platformatic/platformatic

- docs/contributing/documentation-style-guide.md
This PR does the following,
- updates the `documentation-style-guide`
- formatting consistency in titles (using the [APA](https://apastyle.apa.org/style-grammar-guidelines/capitalization/title-case) guide) 
- formatting of examples
- minor wordsmith
> docs: [documentation-style-guide] update formatting, wordsmith

- docs/guides/jwt-auth0.md
URL points to 'reference/db-authorization/intro#user-metadata' instead of 'reference/db-authorization/introduction#user-metadata'
> Fix docs: url points to wrong page

- packages/db/lib/init.mjs
- packages/db/test/cli/init.test.mjs
Currently `npb platformatic db init` creates a config with `logger` level set to `info`: 
```json
{
"server": {
"logger": {
"level": "info"
},
},
```
...which is the default, so this is not necessary anymore.
> Remove logger from config created with `db init`

- packages/sql-graphql/lib/entity-to-type.js
- packages/sql-graphql/test/simple.test.js
Fixes #28 
Basically, we were using the field DB value to get the PK data from `fields` where the keys are all camelCase. So with a non camel-case field, this was failing. 
Fixed and added specific tests
> Correctly handle entity PK when snake_case

- docs/reference/sql-graphql/queries.md
- docs/reference/sql-rest/api.md
- packages/db/tap-snapshots/test/cli/env.test.mjs.test.cjs
- packages/db/tap-snapshots/test/cli/schema.test.mjs.test.cjs
- packages/sql-graphql/lib/entity-to-type.js
- packages/sql-graphql/test/count.test.js
- packages/sql-mapper/lib/entity.js
- packages/sql-mapper/mapper.d.ts
- packages/sql-mapper/test/entity.test.js
- packages/sql-mapper/test/types/mapper.test-d.ts
- packages/sql-mapper/test/where.test.js
- packages/sql-openapi/lib/entity-to-routes.js
- packages/sql-openapi/test/simple.test.js
- packages/sql-openapi/test/tap-snapshots/orderby-openapi-1.cjs
- packages/sql-openapi/test/tap-snapshots/simple-openapi-1.cjs
- packages/sql-openapi/test/tap-snapshots/simple-openapi-2.cjs
- packages/sql-openapi/test/tap-snapshots/simple-openapi-3.cjs
- packages/sql-openapi/test/tap-snapshots/where-openapi-1.cjs
- packages/sql-openapi/test/tap-snapshots/where-openapi-2.cjs
Fixes #32 
There is no portable way to obtain the full count in the same query used with `limit` and `offset`, so two queries are necessary, one for the list and the other for `SELECT COUNT(*)` with the same criteria.
Added a new `findTotalCount` to `entity` so that we don't have to change what `find` returns (currently just the query result with no metadata).
Updated also reference.
```shell
➜ curl -v 'http://localhost:3042/movies?limit=2&offset=0&totalCount=true'
*   Trying 127.0.0.1:3042...
* Connected to localhost (127.0.0.1) port 3042 (#0)
> GET /movies?limit=2&offset=0&totalCount=true HTTP/1.1
> Host: localhost:3042
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< x-total-count: 18
< content-type: application/json; charset=utf-8 …
```
> Optional `X-Total-Count` header in GET

- .github/workflows/docker.yml
@mcollina currently we just tag as `latest`, shall we also tag with version?
> Use to the correct dockerhub repository

- packages/sql-mapper/mapper.js
Partially fixes: #92.
Simple "workaround" to emit queries text on trace using sqlite3 debugging hook: https://github.com/TryGhost/node-sqlite3/wiki/Debugging. 
It doesn't have all the hooks that `createConnectionPool`  but at least it provides the basic query output.
> fix: adds basic query logging for sqlite

- docs/reference/cli.md
- packages/db/help/compile.txt
- packages/db/help/init.txt
- packages/db/help/migrate.txt
- packages/db/help/seed.txt
- packages/db/help/start.txt
- packages/db/help/types.txt
The commands and example code inseveral places aren't displayed correctly on the website.
This PR will fix that.
Example:
Should be highlighted and displayed properlly with new lines and whitespace
> docs[cli]: fix display for code and typos

- packages/db/tap-snapshots/test/cli/schema.test.mjs.test.cjs
- packages/sql-openapi/lib/entity-to-routes.js
- packages/sql-openapi/test/nested.test.js
- packages/sql-openapi/test/tap-snapshots/nested-routes-openapi.cjs
- packages/sql-openapi/test/tap-snapshots/orderby-openapi-1.cjs
- packages/sql-openapi/test/tap-snapshots/simple-openapi-1.cjs
- packages/sql-openapi/test/tap-snapshots/simple-openapi-2.cjs
- packages/sql-openapi/test/tap-snapshots/simple-openapi-3.cjs
- packages/sql-openapi/test/tap-snapshots/where-openapi-1.cjs
Fixes: #8 
Some notes: 
- Renamed `getAllXXX` to `getXXX`. The reason is that we can filter, so we don're really get `all`, IMO is a wrong naming. 
- `/movies/42/posts`: if the movie with PK `42` does not exists, returns HTTP/404, then if there are no posts, `[]`
- `/post/42/movie`: Returns HTTP/404, then if there are no post `42` OR if there is no movie associated.
For the check above this implementation uses 2 `entity.find`. This can be improved with one query (with outer join)
TODO: documentation, will do in a different PR, this one is already too big.
> Nested routes in openapi

- .github/workflows/docker-release.yml
- .github/workflows/docker.yml
This leverage [the `release` event](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release) to trigger the publish on dockerhub.
Then  `${{ github.ref_name }}` contains the name of the version (the tag name). 
Every time we create a new label with a version and we move `latest`
> Docker automatic publish on GH release

- docs/reference/sql-graphql/mutations.md
- docs/reference/sql-mapper/entities/api.md
Should fix #98 
Added some sentences, not sure we need more, but actually I don't find is unclear in current documentation, and now I feel it's kinda redundant. But, well, *repetita iuvant* :)
> Better explaination of the save as upsert

- docs/reference/sql-rest/api.md
This is the missing documentation for https://github.com/platformatic/platformatic/pull/110
> Documentation for the nested routes on openapi

- docs/reference/sql-rest/api.md
- packages/sql-openapi/lib/entity-to-routes.js
- packages/sql-openapi/test/simple.test.js
computes `totalCount` without extra query execution when possible
> refactor: optimize totalCount compute for X-Total-Count header

- packages/db-dashboard/index.js
- packages/db/index.js
- packages/db/lib/metrics-plugin.js
- packages/db/lib/utils.js
- packages/db/test/metrics.test.js
Example of output:
```json
{
"reqMetrics": {
"POST": {
"/movies": {
"reqCountPerStatusCode": {
"200": 4,
"400": 3
},
"totalReqCount": 7,
"medianResponseTime": 1,
"failureRate": 0.43
}
},
"GET": {
"/movies": {
"reqCountPerStatusCode": {
"200": 5
},
"totalReqCount": 5,
"medianResponseTime": 2,
"failureRate": 0
},
"__unknown__": {
"reqCountPerStatusCode": {
"404": 3
},
"totalReqCount": 3,
"medianResponseTime": 1,
"failureRate": 1
}
}
},
"totalReqCount": 15,
"failureRate": 0.4
}
```
> feat: add endpoint for dashboard metrics

- packages/db/lib/gen-types.mjs
- packages/db/lib/init.mjs
- packages/db/lib/schema.js
- packages/db/test/cli/init.test.mjs
- packages/db/test/fixtures/bad-typescript-plugin/platformatic.db.json
- packages/db/test/fixtures/config-to-replace.json
- packages/db/test/fixtures/gen-types/platformatic.db.json
- packages/db/test/fixtures/typescript-plugin/platformatic.db.json
It's painful when you made a typo in an optional property and doesn't see any warning.
> feat(db): restrict additional properties usage in db config

- docs/reference/db/configuration.md
- packages/db/.taprc
- packages/db/index.js
- packages/db/lib/schema.js
- packages/db/test/cli/load-and-reload-files.test.mjs
- packages/db/test/cli/start.test.mjs
- packages/db/test/fixtures/no-hotreload.json
- packages/db/test/fixtures/plugin.mjs
- packages/db/test/load-and-reload-files.test.js
[Had to disable c8 for a branch](https://github.com/platformatic/platformatic/blob/disable-hot-reload/packages/db/index.js#L105) because c8 wrongly reported their coverage (lines are executed and well covered by tests). It might be related with the fact that if tap coverage is enabled instead, it throws in getting the coverage on the very same lines.
To reproduce:
```
npx c8 node ./test/load-and-reload-files.test.js
```
...and check that lines 106-08 are not covered.
> Configuration to disable hot-reload

- packages/config/index.d.ts
- packages/config/index.js
- packages/config/test/watch.test.js
- packages/db/lib/config.js
- packages/db/lib/load-config.mjs
- packages/db/lib/start.mjs
- packages/db/package.json
- packages/db/test/config.test.js
- packages/utils/index.js
- packages/utils/lib/file-watcher.js
- packages/utils/package.json
- packages/utils/test/file-watcher.test.js
- pnpm-lock.yaml
Quick explanations
1. FileWatcher is now an external entity in the `@platformatic/utils` package.
2. There are two instances of FileWatcher used in the Platformatic DB.
- The ConfigManager uses FileWatcher to reload the config and emit an `update` event if there are some changes in the config file or in the files on which the config might depend (it's only `.env` for now).
- The `db` package uses the FileWatcher to watch and reload files used by the server.
That means that we can handle these two events differently. And we can move `--allow-to-watch` and `--watch-ignore` cli options to the config.
> refactor(config): separate FileWatcher from ConfigManager

- packages/cli/cli.js
- packages/cli/test/platformatic.test.js
I think we should exit with code 1 when a command is not found.
Not that I had an issue because of this. Was using the code as an inspiration for the `rescript-platformatic-cli`, and this part was looking wrong to me.
> Exit with 1 when command not found

- docs/reference/sql-rest/api.md
Just yesterday I started building up a react-admin data provider (rest for now, then gql will come) compatible with platformatic here 👉 https://github.com/giacomocerquone/ra-data-platformatic after seeing #33 
and I noticed that the orderby clause was missing from the docs in the SQL to rest section!
> docs: add orderby clause to sql-rest documentation

- docs/reference/sql-mapper/introduction.md
- packages/db/lib/schema.js
- packages/sql-mapper/mapper.js
This feature adds an optional configurable maximum pool size to `sql-mapper`. While the default `10`, as advised by atdatabases, is good enough for most applications, a busier application will benefit from a larger (and configurable) pool size.
refs:
- https://www.atdatabases.org/docs/pg-options
- https://www.atdatabases.org/docs/mysql-options
> feat(sql-mapper): configurable pool size

- packages/db/lib/root-endpoint/index.js
- packages/db/tap-snapshots/test/cli/schema.test.mjs.test.cjs
- packages/db/test/admin.test.js
- packages/db/test/routes.test.js
fixes #163 
This fixes a bug where the platformatic root endpoint `/` (the one that displays the platformatic welcoming page) was being included in the openapi documentation.
This PR introduces the `schema: { hide: true }`  option in the root `/` route definition to exclude it from the openapi documentation and consequently from the swagger ui page.
> fix(db): exclude the root endpoint from the openapi documentation

- docs/reference/cli.md
- packages/db-authorization/README.md
- packages/db/help/compile.txt
- packages/db/help/migrate.txt
- packages/db/help/schema.txt
- packages/db/help/seed.txt
- packages/db/help/start.txt
- packages/db/help/types.txt
This is a follow up to #175 and #195.
- Update Configuration reference docs URL in CLI help texts
- Update generated CLI reference documentation
- Update reference documentation link for @platformatic/db-authorization
Fixes #178.
> Update reference documentation URLs

- CONTRIBUTING.md
fixes #167 
According to pnpm link documentation, we have to use ```(cd packages/cli && pnpm link <dir>)``` for the link to work, but in that case we need to use platformatic through the pnpm always like this
```
pnpm platformatic db
```
If we want to use it globally, we need to specify the --global param as I did on the PR.
> Fixed link of platformatic through pnpm issue

- .github/workflows/docker-release.yml
In the docker release action, we specified the `main` environment, which can be "deployed" only from `main` branch. 
But the docker release is done from the release tag, so the workflow action failed (didn't even start, actually). 
*NOTE*: it's a draft because I still need to test it.
> Docker release fix

- CONTRIBUTING.md
Just aligned the CONTRIBUTING.md file to use `pnpm` when run commands. It should be more easy to understand, the first time I was confused by the alternation of npm and pnpm.
> Always use pnpm to run commands

- docs/guides/add-custom-functionality/extend-rest.md
In guide POST request is described but in example GET handler is using.
> docs(extend-rest): Fix request handler name

- package.json
closes #242 
We're using fastify/pre-commit from the root of the monorepo and it automatically executes `npm test`
I thought it be ok to still keep the devDependency and disable the test script because in the future we might want to add some other script
> chore: avoid running "test" script in pre-commit

- .github/workflows/md-lint.yml
- .gitignore
- .markdownlint-cli2.yaml
- package.json
- pnpm-lock.yaml
Hi maintainers 👋🏻, this pr will add the markdown linter (same as fastify) as written in the issue #231 .
Btw i have a doubt, i also added the gh action CI config, was it implicit in the issue or the general idea was just to add the dependency and configuration?
Thanks for any feedback!
> feat(deps): add markdown linter

- docs/reference/cli.md
- scripts/gen-cli-doc.mjs
This adds the `service` command into the generated CLI reference docs. It also adds a warning notice to avoid directly editing the generated docs and to run the script that generates them instead.
> Include service commands in CLI reference docs

- packages/service/fixtures/options/platformatic.service.yml
- packages/service/fixtures/options/plugin.js
- packages/service/lib/schema.js
- packages/service/package.json
- packages/service/test/cli/start.test.mjs
- pnpm-lock.yaml
This change allows developers to specify the options for the loaded plugin from the main config file.
This partially solves https://github.com/platformatic/platformatic/issues/274.
Note that this feature was half-backed before (it worked with watch disabled) and I'm just completing it.
> Specify plugin options

- docs/reference/db/plugin.md
We got a sneaky typo in the anchor tag when we switched to fastify-sandbox
> Fix typo in link to fastify-sandbox

- docs/reference/db/authorization/introduction.md
- packages/db-authorization/index.js
- packages/db-authorization/test/skip-authorization.test.js
When we use `sql-mapper` in custom plugins, we might want to skip authorization rules, for instance if we need to write an unprotected route. 
Here we add a `skipAuth` parameters for this purpose. 
This does not affect the automatically generated endpoints.
> Param to skip auth when using entities programmatically

- docs/reference/db/configuration.md
The `dashboard` setting in the sample configuration here is invalid: https://oss.platformatic.dev/docs/reference/db/configuration#sample-configuration
> docs: fix sample config enabling dashboard

- docs/reference/db/configuration.md
As mentioned on https://github.com/platformatic/platformatic/issues/305, the current documentation for the logger config is not correct.
From [here](https://github.com/platformatic/platformatic/blob/6da734ffc741a0313bf71298c4fd02f36e182767/packages/service/lib/utils.js#L27), we see that is under the server prop, not the core one.
This PR simply updates the documentation 😊
> Fix documentation for logger

- packages/sql-graphql/lib/relationship.js
When the `assert` fails, debugging the root cause is painful, because there are enough information.
Applying this code the message becomes from:
```
AssertionError [ERR_ASSERTION]: The column with id reference must be ended with `id` postfix`
```
to:
```
AssertionError [ERR_ASSERTION]: The column with id reference must be ended with "id" postfix (table: "my_table_name", foreign table: "my_fx", column: "my_col")
```
> feat(log): Enhance assert error message

- packages/db-authorization/index.js
- packages/db-authorization/test/fields-permissions.test.js
> fix checking for authorized fields if no field is specified

- docs/reference/db/migrations.md
The current anchor link for manually `db migrate` documentation is broken.
I've not found the correct one, so I added a simple description for it.
> Fix db migrate documentation

- docs/guides/jwt-auth0.md
- docs/reference/db/authorization/introduction.md
- packages/db-authorization/lib/jwt.js
- packages/db-authorization/test/jwt.test.js
- packages/db/lib/schema.js
In Auth0 we have [restrictions](https://auth0.com/docs/secure/tokens/json-web-tokens/create-custom-claims#general-restrictions) about ther custom claim. 
One is that they MUST have a namespace for access tokens. 
So, instead of  `X-PLATFORMATIC-ROLE` we receive `https://platformatic.dev/X-PLATFORMATIC-ROLE`. 
This is a problem when we have BOTH JWT and webhook configured.
With this change it's possible to specify in JWT configuration a  `namespace` that is automatically removed when extracting user metadata from JWT claims, so that we can user a `roleKey` without a namespace (or the default X-PLATFORMATIC-ROLE)
> JWT namespace configuration

- packages/db-dashboard/src/components/metrics/Metrics.jsx
Simple `setTimeout` to refresh the metrics ervery 5 seconds without reloading the page.
> Automatic refresh of dashboard metrics

- docs/reference/sql-mapper/entities/api.md
- packages/db/tap-snapshots/test/cli/env.test.mjs.test.cjs
- packages/db/tap-snapshots/test/cli/schema.test.mjs.test.cjs
- packages/sql-graphql/lib/entity-to-type.js
- packages/sql-graphql/test/where.test.js
- packages/sql-mapper/lib/entity.js
- packages/sql-mapper/mapper.d.ts
- packages/sql-mapper/test/where.test.js
- packages/sql-openapi/lib/entity-to-routes.js
- packages/sql-openapi/test/tap-snapshots/nested-routes-openapi-recursive.cjs
- packages/sql-openapi/test/tap-snapshots/nested-routes-openapi.cjs
- packages/sql-openapi/test/tap-snapshots/orderby-openapi-1.cjs
- packages/sql-openapi/test/tap-snapshots/simple-openapi-1.cjs
- packages/sql-openapi/test/tap-snapshots/simple-openapi-2.cjs
- packages/sql-openapi/test/tap-snapshots/simple-openapi-3.cjs
- packages/sql-openapi/test/tap-snapshots/simple-openapi-4.cjs
- packages/sql-openapi/test/tap-snapshots/updateMany-openapi-1.cjs
- packages/sql-openapi/test/tap-snapshots/where-openapi-1.cjs
- packages/sql-openapi/test/tap-snapshots/where-openapi-2.cjs
> Add `like` support on where clause

- docs/reference/db/schema-support.md
- packages/sql-mapper/lib/entity.js
- packages/sql-mapper/lib/queries/mysql-shared.js
- packages/sql-mapper/lib/queries/mysql.js
- packages/sql-mapper/lib/queries/pg.js
- packages/sql-mapper/lib/queries/shared.js
- packages/sql-mapper/lib/queries/sqlite.js
- packages/sql-mapper/lib/utils.js
- packages/sql-mapper/mapper.js
- packages/sql-mapper/test/helper.js
- packages/sql-mapper/test/schema.test.js
This fixes: https://github.com/platformatic/platformatic/issues/362
Basically, we use fully qualified names for tables (so `schema.table`) for every DB that supports schema (so no `sqlite`) 
> Schema support for all DBs

- packages/db-authorization/lib/webhook.js
> feat: set accept-encoding header for the webhook request

- .npmignore
> chore: fix typo in .npmignore

- docs/reference/cli.md
- docs/reference/db/configuration.md
- docs/reference/service/configuration.md
- packages/db/db.mjs
- packages/db/help/schema.txt
- packages/db/lib/gen-schema.mjs
- packages/db/lib/init.mjs
- packages/db/test/cli/gen-schema.test.mjs
- packages/db/test/cli/init.test.mjs
- packages/db/test/cli/schema.test.mjs
The goal of this PR is to improve the developer experience and avoid mistakes when updating the configuration of Platformatic DB.
* Running `npx platformatic db init` now creates a JSON schema in `platformatic.db.schema.json`:
* When opening the `platformatic.db.json` your IDE can now add suggestions thanks to the`$schema` property:
* You can now notice some suggestions like mandatory/missing fields, types, default values
* The config schema follows the documentation available [here](https://oss.platformatic.dev/docs/reference/db/configuration/)
> feat(config): Add schema JSON

- packages/sql-mapper/mapper.js
Signed-off-by: Roberto Bianchi <roberto.bianchi@spendesk.com>
Related to [this issue](https://github.com/platformatic/platformatic/issues/459), the goal of this PR is to have more details in case the check for the primary key of all entities fails.
It will simplify the debugging, giving info regarding schema, fields and other DB data.
The message will change from `Error: Cannot find any primary keys for AnonymousCard` to
```
Cannot find any primary keys for AnonymousCard entity: {"name":"AnonymousCard","singularName":"anonymousCard","pluralName":"anonymousCards","primaryKeys":{},"table":"anonymous_cards","schema":"my_clone_schema","fields":{"id":{"sqlType":"varchar","isNullable":true,"camelcase":"id"} ...
```
> feat(sql-mapper): Enhance error message

- packages/create-platformatic/src/db/create-db-cli.mjs
- packages/create-platformatic/src/ghaction.mjs
- packages/create-platformatic/src/service/create-service-cli.mjs
- packages/create-platformatic/src/utils.mjs
- packages/create-platformatic/test/ghaction.test.mjs
- packages/create-platformatic/test/utils.test.mjs
Creates now:
- Accepts `.` as directory
- `.` is now the default
- The GH action is ALWAYS created in the folder where the `create` is launched, and a `warn` is logged if this is not a `git` repo. 
> Create now accepts current directory (default) 

- packages/create-platformatic/src/db/create-db-cli.mjs
- packages/create-platformatic/src/db/create-db.mjs
- packages/create-platformatic/src/ghaction.mjs
- packages/create-platformatic/src/service/create-service-cli.mjs
- packages/create-platformatic/src/service/create-service.mjs
- packages/create-platformatic/test/ghaction.test.mjs
Example:
```
name: Deploy Platformatic application to the cloud
on:
pull_request:
paths-ignore:
- 'docs/**'
- '**.md'
jobs:
build_and_deploy:
runs-on: ubuntu-latest
steps:
- name: Checkout application project repository
uses: actions/checkout@v3
- name: npm install --omit=dev
run: npm install --omit=dev
- name: Deploy project
uses: platformatic/onestep@latest
with:
github_token: ${{ secrets.GITHUB_TOKEN }}
platformatic_api_key: ${{ secrets.PLATFORMATIC_API_KEY }}
platformatic_config_path: ./platformatic.db.json
env:
DATABASE_URL: sqlite://./db.sqlite 
PLT_SERVER_LOGGER_LEVEL: info 
PORT: 3042 
PLT_SERVER_HOSTNAME: 127.0.0.1 
```
> Add the correct env in gh action

- packages/service/lib/schema.js
Since db generally derives from service, and because this is the service schema, it seemed like these URLs should reference service instead of db.
> remove db references from service schemas

- .github/workflows/ci.yml
This will make sure that `ci.yml` workflow will always pick up the most recent-file committed in a given PR.
Per: https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#pnpm
Unblocks: https://github.com/platformatic/platformatic/pull/472
> ci: Always use commited pnpm lock-file in CI

- packages/create-platformatic/src/db/create-db-cli.mjs
Small fix for this comment we missed: https://github.com/platformatic/platformatic/pull/488/files#r1049393012
> Wrong warn message fix for Platformatic creator

- packages/create-platformatic/src/db/create-db-cli.mjs
`npx platformatic db schema config` does not send the schema to stdout, but creates the schema file directly,  so the ridirection is wrong. 
> Further fix on the warn messages if npm install is not done

- packages/db-authorization/index.js
- packages/db-authorization/test/simple-rest.test.js
This change follows the pattern set in `updateMany` of passing `restOpts`. This allows for changes in **@platformatic/sql-mapper** without major changes to this package.
This also unblocks the use of transactions when using `save` in a Platformatic application. The `tx` option is lost without this update.
> Pass through additional options on entities from db-authorization

- packages/authenticate/authenticate.js
- packages/cli/cli.js
- packages/cli/test/platformatic.test.js
- packages/db/db.mjs
- packages/db/lib/start.mjs
- packages/db/test/cli/auto-config.test.js
- packages/db/test/cli/env.test.mjs
- packages/db/test/cli/helper.js
- packages/db/test/cli/validations.test.mjs
- packages/db/test/migrate/migrate.test.mjs
- packages/db/test/migrate/validations.test.mjs
- packages/service/service.mjs
- packages/service/test/cli/helper.mjs
- packages/service/test/cli/validations.test.mjs
- pnpm-lock.yaml
~Using `process.exitCode = 1` is unfortunate, but otherwise there is no way to test the subcommand output, due to mixed usage of sync/async code under the hood.~ _fixed thanks to `3.2.0` update of `commist`_.
~Currently blocked by https://github.com/mcollina/help-me/pull/16~
Fixes https://github.com/platformatic/platformatic/issues/450
Replaces https://github.com/platformatic/platformatic/pull/462
> fix(cli): Ensure that commands exist when calling them

- packages/sql-graphql/lib/entity-to-type.js
- packages/sql-graphql/test/enum.test.js
- packages/sql-graphql/test/helper.js
Hi! 👋🏼 
If a column has an enum type and starts with a number, we have this error:
`GraphQLError: Names must start with [_a-zA-Z] but "123" does not.`
This code adds an underscore to the enum value we're going to use.
> fix(graphql): Name not start with letter or underscore

- packages/sql-graphql/lib/entity-to-type.js
Related to this [issue](https://github.com/platformatic/platformatic/issues/507), this code change enables to add more logging info in case of an error generating the `GraphQLEnumType`.
> feat(graphql): Enhance error handling enum type

- packages/create-platformatic/src/create-package-json.mjs
- packages/create-platformatic/src/db/create-db-cli.mjs
- packages/create-platformatic/src/ghaction.mjs
- packages/create-platformatic/src/service/create-service-cli.mjs
- packages/create-platformatic/test/create-package-json.test.mjs
- packages/create-platformatic/test/ghaction.test.mjs
If the project has TS plugins, the GH action now executes `npx tsc` so that typescript is transpiled
> `tsc` build step in GH action

- packages/db/index.js
> Do not create types if migrations are not run when starting

- packages/sql-graphql/lib/entity-to-type.js
- packages/sql-graphql/test/enum.test.js
This PR fixes the case when two tables have the same enum name.
To reproduce, run `platformatic db start` using a table like this one (or see the test added):
```
CREATE TABLE enum_tests (
id INTEGER NOT NULL,
test_enum ENUM ('1', '2', '3') DEFAULT NULL,
PRIMARY KEY (id)
);
CREATE TABLE simple_types (
pk INTEGER NOT NULL,
test_enum ENUM ('4', '5', '6') DEFAULT NULL,
PRIMARY KEY (pk)
);
```
> fix(graphql): Handle duplicated enum names

- packages/cli/package.json
- pnpm-lock.yaml
desm was saved in devDeps, hopefully this is an ok fix.
Signed-off-by: MzUgM <108896003+MzUgM@users.noreply.github.com>
> fix: break in production environments

- packages/sql-openapi/lib/entity-to-routes.js
- packages/sql-openapi/test/multiple-table.test.js
In the case of tables with foreign keys that are pointing to the same primary keys, Platformatic will fail ([see the example on the test](https://github.com/platformatic/platformatic/compare/main...rozzilla:platformatic:fix/sql-openapi/multiple-tables-with-fks-pointing-to-same-pks?expand=1#diff-9da90ce22120ec5d5514cf69b122d43810af26b27933ebf72febddd4b0f7be60R13)).
This PR fixes this case, and adds an error handler on the creation of the Fastify route, in order to give more details to the developer in case of other issues.
> fix(sql-openapi): Multiple tables with FKs pointing to same PKs

- packages/sql-openapi/lib/entity-to-routes.js
- packages/sql-openapi/test/same-fk-name.test.js
If a table has multiple foreign keys that point to the exact same primary key, platformatic will fail with:
```
/platformatic/node_modules/.pnpm/find-my-way@7.3.1/node_modules/find-my-way/index.js:301
throw new Error(`Method '${method}' already declared for route '${path}' with constraints '${JSON.stringify(constraints)}'`)
^
Error: Method 'GET' already declared for route '/mfaProcedures/:/factor' with constraints '{}'
at Router._on (/platformatic/node_modules/.pnpm/find-my-way@7.3.1/node_modules/find-my-way/index.js:301:13)
at Router.on (/platformatic/node_modules/.pnpm/find-my-way@7.3.1/node_modules/find-my-way/index.js:136:10)
at Object.addNewRoute (/platformatic/node_modules/.pnpm/fastify@4.10.2/node_modules/fastify/lib/route.js:301:16)
at Object.route …
```
> fix(sql-openapi): Same FK with different names

- packages/utils/lib/file-watcher.js
Simple fix for an issue reported on Windows by @tonysnowboardunderthebridge, that `filename` was `null` and that created a fatal error in this function
```js
isFileAllowed (fileName) {
if (this.allowToWatch === null) return true
return this.allowToWatch.some((allowedFile) => minimatch(fileName, allowedFile))
}
```
Signed-off-by: Leonardo Rossi <leonardo.rossi@gmail.com>
> Check filename is not null before handling restart

- docs/reference/db/logging.md
The `logger` object is under `server`, not `core` in the config objects.
> docs: fix logger docs

- packages/sql-graphql/lib/entity-to-type.js
- packages/sql-graphql/test/enum.test.js
Fix for https://github.com/platformatic/platformatic/issues/568.
Testing this, I also confirm that mutations for enums with special characters fail (as mentioned [here](https://github.com/platformatic/platformatic/pull/403#issuecomment-1377130428)).
> fix(sql-graphql): Enum with special chars

- packages/service/index.js
- packages/service/test/config.test.js
`deepmerge()` does not handle certain edge cases because it only copies enumerable properties. This commit adds a helper function to service that can be used to adjust for these edge cases.
> service: adjust config after deepmerge()

- packages/db/index.js
- packages/service/index.js
Attach the schema to the app so that `buildServer()` can access it. With this change, the config manager related code can be isolated in one place.
> reduce duplication in buildServer()

- packages/sql-graphql/lib/relationship.js
- packages/sql-graphql/test/helper.js
- packages/sql-graphql/test/schema.test.js
Regarding this [issue](https://github.com/platformatic/platformatic/issues/458), the logging info added on this PR was crucial in understanding what's going wrong.
To replicate this scenario, you can look at the [tests](https://github.com/platformatic/platformatic/compare/main...rozzilla:platformatic:feat/sql-graphql/enhance-error-logging-for-fk-errors?expand=1#diff-dbdd48775f4c0dc2369209c0cfb588239aad4bd4cb4049e60c8486b0467db07eR169).
I had to add 2 new schemas and 2 new tables to create proper tests for this error.
> feat(sql-graphql): Enhance error logging for FK errors

- packages/db/lib/seed.mjs
- packages/db/package.json
- packages/db/test/cli/seed.test.mjs
- packages/db/test/fixtures/valid-config-files/platformatic.db.json
- packages/db/test/fixtures/valid-config-files/platformatic.db.json5
- packages/db/test/fixtures/valid-config-files/platformatic.db.tml
- packages/db/test/fixtures/valid-config-files/platformatic.db.toml
- packages/db/test/fixtures/valid-config-files/platformatic.db.yaml
- packages/db/test/fixtures/valid-config-files/platformatic.db.yml
- pnpm-lock.yaml
> fix(db): `db seed` should try all known config file names by default

- packages/db/lib/gen-migration.mjs
- packages/db/lib/migrate.mjs
- packages/db/lib/start.mjs
- packages/db/test/cli/gen-migration.test.mjs
- packages/db/test/cli/migrate.test.mjs
> fix: hide call stack on migration errors

- packages/db-dashboard/package.json
- pnpm-lock.yaml
> Lock graphiql dep to 2.2.0 avoid issues with missing @graphiql/toolkit v0.8.1

- packages/db/lib/gen-types.mjs
- packages/db/package.json
- packages/db/test/cli/gen-types.test.mjs
- packages/db/test/fixtures/chars-gen-types/index.d.ts
- packages/db/test/fixtures/chars-gen-types/index.test-d.ts
- packages/db/test/fixtures/chars-gen-types/migrations/001.do.sql
- packages/db/test/fixtures/chars-gen-types/package.json
- packages/db/test/fixtures/chars-gen-types/platformatic.db.json
- packages/db/test/helper.js
- pnpm-lock.yaml
Currently, if a table has special chars like `-` in the name, the generated types are wrong.
To make an example, with [this](https://github.com/platformatic/platformatic/compare/main...rozzilla:platformatic:fix/db/properly-format-entity-type-name?expand=1#diff-7c7c99cb3cfdd787010537e474556d93f2ff0b24527adcc63b82710f674d6ad4R1) table, the following type is created:
```
declare interface PltDb {
id: number;
name?: string;
}
export { plt_db };
```
and this generates a TS error.
This PR creates a fix for this, applying the right formatting to the generated types.
> fix(db): Properly format entity type name

- packages/create-platformatic/src/ghaction.mjs
- packages/create-platformatic/test/ghaction.test.mjs
https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/
> fix: add permissions to the GH action workflow script

- docs/reference/db/configuration.md
- docs/reference/db/dashboard.md
[Discord discussion](https://discord.com/channels/1011258196905689118/1075349275921371197/1075361253104554044)
> docs(dashboard): Add info boxes

- docs/reference/db/configuration.md
- docs/reference/db/dashboard.md
- package.json
- packages/config/test/fixtures/simple.json
- packages/config/test/fixtures/simple.json5
- packages/config/test/fixtures/simple.toml
- packages/config/test/fixtures/simple.yaml
- packages/config/test/load.test.js
- packages/db-dashboard/index.html
- packages/db-dashboard/index.js
- packages/db-dashboard/package.json
- packages/db-dashboard/scripts/fix-dashboard-env.js
- packages/db-dashboard/src/App.jsx
- packages/db-dashboard/src/components/Header.jsx
- packages/db-dashboard/src/components/Navbar.jsx
- packages/db-dashboard/src/components/metrics/Metrics.jsx
- packages/db-dashboard/test/e2e/fixtures/e2e-test-config.json
- packages/db/index.js
- packages/db/lib/schema.js
- packages/db/test/config.test.js
- packages/db/test/dashboard.test.js
- packages/db/test/start-and-stop.test.js
- packages/shared/index.js
- packages/shared/lib/errors.d.ts
- packages/shared/lib/errors.js
- packages/shared/package.json
- pnpm-lock.yaml
@mcollina this may be a breaking change in configuration because I renamed `dashboard.rootPath` to `dashboard.path` and that would be a string. 
@Eomm I used the `{ path: ... }` pattern to be consistent with the `plugins` configuration 
Let me know what you think
Fixes #657 
Signed-off-by: Leonardo Rossi <leonardo.rossi@gmail.com>
> Setup Dashboard on custom endpoint

- packages/db-dashboard/src/components/Navbar.jsx
Current bug:
Now:
Explanation of the 1-line fix: now `react-router-dom` can properly detect if the `NavLink` is active or not, since we append `/` to it 😉
> fix(dashboard): Active selector

- packages/db/lib/gen-types.mjs
- packages/db/test/fixtures/typescript-plugin/global.d.ts
By default, the type definition for the `fastify` method called `getSchema` is not narrowed down, since it accepts `string` as a parameter and `unknown` as a return value.
This PR overrides the type definition in the `global.d.ts`, making it more specific.
> feat(types): Generate better getSchema definition

- packages/create-platformatic/src/create-package-json.mjs
- packages/create-platformatic/test/create-package-json.test.mjs
In some cases (for example after a TS error), the build is not up-to-date, and to properly regenerate it you need to remove the `dist` folder and create it again. This PR creates a new `clean` option for TS projects and add it to the `start` command.
> chore(package.json): Update template

- docs/reference/cli.md
- packages/db/lib/start.mjs
- packages/db/test/cli/start.test.mjs
- packages/service/index.js
- packages/service/lib/schema.js
#670 
If I got this correctly one more thing would be to add test.
I wanted to add test in `start.test.mjs` something like https://github.com/platformatic/platformatic/blob/e9f7daaf620ff10562eea9b10b443066e661138d/packages/db/test/cli/start.test.mjs#L246
But seems like this one is already failing ?
```js
FAIL ​ test/cli/start.test.mjs
✖ test unfinished
test: start with hotreload disabled
stack: |
file://test/cli/start.test.mjs:246:1
at:
line: 246
column: 1
file: file://test/cli/start.test.mjs
```
Is `no-hotreload.json` correct since I can't find that 
```
"watch": {
"hotReload": false
}
```
is valid setting?
> feat: global hot reload setting in cli

- docs/reference/db/introduction.md
This is related to #693. I retrieved the minimum required versions from the docker-compose file and from the GitHub actions.
> Adds minimum supported versions for databases

- .github/workflows/publish-schemas.yml
- package.json
- packages/authenticate/package.json
- packages/cli/package.json
- packages/config/package.json
- packages/create-platformatic/package.json
- packages/db-authorization/package.json
- packages/db-core/package.json
- packages/db-dashboard/package.json
- packages/db-ra-data-rest/package.json
- packages/db/lib/schema.js
- packages/db/package.json
- packages/db/test/cli/init.test.mjs
- packages/db/test/cli/schema.test.mjs
- packages/db/test/schema.test.js
- packages/service/lib/schema.js
- packages/service/package.json
- packages/service/test/cli/gen-schema.test.mjs
- packages/service/test/schema.test.js
- packages/shared/package.json
- packages/sql-events/package.json
- packages/sql-graphql/package.json
- packages/sql-json-schema-mapper/package.json
- packages/sql-mapper/package.json
- packages/sql-openapi/package.json
- packages/utils/package.json
This PR adds the logic to automatically upload the configuration schemas to the schemas repository, which will automatically be published as https://platformatic.dev/schemas.
Therefore, each configuration schema will be published at https://platformatic.dev/schemas/v{version}/db and https://platformatic.dev/schemas/v{version}/db, where version is what is specified in `package.json`.
In this PR I have bumped the release to v0.17.0-dev to verify everything would work fine once landed on main.
> Add setup for schema store

- docs/guides/deployment/deployment.md
I think this was missed in https://github.com/platformatic/platformatic/pull/618. I'm not quite sure if the `deployment.md` is the right place for it.
Anyway, I think adding it as a configuration property would be good. Something like:
```json
"server": {
"welcomePage": false
}
```
> doc: add removing welcome page guide on deployment

- packages/create-platformatic/src/db/create-db-cli.mjs
- packages/create-platformatic/src/db/create-db.mjs
- packages/create-platformatic/src/service/create-service-cli.mjs
- packages/create-platformatic/src/service/create-service.mjs
- packages/db/lib/init.mjs
- packages/db/test/cli/init.test.mjs
All the new generated config files will now use the public schema instead of the locally generated one.
> Use the published schemas instead of the local one

- packages/cli/README.md
The logo image URL in the README needs to be absolute for it to render correctly on npm. This will fix the broken image that's currently displaying on https://www.npmjs.com/package/platformatic.
> Fix logo in README for npm

- packages/service/lib/load-config.js
Related to https://github.com/platformatic/platformatic/issues/523, this PR changes the error message from `Missing config file` to:
```
Missing config file!
Be sure to have a config file with one of the following names: platformatic.service.json
platformatic.service.json5
platformatic.service.yaml
platformatic.service.yml
platformatic.service.toml
platformatic.service.tml
In alternative run "npm create platformatic@latest" to generate a basic plt service config.
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
```
> chore(service): Improve error message

- packages/service/index.js
- packages/service/test/cli/compile.test.mjs
I've recently had issues running typescript tests with Platformatic.
In short, when running Platformatic DB inside an inner folder, the `configPath` and `tsConfigPath` were correct:
```
// $: plt db start
{
configPath: '/Users/rozzilla/fastify-poc/platformatic.db.json',
tsConfigPath: '/Users/rozzilla/fastify-poc/tsconfig.json'
}
```
When running inside a test, instead, those 2 paths were wrong:
```
// $: test
{
configPath: '/Users/rozzilla/fastify-poc',
tsConfigPath: '/Users/rozzilla/tsconfig.json'
}
```
This PR fixes it.
> fix(tests): TypeScript config error

- docs/guides/prisma.md
This fixes a simple typo in the "Integrate Prisma with Platformatic DB" guide, see https://oss.platformatic.dev/docs/guides/prisma#setup-prisma.
When running the specified init command:
```bash
npx prisma init --datasource-provider postgres # or sqlite, mysql, sqlserver, cockroachdb
```
I get the following error:
```
Error: Provider "postgres" is invalid or not supported. Try again with "postgresql", "mysql", "sqlite", "sqlserver", "mongodb" or "cockroachdb".
```
The command should be:
```bash
npx prisma init --datasource-provider postgresql # or sqlite, mysql, sqlserver, cockroachdb
```
See init arguments on prisma docs: https://www.prisma.io/docs/reference/api-reference/command-reference#arguments
> docs: fix typo in guide for prisma database provider init option

- packages/create-platformatic/src/cli-options.mjs
- packages/create-platformatic/src/create-package-json.mjs
- packages/create-platformatic/src/db/create-db-cli.mjs
- packages/create-platformatic/src/service/create-service-cli.mjs
- packages/create-platformatic/src/service/create-service.mjs
- packages/create-platformatic/test/cli-options.test.mjs
- packages/create-platformatic/test/service/create-service.test.mjs
Issue #628
This is a PR for adding typescript templates in create-platformatic-service CLI. CLI generates these templates if the user selects the TS option. I'm especially appreciated that if someone reviews it's the correct way to use TS with Fastify.
```typescript
const TS_PLUGIN_WITH_TYPES_SUPPORT = `\
import { FastifyInstance, FastifyPluginOptions } from 'fastify'
export default async function (fastify: FastifyInstance, opts: FastifyPluginOptions) {
fastify.decorate('example', 'foobar')
}
`
const TS_ROUTES_WITH_TYPES_SUPPORT = `\
import { FastifyInstance, FastifyPluginOptions } from 'fastify'
declare module 'fastify' {
interface FastifyInstance {
example: string
}
}
export default async function (fastify: FastifyInstance, opts: FastifyPluginOptions) {
fastify.get('/', async (request, …
```
> Add typescript templates create-platformatic-service in CLI

- .github/workflows/ci.yml
- packages/db/package.json
- packages/service/package.json
- pnpm-lock.yaml
I figured out that quite a few of the problems we had with stability of the CI were due to `@matteo.collina/worker` not installing properly because _the disk was busy_ and we could not download the node headers correctly. I think this would help solve some of those issues.
> Enforce @matteo.collina/worker as a devDep in service and db to retry the build

- docs/reference/service/configuration.md
- packages/service/index.js
- packages/service/lib/config.js
- packages/service/lib/schema.js
- packages/service/package.json
- packages/service/test/https.test.js
- pnpm-lock.yaml
This commit updates service to support loading keys and certs as strings or from file.
Fixes #777
> service: add support for HTTPS keys and certs

- docs/guides/securing-platformatic-db.md
Adds an example of `adminSecret` auth on how to use rules associated with it's default role
> add rules section and add admin default role info

- .github/workflows/publish-releases.yml
Thanks to [this comment](https://github.com/orgs/community/discussions/16244#discussioncomment-5232285) we discovered that releases created by `github-actions` user, do not trigger action that have
```yaml
on:
release:
...
```
So at the moment when creating release, all the workflows like Docker release, Discord announce etc... are not triggered.
Need to add a `GH_RELEASE_TOKEN` in this repository's secrets and @mcollina should fill it with it's token.
At the moment there is no way that the release author is an Organization, only an user can do that.
> Do not use GITHUB_TOKEN to create releases

- .gitignore
- packages/sql-graphql/lib/utils.js
- packages/sql-graphql/test/datatypes.test.js
- packages/sql-json-schema-mapper/index.js
- packages/sql-json-schema-mapper/test/simple.test.js
Most node.js database clients return numeric and decimal as string because 64 bit float (number) cannot always represent the value without potential loss of accuracy.
> Return numeric and decimal db types as string

- packages/client/index.js
- packages/client/test/fixtures/movies/plugin.js
- packages/client/test/openapi.test.js
Closes #883
Adds support for 204 level responses by dumping the empty body.
Also, I changed the `JSON.Stringify()` to be on `body` rather than `args`, I think this was is a mistake? By setting the properties to undefined withing the params loops I assume you're building a payload without data duplicated from the path params and query, so body should be sent?
Thanks!
> support bodyless 204 responses (#883)

- docs/reference/sql-mapper/entities/api.md
- docs/reference/sql-openapi/api.md
- packages/db/tap-snapshots/test/cli/env.test.mjs.test.cjs
- packages/db/tap-snapshots/test/cli/schema.test.mjs.test.cjs
- packages/sql-graphql/lib/entity-to-type.js
- packages/sql-graphql/test/or.test.js
- packages/sql-mapper/lib/entity.js
- packages/sql-mapper/test/or.test.js
- packages/sql-openapi/lib/shared.js
- packages/sql-openapi/test/or.test.js
- packages/sql-openapi/test/tap-snapshots/nested-routes-openapi-recursive.cjs
- packages/sql-openapi/test/tap-snapshots/nested-routes-openapi.cjs
- packages/sql-openapi/test/tap-snapshots/orderby-openapi-1.cjs
- packages/sql-openapi/test/tap-snapshots/simple-openapi-1.cjs
- packages/sql-openapi/test/tap-snapshots/simple-openapi-2.cjs
- packages/sql-openapi/test/tap-snapshots/simple-openapi-3.cjs
- packages/sql-openapi/test/tap-snapshots/simple-openapi-4.cjs
- packages/sql-openapi/test/tap-snapshots/updateMany-openapi-1.cjs
- packages/sql-openapi/test/tap-snapshots/where-openapi-1.cjs
- packages/sql-openapi/test/tap-snapshots/where-openapi-2.cjs
Closes #847
Possibility for `OR` conditions in where clause
Inside the where object we pass the `or` as the key and an array of the conditions as value
```js
const data = await entity.find({
where: {
or: [
{
counter: {
eq: 20
}
},
{
counter: {
gte: 30
}
}
]
}
})
```
Inside the where object we pass the `or` as the key and an array of the conditions as value
```graphql
query {
posts(where: { or: [ { counter: { eq: 10 } }, { counter: { gte: 30 } } ] }) {
id
title
longText
counter
}
}
```
In search query params we pass the `where.or` as the key and as a value we pass inside the parenthesis the conditions as we would in normal query but without the `where` prefix. We separate the or parts by `|` (pipe), the reason that I choose pipe as a separator is because we should also support `in` and …
> feat(#847): add 'or' condition on where clause

- packages/client/index.js
- packages/client/test/fixtures/auth/openapi.json
- packages/client/test/fixtures/auth/plugin.js
- packages/client/test/fixtures/movies/openapi.json
- packages/client/test/fixtures/movies/plugin.js
- packages/client/test/openapi.test.js
Closes #875
Ensures client inputs which map to header paramters are actually sent with request. Thanks!
> fix: send header parameters from platformatic/client (#875)

- packages/client/index.js
- packages/client/test/fixtures/movies/platformatic-prefix.db.json
- packages/client/test/openapi.test.js
Closes #876
Hi, my apporach to this problem is as follows:
* If only a URL is provided, strip paths and use root as basePath - I didn't know if it would be safe to always assume the first path in the openapi JSON URL will be required by the endpoints, as there is probably mulitple standards?
* If a URL and JSON path are provided, use the full provided URL and append paths from the spec
```javascript
// baseUrl === 'https://test-server'
app.register(pltClient, {
type: 'openapi',
name: 'dogs',
url: 'https://test-server/documentation/json'
})
// baseUrl === 'https://test-server/cats'
app.register(pltClient, {
type: 'openapi',
name: 'cats',
path: join(__dirname, 'cats.openapi.json'),
url: 'https://test-server/cats'
})
```
Lemme know what you think, thanks!
> feat(#876): allow for URL context paths when suppling openapi JSON path

- packages/sql-graphql/lib/utils.js
Underneath GraphQLID technically is same as a GraphQLString, however, using ID type conveys a bit more meaning that the field value is not meant to be in a human friendly format.
> Use GraphQLID type for uuid

- packages/cli/lib/gh.js
- packages/cli/lib/upgrade.js
- packages/cli/package.json
- packages/client-cli/cli.mjs
- packages/client-cli/package.json
- packages/config/index.js
- packages/config/test/fixtures/platformatic.db.json
- packages/config/test/fixtures/platformatic.service.json
- packages/config/test/index.test.js
- packages/create-platformatic/package.json
- packages/create-platformatic/src/utils.mjs
- packages/db-dashboard/package.json
- packages/db-dashboard/scripts/fix-dashboard-env.js
- packages/db/lib/load-config.mjs
- packages/service/lib/load-config.js
- packages/service/lib/utils.js
- packages/service/test/utils.test.js
- pnpm-lock.yaml
This commit adds two static methods to the `ConfigManager` class:
- `listConfigFiles()` - this lists well known config files with or without a project type filter. It does not touch the file system at all.
- `findConfigFile()` - this looks for a well known config file (with or without a project type filter) in a specific directory.
The goal of these methods is to reduce code duplication in the codebase and make it simpler to discover config files before creating a `ConfigManager` instance.
> feat: add ConfigManager methods for finding configs

- .gitignore
- docs/reference/db/configuration.md
- packages/db/index.js
- packages/db/lib/migrate.mjs
- packages/db/lib/schema.js
- packages/db/lib/utils.js
- packages/db/test/cli/migrate.test.mjs
- packages/db/test/fixtures/no-auto-apply.json
- packages/db/test/fixtures/schemalock.json
- packages/db/test/fixtures/schemalock2.json
- packages/sql-mapper/lib/entity.js
- packages/sql-mapper/mapper.js
- packages/sql-mapper/test/schema.test.js
Retrieving the database schema metadata via SQL at every startup of the database adds quite a bit of latency and it increase cold start time. This change allows us to store it on disk so that it can be skipped at startup time.
> Store & Reload the schema metadata on disk

- packages/client-cli/cli.mjs
- packages/client-cli/help/help.txt
- packages/client-cli/lib/gen-openapi.mjs
- packages/client-cli/test/cli-openapi.test.mjs
- packages/client/index.js
- packages/client/test/openapi.test.js
Closes #877
Adds support to get full HTTP response by passing `fullResponse: true`:
```javascript
app.register(pltClient, {
type: 'openapi',
name: 'cats',
path: join(__dirname, 'cats.openapi.json'),
url: 'https://cats/',
fullResponse: true,
})
// { statusCode: 200, headers: { 'content-type': 'application/json' }, body: { type: 'Norwegian forest' } }
await app.cats.getCat(10)
```
> feat(#877): add support to receive full response objects from client

- packages/client-cli/lib/gen-openapi.mjs
- packages/client-cli/lib/utils.mjs
- packages/client-cli/test/cli-graphql.test.mjs
- packages/client-cli/test/fixtures/movies/plugin.js
- packages/client/test/fixtures/movies/plugin.js
Hi,
In https://github.com/platformatic/platformatic/pull/884 I added support for 204 responses with no body to the client plugin, the changes in this PR allow the client-cli to generate `undefined` types for those responses rather than throw because of a lack of a 200 response.
Example:
```json
{
"responses": {
"204": {
"description": "Delete an task template",
"content": {
"*/*": {
"schema": {
"type": "object"
}
}
}
}
}
}
```
Gives:
```typescript
interface Tasks {
deleteTaskTemplate(req: DeleteTaskTemplateRequest): Promise<undefined>;
}
```
I've also allowed 201 responses and skip attempting to add interface properties if there's no schema defined for the respone (again to prevent client-cli throwing in this case). This is due to having a bunch of Java/Spring APIs in my organisation that …
> client-cli: set response types to undefined for 204 responses, support 201 and empty objects

- .github/workflows/ci.yml
- docs/reference/cli.md
- docs/reference/start/programmatic.md
- packages/cli/cli.js
- packages/cli/help/help.txt
- packages/cli/help/start.txt
- packages/cli/package.json
- packages/cli/test/fixtures/platformatic.service.json
- packages/cli/test/start.test.js
- packages/start/LICENSE
- packages/start/NOTICE
- packages/start/fixtures/dbApp/platformatic.db.json
- packages/start/fixtures/invalid-schema-type.config.json
- packages/start/fixtures/no-schema.config.json
- packages/start/fixtures/serviceApp/platformatic.service.json
- packages/start/fixtures/serviceApp/plugin.js
- packages/start/fixtures/start-command.js
- packages/start/fixtures/starter.js
- packages/start/index.js
- packages/start/package.json
- packages/start/test/start.test.js
- pnpm-lock.yaml
This commit adds a `platformatic start` command for starting any supported type of Platformatic app. It also adds programmatic APIs for loading arbitrary types of configs, building servers, and starting them.
> feat: add platformatic start command

- docs/reference/start/programmatic.md
- packages/start/index.js
- packages/start/test/start.test.js
This commit does two things:
- Fixes a bug that prevented `buildServer()` from handling string inputs properly (indicating a config filename).
- Adds `getCurrentSchema()` to return the current schema for the provided application type. This makes it simpler to pass schemas to the `ConfigManager`. This makes testing more reliable, and saves an extra HTTP request in production (because the `ConfigManager` will attempt to download the schema).
> add more functionality to @platformatic/start

- packages/db/lib/schema.js
This might confuse users when autocomplete is on for config file
> Fixes typo in schemalock schema definition

- packages/client-cli/test/cli-graphql.test.mjs
- packages/client-cli/test/fixtures/auth/platformatic.db.json
- packages/client-cli/test/fixtures/movies-quotes/platformatic.db.json
- packages/client-cli/test/fixtures/movies/platformatic.db.json
- packages/service/index.js
- packages/service/test/watch.test.js
This fixes a regression we introduced from v0.23 onwards.
> Restore watch: true by default in service

- packages/service/index.js
- packages/service/package.json
- packages/service/test/fixtures/throw-resolver.js
- packages/service/test/graphql.test.js
- pnpm-lock.yaml
This is a test that is missing (throwing an error in a custom GraphQL resolver). 
If we had this, we would have spot [this problem in fastify-sandbox ](https://github.com/mcollina/fastify-sandbox/pull/29) earlier.
> Custom GraphQL resolver test and removed Error Handler to wrap errors from sandbox

- packages/create-platformatic/src/db/create-db-cli.mjs
Originally reported on Discord https://discord.com/channels/1011258196905689118/1027566961254744084/1113887746965119066.
> do not crash if platformatic is not in path when creating a platformatic db

- packages/create-platformatic/src/create-gitignore.mjs
I noticed this whitespace when a new platformatic project is created.
This commit remove the whitespace in gitignore generator.
> chore(create-platformatic): removed whitespace in gitignore generator

- packages/create-platformatic/src/cli-options.mjs
- packages/create-platformatic/src/composer/create-composer-cli.mjs
- packages/create-platformatic/src/db/create-db-cli.mjs
- packages/create-platformatic/src/runtime/create-runtime-cli.mjs
- packages/create-platformatic/src/service/create-service-cli.mjs
- packages/create-platformatic/test/cli-options.test.mjs
It is a chore PR to extract duplicated cli option into the single place for improving consistency and maintainability. Also, the configuration of cli option is covered by unit test to let someone know when the configuration is slightly changed.
> Move duplicated cli option in single place

- packages/config/test/helper.js
- packages/utils/test/file-watcher.test.js
When trying to get the tests running on Node 20, the way these modules use the temp directory in tests was causing problems. This commit refactors the temp directory logic.
> config,utils: refactor tmpdir access

- .github/workflows/ci.yml
The utils package was not being tested in the CI. It was helpful in figuring out some issues with Node 20, plus it should just be tested anyway.
> run utils tests in CI

- packages/composer/package.json
- pnpm-lock.yaml
The composer test suite was failing on Node 20. fastify@4.18.0 includes a fix (fastify #4810) that gets the composer test suite passing on Node 20.
> update fastify dependency in composer

- packages/utils/lib/file-watcher.js
Input validation in core is inconsistent, it was only supported on macOS and Windows prior to Node 20, and the recursive watch on Linux seems to have some bugs.
> only use recursive file watching on macOS and Windows

- packages/cli/cli.js
- packages/cli/test/start.test.js
- packages/runtime/fixtures/start-command-in-runtime.js
- packages/runtime/lib/config.js
- packages/runtime/lib/loader.mjs
- packages/runtime/lib/start.js
- packages/runtime/lib/unified-api.js
- packages/runtime/test/unified-api.test.js
- pnpm-lock.yaml
This PR updates `platformatic start` to run things within the runtime.
Unfortunately, the recent c8 update seems to have thrown off some coverage in the runtime's loader so there are some unrelated changes for that in this PR too.
> refactor platformatic start to launch apps via the runtime

- packages/client-cli/cli.mjs
On windows it fails with:
```bash
InvalidArgumentError: Invalid URL protocol: the URL must start with `http:` or `https:`.
at Object.parseURL (D:\a\platformatic\platformatic\node_modules\.pnpm\undici@5.22.1\node_modules\undici\lib\core\util.js:51:13)
at D:\a\platformatic\platformatic\node_modules\.pnpm\undici@5.22.1\node_modules\undici\index.js:78:18
at downloadAndProcess (file:///D:/a/platformatic/platformatic/packages/client-cli/cli.mjs:54:21)
at command (file:///D:/a/platformatic/platformatic/packages/client-cli/cli.mjs:164:11)
at file:///D:/a/platformatic/platformatic/packages/client-cli/cli.mjs:174:3
at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
code: 'UND_ERR_INVALID_ARG'
```
> fix: client-ci url parsing on windows

- packages/metaconfig/test/from-eighteen-to-will-see.test.js
- packages/metaconfig/versions/from-zero-eighteen-to-will-see.js
This property was removed in #1103.
Fixes: https://github.com/platformatic/platformatic/issues/1104
> metaconfig: remove hotReload from plugins object

- packages/utils/lib/file-watcher.js
This property is never used, so remove it.
> utils: remove unused fsWatcher property from FileWatcher

- docs/reference/client/introduction.md
- docs/reference/runtime/configuration.md
- packages/runtime/fixtures/configs/monorepo-client-without-id.json
- packages/runtime/fixtures/monorepo/serviceApp/platformatic.service-client-without-id.json
- packages/runtime/fixtures/monorepo/serviceApp/platformatic.service.json
- packages/runtime/lib/config.js
- packages/runtime/test/config.test.js
- packages/service/lib/schema.js
This commit allows clients to be given an explicit ID, similar to composer services. The runtime will automatically use this ID if present. Otherwise, the runtime will use its existing behavior.
Fixes: https://github.com/platformatic/platformatic/issues/1095
> support passing explicit client IDs in service clients

- packages/runtime/test/api.test.js
The `$schema` field changes with each release, so leave it out of the assertion.
> fix a runtime test

- packages/runtime/test/app.test.js
- packages/runtime/test/cli/validations.test.mjs
- One test had a leftover 'only' flag.
- One test recently started failing due to ANSI characters.
(FYI - we can use `stripVTControlCharacters()` from core instead of depending on an npm package that only supports ESM)
> fix two runtime test issues

- docs/reference/cli.md
- packages/runtime/lib/config.js
- packages/runtime/lib/start.js
- packages/runtime/lib/unified-api.js
- packages/runtime/lib/worker.js
- packages/runtime/test/cli/start.test.mjs
- packages/runtime/test/config.test.js
- pnpm-lock.yaml
Fixes: https://github.com/platformatic/platformatic/issues/835
Opening as a draft until we know if we want to do this and tests are added.
@mcollina please take a look (and possibly pull this down locally to try it out). It seems to work well enough. The two biggest hiccups are:
1. Printing the "Debugger listening" message twice - once on the main thread and a second time in the worker thread.
2. The debug port can currently be customized, but the host cannot.
> runtime: support node inspector flags

- packages/composer/lib/openapi-modifier.js
- packages/composer/test/cli/fetch-schema.test.js
- packages/composer/test/helper.js
- packages/composer/test/openapi/fields-renaming.test.js
- packages/composer/test/openapi/fixtures/schemas/users.json
Ideally, we should resolve schemas on our end, but for now, we can reuse `fastify-openapi-glue` schema resolving.
> fix: modify schema with resolved refs

- docs/reference/client/introduction.md
- packages/client-cli/cli.mjs
- packages/client-cli/lib/utils.mjs
- packages/client-cli/package.json
- packages/client-cli/test/cli-graphql-no-implementation.test.mjs
- packages/client-cli/test/cli-graphql.test.mjs
- packages/client-cli/test/cli-openapi-no-implementation.test.mjs
- packages/client-cli/test/cli-openapi.test.mjs
- packages/client-cli/test/helper.js
- packages/client-cli/test/runtime.test.mjs
- packages/service/fixtures/hello-client-ts-without-deps/hello.d.ts
- packages/service/fixtures/hello-client-ts-without-deps/hello.openapi.json
- packages/service/fixtures/hello-client-ts-without-deps/platformatic.service.json
- packages/service/fixtures/hello-client-ts-without-deps/plugin.ts
- packages/service/fixtures/hello-client-ts-without-deps/tsconfig.json
- packages/service/fixtures/hello-client-without-deps/hello.d.ts
- packages/service/fixtures/hello-client-without-deps/hello.openapi.json
- packages/service/fixtures/hello-client-without-deps/platformatic.service.json
- packages/service/fixtures/hello-client-without-deps/plugin.js
- packages/service/lib/plugins/clients.js
- packages/service/lib/schema.js
- packages/service/test/clients.test.js
- pnpm-lock.yaml
I noticed that we could save quite a bit of codegen and typescript issues by not generating the clients Fastify plugins at all.
> Do not generate clients when not needed

- packages/client-cli/lib/gen-openapi.mjs
- packages/client/index.js
- packages/client/test/openapi.test.js
Resolves #1019
Can set `throwOnError` option in the platform/client plugin which is passed down the undici request options.
> feat(#1019): support throwOnError option in platformatic/client

- packages/runtime/lib/message-port-writable.js
- packages/runtime/lib/start.js
- packages/runtime/lib/worker.js
- packages/runtime/test/start.test.js
This commit allows runtime applications to use a message port as a destination so that logs can be sent to another thread.
> runtime: support logging over message ports

- packages/runtime/lib/api-client.js
The API client is already an event emitter, so emit errors instead of throwing them. If there are no 'error' listeners, the error will still be thrown anyway.
> runtime: emit errors from API client

- packages/runtime/lib/worker.js
This will let us pick up fetch fixes more quickly and match the behavior of the cloud.
> runtime: set global fetch to be undici fetch

- packages/service/lib/schema.js
Fixes https://github.com/platformatic/platformatic/issues/1177
> Allow metrics.port to be a string

- packages/runtime/lib/api-client.js
- packages/runtime/lib/start.js
This commit does two things:
- Make the runtime worker available to embedders. This is done to listen for worker events without needing to proxy them all through the runtime API.
- Make the runtime only exit the process on error if there are no other error event listeners. This is done so that embedders can handle errors without the process terminating.
> runtime: make runtime worker accessible to embedders

- packages/runtime/package.json
Since dbd19c851d87db32548b3a8bfa057af93cc99e14, the linter fails due to the contents of the test/tmp directory. This commit ignores that directory for linting purposes.
> runtime: ignore test/tmp directory for linting

- docs/guides/migrating-express-app-to-platformatic-service.md
Add a new guide which shows how to migrate an Express application to Platformatic Service.
> docs: Guide: Migrating an Express app to Platformatic Service

- packages/runtime/lib/api-client.js
- packages/runtime/test/api.test.js
This commit uses `Promise.race()` to abort API client operations if the worker thread exits. Prior to this commit, the client could hang indefinitely while awaiting a response that would never come because the worker had already exited.
Fixes: https://github.com/platformatic/platformatic/issues/1191
> runtime: abort API operations if worker exits

- packages/runtime/fixtures/dbApp/platformatic.db.json
- packages/runtime/fixtures/dbApp/plugin.js
- packages/runtime/fixtures/start-command-in-runtime.js
- packages/runtime/test/start.test.js
Regression test for https://github.com/platformatic/platformatic/issues/1193
Opening as a draft because the test causes a segfault until #1193 is fixed.
> runtime: add regression test for db app crashes

- packages/runtime/lib/app.js
- packages/runtime/test/app.test.js
This commit updates the runtime config override logic to support missing config fields. Technically, there is already a test for this, but the behavior depends on whether or not the config manager populates a default value.
> runtime: allow overriding missing config keys

- packages/create-platformatic/src/index.mjs
Currently is: 
While should be: 
`Hello marcopiraccini, welcome to Platformatci 0.30.1!`
> The comma in the 'Hello' message should be after the username

- packages/client-cli/test/fixtures/movies/openapi.json
- packages/client-cli/test/fixtures/movies/plugin.js
- packages/client/index.js
- packages/client/test/fixtures/movies/openapi.json
- packages/client/test/fixtures/movies/plugin.js
- packages/client/test/openapi.test.js
The `generateOperationId()` function in the client package was not accounting for hyphens in URLs which meant that for:
```javascript
app.get('/hello-world', async (request, reply) => {
return { hello: 'world' }
})
```
You would get the following client method:
```javascript
client['getHello-world']()
```
And broken types:
```typescript
interface GetHello-worldRequest {
}
interface GetHello-worldResponseOK {
}
```
This fix will treat hyphens as slashes when determining case: `GET: /hello-world -> getHelloWorld`
> fix: generated operation IDs included dashes from URL

- packages/runtime/fixtures/dbAppWithMigrationError/migrations/001.do.sql
- packages/runtime/fixtures/dbAppWithMigrationError/migrations/001.undo.sql
- packages/runtime/fixtures/dbAppWithMigrationError/platformatic.db.json
- packages/runtime/fixtures/dbAppWithMigrationError/plugin.js
- packages/runtime/lib/message-port-writable.js
- packages/runtime/test/start.test.js
In some situations, such as when DB migrations fail during startup, the error logs were not being handled properly. According to the Node.js docs, custom writables such as `MessagePortWritable` need to implement one or both of `_write()` and `_writev()`. The runtime only implemented `_writev()`, and this seemed to be the cause of the missing logs. This commit adds `_write()`, and seems to resolve the missing logs issue.
Fixes: https://github.com/platformatic/dashformatic/issues/648
> runtime: add _write() to MessagePortWritable

- packages/runtime/lib/schema.js
Fix: #1277 
To control the hotReload property via environment variable string type is added.
> Runtime config hotReload: string type added

- docs/reference/runtime/configuration.md
- docs/reference/runtime/introduction.md
Fix: #1254 
The Interservice communication section is being moved from https://docs.platformatic.dev/docs/reference/runtime/configuration/ to https://docs.platformatic.dev/docs/reference/runtime/introduction/ for better access.
> Interservice communication doc section moved

- packages/composer/lib/openapi-composer.js
- packages/composer/test/openapi/schemas-composition.test.js
This PR is fixing https://github.com/platformatic/platformatic/issues/1299. The issue was that the openapi composer schema composition test, did not take into account namespace schema operation id's that are not pascal case. 
Currently namespaced schemas are composed using the operationID directly from `platformatic.composer.json`.  This had unexpected consequences when creating a frontend client. 
For example the composer service id:
`"id": "website-service"`
becomes
`export async function website-service_getPages(request) {...}`
When using the `api.js or api.ts` downloaded frontend code, type errors makes the file unusable due to the `hypen` in the function names.
The solution now generates an api prefix for the operationId using regex to remove undesired characters. For example:
1. …
> Fixing #1299 Composer: Namespace schema operation id's that are not pascal case

- .github/workflows/ci.yml
- packages/cli/cli.js
- packages/runtime/fixtures/configs/hotreload.json
- packages/runtime/fixtures/monorepo/serviceAppWithLogger/platformatic.service.json
- packages/runtime/fixtures/start-command-in-runtime.js
- packages/runtime/lib/api.js
- packages/runtime/lib/app.js
- packages/runtime/lib/start.js
- packages/runtime/lib/unified-api.js
- packages/runtime/package.json
- packages/runtime/runtime.mjs
- packages/runtime/test/app.test.js
- packages/runtime/test/cli/helper.mjs
- packages/runtime/test/cli/start.test.mjs
- packages/runtime/test/cli/watch.test.mjs
- packages/runtime/test/start.test.js
- packages/runtime/test/unified-api.test.js
- pnpm-lock.yaml
This fixes a few things:
* fast exit (not waiting 10s)
* watch gets disabled after the first change
* support running a single service with `platformatic runtime start`
> Fix hot reload with single service

- .github/workflows/ci.yml
They are often going in timeout for _no reason_
> Skip ci-composer tests for windows and node v20

- packages/db/config.d.ts
- packages/db/lib/schema.js
Updated graphql schema object to selectively ignore entity fields as per the [Platformatic reference configuration](https://docs.platformatic.dev/docs/reference/db/configuration) found under section `db` graphql.
Updated from only ignoring entities,
```
{
"db": {
...
"graphql": {
"ignore": {
"categories": true
}
}
}
}
```
to been able to selectively ignore entity fields as well.
```
{
"db": {
...
"graphql": {
"ignore": {
"categories": {
"name": true
}
}
}
}
}
```
Tests pass: 
Platformatic: 0.32.0
Nodejs: 18.16.1
> [DRAFT]: Updated graphql schema object to selectively ignore entity fields

- packages/db/config.d.ts
- packages/db/lib/schema.js
Updated openapi schema object to selectively ignore entity fields as per the [Platformatic reference configuration](https://docs.platformatic.dev/docs/reference/db/configuration) found under section `db` openapi.
Updated from only ignoring entities,
```
{
"db": {
...
"openapi": {
"ignore": {
"categories": true
}
}
}
}
```
to been able to selectively ignore entity  fields as well.
```
{
"db": {
...
"openapi": {
"ignore": {
"categories": {
"name": true
}
}
}
}
}
```
Tests pass: 
Platformatic: 0.32.0
Nodejs: 18.16.1
> fixes #1309 Updated openapi schema object to selectively ignore entity fields

- packages/composer/lib/openapi-generator.js
- packages/composer/test/openapi/routes-composition.test.js
it does the same parsing for the composer.
https://github.com/platformatic/platformatic/blob/0f89c0d91d019bb29265155bb56c4d6d755f50ce/packages/sql-openapi/lib/entity-to-routes.js#L60
Fix #1310
> fix: parse querystring fields param

- packages/frontend-template/lib/gen-openapi.mjs
- packages/frontend-template/package.json
- packages/frontend-template/test/fixtures/sample/.gitignore
- packages/frontend-template/test/fixtures/sample/platformatic.db.json
- packages/frontend-template/test/fixtures/sample/plugin.cjs
- packages/frontend-template/test/openapi.test.js
- pnpm-lock.yaml
To check it
- Create a new platformatic service with `create-platformatic`
- Add a route like this
```js
fastify.get('/redirect', {
schema: {
response: {
302: {
type: 'object',
properties: {}
},
400: {
type: 'object',
properties: {
message: { type: 'string' }
}
}
}
}
}, 
async (request, reply) => {
return reply.code(302).redirect('https://google.com')
})
```
- Start the application with `npm start`
- Generate frontend boilerplate files with `platformatic frontend http://127.0.0.1:3042 ts`
File `api-types.d.ts` would include this code
```ts
interface FullResponse<T> {
'statusCode': number;
'headers': object;
'body': T;
}
...
interface GetRedirectRequest {
}
interface GetRedirectResponseFound {
}
interface GetRedirectResponseBadRequest {
'message': string;
}
export interface Api { …
```
> Update type definitions and implementation to support multiple responses

- packages/client/test/telemetry.test.js
- packages/composer/test/telemetry/proxy.test.js
- packages/composer/test/telemetry/routes-composition-telemetry.test.js
- packages/db/test/telemetry.test.js
- packages/service/test/telemetry.test.js
- packages/telemetry/lib/telemetry.js
- packages/telemetry/package.json
- packages/telemetry/test/client.test.js
- packages/telemetry/test/telemetry.test.js
- pnpm-lock.yaml
Two telemetry fixes here:
- Set the correct `SpanType` for client and server.
- Set the correct standard required attributes, following the [Semantic conventions for HTTP spans](https://opentelemetry.io/docs/specs/otel/trace/semantic_conventions/http/#http-client)
> Correct telemetry span types and Semantic HTTP attributes

- docs/guides/securing-platformatic-db.md
Fix the link to point the reference documentation for [Authorization Introduction](https://docs.platformatic.dev/docs/reference/db/authorization/introduction).
> fixes #1354: Page not found authorization

- packages/client-cli/lib/gen-graphql.mjs
- packages/client-cli/lib/gen-openapi.mjs
- packages/client-cli/test/cli-graphql-no-implementation.test.mjs
- packages/client-cli/test/cli-openapi-no-implementation.test.mjs
So that, as mentioned on [ts website](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html):
> `import type` only imports declarations to be used for type annotations and declarations. It always gets fully erased, so there’s no remnant of it at runtime. Similarly, `export type` only provides an export that can be used for type contexts, and is also erased from TypeScript’s output.
and to avoid issues, f.e. when using `elint` plugins, like:
```
All imports in the declaration are only used as types. Use `import type`.eslint[@typescript-eslint/consistent-type-imports](https://typescript-eslint.io/rules/consistent-type-imports)
```
> feat(client-cli): Import as type

- docs/reference/composer/configuration.md
- docs/reference/db/configuration.md
- docs/reference/runtime/configuration.md
- docs/reference/service/configuration.md
- packages/composer/test/telemetry/proxy.test.js
- packages/composer/test/telemetry/routes-composition-telemetry.test.js
- packages/telemetry/lib/schema.js
- packages/telemetry/lib/telemetry.js
- packages/telemetry/test/client.test.js
- packages/telemetry/test/telemetry.test.js
Added the new config `skip` property: 
```
serviceName: 'test-service',
skip: ['POST/skipme'],
exporter: {
type: 'memory'
}
```
This is useful to skip calls that are not intereseting on traces (like ` GET/documentation/json` from the composer and health checks).
Also some other minor fixes:
- Added some missing guards
-  Avoid to put querystring on `url.path` in spans.
> Configurable skip for tracing

- docs/reference/composer/configuration.md
- docs/reference/db/configuration.md
- docs/reference/runtime/configuration.md
- docs/reference/service/configuration.md
- packages/client/test/telemetry.test.js
- packages/composer/test/telemetry/proxy.test.js
- packages/composer/test/telemetry/routes-composition-telemetry.test.js
- packages/db/test/telemetry.test.js
- packages/service/test/telemetry.test.js
- packages/telemetry/lib/platformatic-trace-provider.js
- packages/telemetry/lib/schema.js
- packages/telemetry/lib/telemetry.js
- packages/telemetry/test/client.test.js
- packages/telemetry/test/telemetry.test.js
With this  PR, `exporter` can also be an array, so multiple exporters can be setup for telemetry.
> Telemetry: multiple exporters support

- packages/client-cli/lib/gen-openapi.mjs
- packages/client/index.d.ts
- packages/client/index.js
- packages/client/test/generateOperationId.test.js
- packages/client/test/openapi.test.js
- packages/frontend-template/index.js
- packages/frontend-template/lib/gen-openapi.mjs
- pnpm-lock.yaml
Instead of having a progressive number I used the method name before the operation Id.
One of our test was failing , and after the fix with progressive number, I had to change the test to
```
client.updateMovies1(...)
``` 
Which didn't look good to me.
There is still an edge case
```json
{
"openapi": "3.0.3",
"paths": {
"/sample-path": {
"get": {
"operationId": "sampleOperationId"
}
},
"/sample-path2": {
"get": {
"operationId": "sampleOperationId"
}
}
}
}
```
Same operationId, same method (but different path). 
I think it's very uncommon, should we support also this? 
Maybe using this [code](https://github.com/platformatic/platformatic/blob/1396-duplicated-exports/packages/client/index.js#L13-L19) we already have? 
Fixes: #1396
> Generate unique operation id

- packages/client-cli/lib/gen-openapi.mjs
- packages/client-cli/test/cli-openapi-no-implementation.test.mjs
When generating types, this helps in case you want to select a specific request or response typ
> feat(client-cli): export interfaces

- packages/client-cli/lib/gen-openapi.mjs
- packages/client-cli/test/get-type.test.mjs
Fix the following issue, in case you have an enum containing the single quote char `'`
> fix(client-cli): Enum with single quote

- docs/reference/cli.md
- packages/client-cli/cli.mjs
- packages/client-cli/help/help.txt
- packages/client-cli/lib/gen-openapi.mjs
- packages/client-cli/test/cli-openapi-no-implementation.test.mjs
- packages/client-cli/test/cli-openapi.test.mjs
- packages/client-cli/test/fixtures/full-req-res/openapi.json
- packages/client-cli/test/fixtures/full-req-res/package.json
- packages/client-cli/test/fixtures/full-req-res/platformatic.service.json
- packages/client-cli/test/fixtures/full-req-res/plugins/example.js
- packages/client-cli/test/fixtures/same-parameter-name-openapi.json
- packages/client/index.d.ts
- packages/client/index.js
- packages/client/test/fixtures/array-query-params/openapi.json
- packages/client/test/fixtures/array-query-params/package.json
- packages/client/test/fixtures/array-query-params/platformatic.service.json
- packages/client/test/fixtures/array-query-params/plugins/example.js
- packages/client/test/fixtures/duped-params/openapi.json
- packages/client/test/fixtures/duped-params/package.json
- packages/client/test/fixtures/duped-params/platformatic.service.json
- packages/client/test/fixtures/duped-params/plugins/example.js
- packages/client/test/fixtures/no-params/openapi.json
- packages/client/test/fixtures/no-params/package.json
- packages/client/test/fixtures/no-params/platformatic.service.json
- packages/client/test/fixtures/no-params/plugins/example.js
- packages/client/test/openapi.test.js
Example:
```typescript
export interface GetRequest {
body: {
'id': string;
}
query: {
'id': string;
}
headers: {
'id': string;
}
}
```
Draft because I'm pretty sure some cases are not covered
cc @rozzilla 
Fixes: #1435
> improve request type definition

- packages/db/lib/migrator.mjs
Adds a warning if no migration file is found in the `migrations` dir. A message would be helpful for someone who's not familiar.
Related to #1464.
> Adds warning if no migration file found

- packages/sql-mapper/lib/entity.js
- packages/sql-mapper/test/updateMany.test.js
- packages/sql-mapper/test/where.test.js
When querying for an unknown field inside the mapper an error like this get thrown: `TypeError: Cannot read properties of undefined (reading 'isArray')`
Check the existance of the field before computing criteria.
> fix: better error when querying an unknown field

- packages/client/index.js
- packages/client/test/fixtures/array-query-params/openapi.json
- packages/client/test/fixtures/array-query-params/plugins/example.js
- packages/client/test/openapi.test.js
The goal of this PR is to fix the way we pass an array `querystring`:
* fix [this](https://github.com/platformatic/platformatic/blob/main/packages/client/test/fixtures/array-query-params/openapi.json) OpenAPI definition, since it was invalid
* fix [this](https://github.com/platformatic/platformatic/blob/main/packages/client/index.js#L127) code and check `param.schema.type` instead of `param.type`
* consider the case when a `querystring` is defined as a union of `string | string[]` (since for most of the query parser, passing 1 element is considered as a `string`, while multiple ones as `string[]`
> fix(client): Properly pass array `querystring`

- packages/client-cli/lib/gen-openapi.mjs
- packages/client-cli/test/cli-openapi.test.mjs
- packages/client-cli/test/fixtures/same-parameter-name-openapi.json
As by title, `path` is currently not generated on types when `--full` option is specified.
> fix(client-cli): Generate path types on full-request

- packages/client/index.d.ts
- packages/client/index.test-d.ts
As by title, this PR adds the `validateResponse` to the type definition of the client.
> fix(client): Add validateResponse param

- packages/runtime/lib/api.js
Ref https://github.com/fastify/fastify-swagger/pull/757
> Always call .ready() before calling .swagger()

- Dockerfile
This PR tries to make the `Dockerfile` _slightly_ more secure by preventing the running user from changing sources (by not `chown`ing files `node:node` in the first place.
> feat(docker): secure `Dockerfile`

- packages/create-platformatic/src/composer/create-composer-cli.mjs
- packages/create-platformatic/src/db/create-db-cli.mjs
- packages/create-platformatic/src/db/create-db.mjs
- packages/create-platformatic/src/runtime/create-runtime.mjs
- packages/create-platformatic/src/service/create-service-cli.mjs
- packages/create-platformatic/src/service/create-service.mjs
- packages/service/index.js
- packages/service/lib/schema.js
- packages/service/lib/start.js
- packages/service/test/cli/gen-schema.test.mjs
- packages/service/test/cli/validations.test.mjs
- packages/service/test/config.test.js
- packages/utils/lib/is-key-enabled.js
- packages/utils/test/is-key-enabled.test.js
Opening early to check CI, since this PR may affect other packages.
This PR aims to remove the `server` block from the services inside the runtime. 
It will keep it for the service entrypoint, though.
It also manages services `.env` files: it will copy the contents into the main `.env` file, purging the `PORT`, `PLT_LOGGER_LEVEL` and `PLT_SERVER_HOSTNAME` if the service is _not_ the entrypoint.
This will probably affect #1424 
Fixes: #1372
Fixes: https://github.com/platformatic/platformatic/issues/1575
> Make server config not required in runtime

- packages/sql-mapper/mapper.d.ts
- packages/sql-mapper/test/types/mapper.test-d.ts
I have also made `fields` and `where` options on delete hook optional, I believe they are not required. let me know if I should revert it.
Example usecase:
```ts
/// <reference path="./global.d.ts" />
import { FastifyInstance } from "fastify";
export default async function (app: FastifyInstance) {
app.platformatic.addEntityHooks("entity", {
save: async (originalSave, opts) => {
return app.platformatic.db.tx(async (tx) => {
// Do other things atomically
return originalSave({
...opts,
tx,
});
});
},
});
}
```
> fix(sql-mapper): add types for tx option on all entity hooks

- packages/create-platformatic/src/db/create-db-cli.mjs
Removes the default boolean cli options value which was `true` because, since they are flags, there is no way to "deactivate" them.
Fixes: #1600 
Fixes: #1230
> Remove default true value to boolean args

- docs/reference/runtime/configuration.md
- docs/reference/service/configuration.md
- packages/runtime/fixtures/server/overrides-service/platformatic.runtime.json
- packages/runtime/fixtures/server/overrides-service/services/echo/platformatic.service.json
- packages/runtime/fixtures/server/overrides-service/services/echo/routes/span.js
- packages/runtime/fixtures/server/runtime-server/platformatic.runtime.json
- packages/runtime/fixtures/server/runtime-server/services/echo/platformatic.service.json
- packages/runtime/fixtures/server/runtime-server/services/echo/routes/span.js
- packages/runtime/lib/api.js
- packages/runtime/lib/app.js
- packages/runtime/lib/schema.js
- packages/runtime/test/app.test.js
- packages/runtime/test/cli/server.test.mjs
If a `server` is defined on runtime, it's used for the entrypoint `server`  (and in case, overrides the `server` config)
Fixes: https://github.com/platformatic/platformatic/issues/1611
> uses global runtime server for entrypoint if defined

- packages/client-cli/lib/openapi-common.mjs
- packages/client-cli/test/cli-openapi.test.mjs
The result of this PR is that if a block (like `headers`) has all optional parameters, the entire block will be optional (f.e. it will not be required to pass an empty object to make TypeScript compile).
> fix(client-cli): Make TS block optional when all params are optional

- packages/client-cli/cli.mjs
The `full-response` argument was given twice in the `minimist` arg parser and the `full-request` arg was not given. I've corrected it.
There was also another typo with the `language` argument.
> Fixed a couple of typos in the client-cli package

- packages/sql-graphql/lib/entity-to-type.js
- packages/sql-graphql/test/enum.test.js
fixes(#1641) Bug where enums could not be parsed when generating graphql schema.
> fixes(#1641) sql-graphql enum values may contain spaces

- packages/create-platformatic/package.json
- packages/create-platformatic/src/db/create-db-cli.mjs
- packages/create-platformatic/src/db/create-db.mjs
- packages/create-platformatic/test/cli/db.mjs
- packages/create-platformatic/test/cli/db.test.mjs
- packages/create-platformatic/test/cli/helper.mjs
- pnpm-lock.yaml
This is for unit tests for DB services created by `create-platformatic` (currently the "interactive" part of the  CLI is NOT tested).
This can be leveraged also for future integration tests.
If this is OK, we will do the same for Service, Runtime, Composer
> create-platformatic CLI unit tests for DB services

- docs/reference/sql-mapper/introduction.md
- packages/db/config.d.ts
- packages/db/lib/schema.js
- packages/service/config.d.ts
- packages/sql-mapper/lib/cache.js
- packages/sql-mapper/mapper.d.ts
- packages/sql-mapper/mapper.js
- packages/sql-mapper/package.json
- packages/sql-mapper/test/cache.test.js
- packages/sql-mapper/test/helper.js
- packages/sql-mapper/test/types/mapper.test-d.ts
- pnpm-lock.yaml
Following https://github.com/platformatic/platformatic/pull/1614
> This adds `async-cache-dedupe` to Platformatic DB so that queries can be deduplicated before sending them down, saving quite a bit of DB latency. On my local tests, enabling it gives around 6x more throughput (with just deduping).
> 
> Todo:
> 
> * [x]  Add cache to sql-mapper
> * [ ] ~~Add tests for redis~~
> * [x]  Add options in the schema of Platformatic DB
The target is to add `dedupe` feature at first,  I'll open a new issues with the tasks to add the full cache support
> Add dedupe cache

- docs/reference/db/configuration.md
- docs/reference/service/configuration.md
Update documentation to include `enabled` option for `graphql`, `openapi` and `events. Also add documentation for `autoload` options.
Resolves #1695
> Update reference configuration docs

- packages/sql-mapper/lib/entity.js
- packages/sql-mapper/lib/utils.js
A utility function to convert the first char of a string to lower case was defined in `/lib/entity.js` of the `sql-mapper` package, while a similar function to convert the first char to upper case was defined in `/lib/utils.js`. I've moved the first function to the `utils` file too and made its name consistent with the other function.
Also, the function to convert the first char to upper case was not converting its input to a string before performing a string operation. I've fixed that too.
In short, I moved both functions to the same place (`/lib/utils.js`) and made them consistent.
> Moved a utility function to lib/utils.js in sql-mapper and also made it consistent with another similar function

- packages/sql-graphql/lib/telemetry.js
- packages/sql-graphql/test/telemetry.test.js
This to avoid to wrap all the schema type with name starting with `__`  like `__schema`, `__type`, `__field` (which is useless).
> skip the schema type starting with __

- packages/create-platformatic/src/composer/create-composer-cli.mjs
- packages/create-platformatic/src/create-package-json.mjs
- packages/create-platformatic/src/db/create-db-cli.mjs
- packages/create-platformatic/src/index.mjs
- packages/create-platformatic/src/runtime/create-runtime-cli.mjs
- packages/create-platformatic/src/runtime/create-runtime.mjs
- packages/create-platformatic/src/service/create-service-cli.mjs
- packages/create-platformatic/src/utils.mjs
- packages/create-platformatic/test/create-package-json.test.mjs
- packages/create-platformatic/test/utils.test.mjs
Main changes
- all `createXXX` function will return an object `{ typescript: true | false }` 
- `createPackagejson()` will accept a `devDependencies` parameter
- `getDependencyVersion` will find where exactly the dep `package.json` file is located 
Fixes: #1752
> Add typescript dependency on runtime

- packages/client-cli/cli.mjs
- packages/client-cli/test/runtime.test.mjs
This PR is needed because the `platformatic.runtime.json` file would me modified adding a `clients: [ ... ]` property which fails the schema validation
> Avoid creating a client from a runtime root

- packages/client-cli/lib/frontend-openapi-generator.mjs
- packages/client-cli/test/fixtures/append-query-params-frontend.openapi.json
- packages/client-cli/test/frontend-openapi.test.mjs
This is sample of the new generated code
```js
const _appControllerGetHello = async (url: string, request: Types.AppControllerGetHelloRequest) => {
const queryParameters = ['level']
const searchParams = new URLSearchParams()
queryParameters.forEach((qp) =>{
searchParams.append(qp, request[qp])
delete request[qp]
})
const response = await fetch(`${url}/${searchParams.toString()}`, {
method: 'POST',
body: JSON.stringify(request),
headers: {
'Content-type': 'application/json'
}
})
if (!response.ok) {
throw new Error(await response.text())
}
return await response.json()
}
```
Fixes: #1748
> Appends query params to non-GET requests in frontend client generation

- packages/service/lib/plugins/openapi.js
- packages/service/lib/schema.js
- packages/service/test/fixtures/openapi-spec-test.json
- packages/service/test/openapi.test.js
I think this is a missing feature in Platformatic and can be useful.
Before this all routes should have a `schema` object (which btw provides serialization and validation out of the box though)
With this new feature the with a config like this
```json
{
"service": {
"openapi": {
"file": "./path/to/openapi.json"
}
}
}
```
swagger plugin is loaded and read the spec from that file using the simplest [static](https://github.com/fastify/fastify-swagger#static) configuration option of the plugin
> Read OpenAPI spec from file

- packages/composer/lib/fetch-schemas.mjs
- packages/composer/test/cli/fetch-schema.test.js
- packages/composer/test/openapi/fixtures/schemas/users.json
- packages/composer/test/runner.js
Changed the `fetchOpenApiSchemas` function in `packages/composer/lib/fetch-schemas.mjs` so that the composer CLI does not exit if it fails to fetch even a single schema.
Also, added success/error logs for fetching schema for every OpenAPI service.
Note: there were no tests for `fetchOpenApiSchemas`, so I have not changed any tests after making the above changes.
> Changes to prevent the composer process from exiting if it fails to fetch any OpenAPI schemas

- packages/create-platformatic/src/db/create-db.mjs
- packages/create-platformatic/src/service/create-service.mjs
This was a leftover, when we changed the behavior to overwrite existing files/dirs.
Fixes: #1797
> Removes useless output on .env file

- packages/utils/package.json
- packages/utils/test/create-server-config.test.js
- packages/utils/test/deepmerge.test.js
- packages/utils/test/file-watcher.test.js
- packages/utils/test/find-nearest-string.test.js
- packages/utils/test/is-file-accessible.test.js
- packages/utils/test/is-key-enabled.test.js
- packages/utils/test/packages.test.js
- pnpm-lock.yaml
This PR follows the #1796 by migrating from `tap` to `node:test`.
> refactor(test): remove tap from utils tests

- packages/telemetry/package.json
- packages/telemetry/test/client.test.js
- packages/telemetry/test/internal.test.js
- packages/telemetry/test/multispan-processor.test.js
- packages/telemetry/test/platformatic-trace-provider.test.js
- packages/telemetry/test/telemetry.test.js
- pnpm-lock.yaml
This PR follows the https://github.com/platformatic/platformatic/issues/1796 by migrating tests from `tap` to `node:test`.
> refactor(test): remove tap from telemetry tests

- packages/metaconfig/package.json
- packages/metaconfig/test/0.16.0.test.js
- packages/metaconfig/test/0.17.0.test.js
- packages/metaconfig/test/0.18.0.test.js
- packages/metaconfig/test/0.19.0.test.js
- packages/metaconfig/test/0.20.0.test.js
- packages/metaconfig/test/1.x.x.test.js
- packages/metaconfig/test/base.test.js
- packages/metaconfig/test/from-eighteen-to-will-see.test.js
- pnpm-lock.yaml
This PR follows the https://github.com/platformatic/platformatic/issues/1796 by migrating tests from `tap` to `node:test`.
> refactor(test): remove tap from metaconfig tests

- packages/db/snapshots/test/cli/schema2.test.mjs
- packages/sql-openapi/index.js
- packages/sql-openapi/lib/entity-to-routes.js
- packages/sql-openapi/lib/many-to-many.js
- packages/sql-openapi/lib/shared.js
- packages/sql-openapi/lib/utils.js
- packages/sql-openapi/test/schema-override.test.js
- packages/sql-openapi/test/tap-snapshots/array-openapi-1.cjs
- packages/sql-openapi/test/tap-snapshots/nested-routes-openapi-recursive.cjs
- packages/sql-openapi/test/tap-snapshots/nested-routes-openapi.cjs
- packages/sql-openapi/test/tap-snapshots/orderby-openapi-1.cjs
- packages/sql-openapi/test/tap-snapshots/simple-openapi-1.cjs
- packages/sql-openapi/test/tap-snapshots/simple-openapi-2.cjs
- packages/sql-openapi/test/tap-snapshots/simple-openapi-3.cjs
- packages/sql-openapi/test/tap-snapshots/simple-openapi-4.cjs
- packages/sql-openapi/test/tap-snapshots/updateMany-openapi-1.cjs
- packages/sql-openapi/test/tap-snapshots/where-openapi-1.cjs
- packages/sql-openapi/test/tap-snapshots/where-openapi-2.cjs
- packages/sql-openapi/test/tap-snapshots/where-openapi-3.cjs
Fixes #1774 
The schema for `platformatic.db.json` config file already provides the property `db.openapi.paths` that can be used to override path summaries or descriptions. These are in accordance with the OpenAPI 3 specs.
Here is a summary of the changes:
1. For every route, the `sql-openapi` package will check for and apply any schema overrides for that route. The properties provided at the method level will override those at the path level, in case both are provided.
2. Added `schema-override.test.js` to test the above functionality.
3. Added default `summary` and `description` to each route.
4. Updated test snapshots: added default summaries and descriptions.
To add a custom summary or description, the following configuration can be used in the `platformatic.db` config file:
```
{
... …
```
> Changes to allow provision of custom summaries and descriptions for each route, plus addition of default summaries and descriptions.

- packages/client-cli/cli.mjs
- packages/create-platformatic/src/db/create-db-cli.mjs
- packages/create-platformatic/test/cli/db.test.mjs
- packages/db/lib/gen-types.mjs
- packages/db/test/cli/gen-types.test.mjs
After some work on this issue, the Occam's Razor is to **not** generate types if no schema is found.
Fixes: #1798
> Do not generate types if no schema is found

- packages/client/index.d.ts
- packages/client/index.test-d.ts
Probably related to this [issue](https://github.com/platformatic/platformatic/issues/1820).
In any case, `openTelemetry` param should not be mandatory to be passed, considering how it's used for example [here](https://github.com/platformatic/platformatic/blob/main/packages/client/index.js#L193). In any case, in the entire [client](https://github.com/platformatic/platformatic/blob/main/packages/client/index.js), it's always called with the question mark, so it can be `undefined` 😉
> fix(#1820): openTelemetry param should be optional

- docs/reference/client/programmatic.md
- packages/client/index.d.ts
- packages/client/index.js
- packages/client/index.test-d.ts
- packages/client/test/openapi.test.js
Hello! 👋🏼 
While using `@platformatic/client` and its `buildOpenAPIClient`, I realised `getHeaders` is not being passed down (nor there was the chance to do so). Since `buildCallFunction` already makes use of it, it would be fantastic if that could be passed down so that headers can be injected in the request if needed. We have this use case where we'd like to call this function to build dynamic headers (like signature headers), without having to inject them, before calling platformatic client methods.
The functionality would remain the same as in the plugin (excluding the `request` and `reply` objects). This PR makes sure:
- The `getHeaders` function is received by `buildOpenAPIClient` and gets added to `client`
- There is a test to prove the function gets called upon request
- There is …
> feat(client): Allow getHeaders to be called when using buildOpenAPIClient

- packages/client-cli/lib/frontend-openapi-generator.mjs
- packages/client-cli/test/fixtures/get-headers-frontend-openapi.json
- packages/client-cli/test/frontend-openapi.test.mjs
#1821 solved the header problem when running `platformatic client <url> --frontend` for all http methods except for get, so this is the fix.
> handle headers for get requests too

- packages/client/index.js
The @platformatic/client tests are currently failing as they assert that the body of a 204 response should be `undefined`, yet it is actually `null` as the client returns the value of `res.body.dump()` (looks like undici changed to returning null in 5.28.0 with [perf: optimize Readable.dump](https://github.com/nodejs/undici/pull/2402)).
> fix: client body on 204 is null not undefined

- packages/client/index.js
- packages/client/test/fixtures/no-bodies/openapi.json
- packages/client/test/fixtures/no-bodies/package.json
- packages/client/test/fixtures/no-bodies/platformatic.service.json
- packages/client/test/fixtures/no-bodies/plugins/example.js
- packages/client/test/openapi.test.js
Fixes #1878
My original approach was to not send content for methods which did not have request bodies defined in their openAPI specs, but the default @platformatic/client functionality is to send all unmapped params in the request body. Instead I've decided to not send a body where the method SHOULD NOT or MUST NOT have one according to [RFC 9110](https://www.rfc-editor.org/rfc/rfc9110).
Hope this is ok!
Ta
> fix(#1878): only POST, PUT, PATCH & OPTIONS can send bodies from client

- packages/client/index.js
- packages/client/test/openapi.test.js
Fix: #1881
Ensure response validation applies whether `fullResponse` is enabled or not.
> fix(#1881): @platformatic/client doesn't validate in fullResponse mode

- packages/generators/lib/base-generator.d.ts
- packages/generators/lib/base-generator.js
- packages/generators/lib/utils.d.ts
- packages/generators/lib/utils.js
- packages/generators/test/base-generator.test.js
If the `path` type is specified for value `xxx`, the generator creates a configuration with `{PLT_ROOT}/xxx` 
Fixes: https://github.com/platformatic/platformatic/issues/1895
Note that the `relativePath` has been renamed `path`. The path is always relative now, if we want to add the possibility of setting an absloute path in generator, we need a new type.
> Generator support for relative paths 

- packages/client-cli/lib/openapi-common.mjs
- packages/client-cli/test/fixtures/sample/plugin.cjs
- packages/client-cli/test/frontend-openapi.test.mjs
- packages/client/index.js
With this change, when an Open API schema contains a `nullable: true` property, it's properly handled and the generated type will contain ` | null;`
> fix(client-cli): Properly interpret nullable prop

- packages/client-cli/lib/openapi-common.mjs
- packages/client-cli/test/fixtures/sample/plugin.cjs
- packages/client-cli/test/frontend-openapi.test.mjs
- packages/client/index.js
This PR adds support for a `string` type when the format is `date` or `date-time` ([OpenAPI reference](https://swagger.io/docs/specification/data-models/data-types/#string%C2%A7)).
Additionally, it does a small refactor of `JSONSchemaToTsType` to make it more reusable.
> fix(client-cli): Support string date-time

- docs/guides/migrating-fastify-app-to-platformatic-service.md
> 
Hello,
While I was reading the Fastify migration guide, I found a small mistake. The directory that should contain the testing code is sometimes referred to as "tests" and at other times as "test".
So, I renamed all occurrences of the "test "tests" directory to "tests" "test".
Related to this pull request: https://github.com/platformatic/docs/pull/102
> Rename the tests directory to 'test' in Fastify migration guide

- packages/client-cli/lib/openapi-common.mjs
- packages/client-cli/test/fixtures/sample/plugin.cjs
- packages/client-cli/test/frontend-openapi.test.mjs
The request object values are stringified before being sent, so it's completely fine to generate a `Date` type, if needed, inside the `Request` object.
The same behaviour is misleading for the `Response`: considering that a JSON response is always a `string`, and can't be a "real" `Date`, even though it's contained inside it, you should always convert it to a real `Date` object.
This PR handle this scenario.
> fix(client-cli): Date only for request

- packages/create-platformatic/src/service/README.md
When creating a new platformatic service with the `create platformatic@latest` command, the link in the readme to the generated `documentation` site fails to load:
Before:
It took me a little while to realize this was because of the trailing slash on the URL in the readme:
After:
Hopefully this helps others trying platformatic for the first time like myself!
> fix: service-readme-documentation-url

- packages/sql-graphql/lib/utils.js
- packages/sql-graphql/test/datatypes.test.js
I have also changed `time` to `scalars.GraphQLTime`. I feel like that is the correct type unless it was intentional.
> fix(sql-graphql): define correct graphql types for timetz/timestamptz

- packages/client/index.d.ts
- packages/client/index.js
- packages/client/index.test-d.ts
- packages/client/test/openapi.test.js
Similarly to `fastify`, where we can pass an optional `querystringParser`, this PR introduces support for an optional query parser when calling the `client`
> feat(client): Add optional query parser

- docs/reference/db/introduction.md
Update 'core' link for 'connectionString' config reference to point to 'db', and not 'core' for better documentation.
Fixes #2060
> Update 'core' link for 'connectionString' config reference

- packages/client-cli/lib/openapi-common.mjs
- packages/client-cli/lib/openapi-generator.mjs
- packages/client/index.js
- packages/sql-openapi/lib/shared.js
At the moment the `where.or` clause in a generated client for a db app supports the following format
```js
const output = await req.dbtest.getMovies({
"where.or": ['(id.eq=1|title.eq=Matrix)']
})
```
With this PR a better type is created for such clause and you can use this
```js
const output = await req.dbtest.getMovies({
"where.or": [
{ id: { eq: 2 } }, 
{ title: { eq: 'Matrix' } }
]
})
```
This will also enable suggestion from the editor based on the entity fields
Fixes: #1806
> Suuport complex object in where.or clause

- packages/client-cli/lib/responses-writer.mjs
- packages/client-cli/test/frontend-openapi.test.mjs
In case of a non-defined response in an OpenAPI schema, we previously returned something like this:
```
get(req?: GetRequest): Promise<GetResponses>;
type GetResponses = FullResponse<GetResponseOK, 200>;
```
while we now return:
```
get(req?: GetRequest): Promise<unknown>;
```
This PR makes the type backwards compatible, by returning a `FullResponse` of `unknown` type in case of missing response schema, so:
```
get(req?: GetRequest): Promise<FullResponse<unknown, 200>>;
```
> fix(client-cli): Make type generation backward compatible

- packages/runtime/package.json
ts compilation tests on windows nodejs 18.19 takes a lot of time
> test: increase runtime test timeout

- packages/client-cli/package.json
Small investigation shows that just windows ci is slow.
> test: increase client-cli test timeout

- packages/client-cli/lib/openapi-generator.mjs
- packages/client-cli/test/cli-openapi-no-implementation.test.mjs
- packages/client-cli/test/cli-openapi.test.mjs
The rationale of this switch:
* Allows the creation of aliases for complex types
* Supports union types and intersection types directly
> feat(client-cli): Export main definition as type

- packages/client-cli/lib/responses-writer.mjs
- packages/client-cli/lib/utils.mjs
- packages/client-cli/test/cli-openapi.test.mjs
- packages/client-cli/test/frontend-openapi.test.mjs
- packages/client-cli/test/utils.test.mjs
> Support empty responses with types

- packages/client/index.d.ts
- packages/client/index.test-d.ts
Extremely useful to better narrow down the types to the proper status code (f.e. in [this case](https://github.com/platformatic/platformatic/issues/2213))
> chore(client): Add status code types

- packages/generators/index.test-d.ts
- packages/generators/lib/base-generator.d.ts
- packages/generators/package.json
- pnpm-lock.yaml
The only value `configValue` can have is `string` in typescript, which appears to be incorrect (using code from platformatic db's generator added in the same pr as this property for reference https://github.com/platformatic/platformatic/pull/1846/files#diff-5f2c6dbe9a4fd864242b3a0bcd3a30f6877d36729bdfa61c4a971a9d6c6a2f1dR205)
cc @mcollina @leorossi
> Fix typing of configValue in config fields

- packages/client-cli/lib/openapi-generator.mjs
Fixes: https://github.com/platformatic/platformatic/issues/2256
> Correct type for getHeaders 

- packages/service/fixtures/hello-client-from-plugin/hello.d.ts
- packages/service/fixtures/hello-client-from-plugin/hello.openapi.json
- packages/service/fixtures/hello-client-from-plugin/platformatic.service.json
- packages/service/fixtures/hello-client-from-plugin/plugin.js
- packages/service/index.js
- packages/service/test/clients.test.js
Fixes: https://github.com/platformatic/platformatic/issues/2254
> Register clients before plugins

- docs/reference/client/introduction.md
- packages/client-cli/cli.mjs
- packages/client-cli/test/cli-openapi-no-implementation.test.mjs
- packages/client-cli/test/cli-openapi.test.mjs
Closes https://github.com/platformatic/platformatic/issues/2251
> Don't set `options.folder` when `--types-only`

- packages/generators/lib/create-stackable-cli.js
- packages/generators/lib/create-stackable-files.js
- packages/generators/lib/create-stackable-plugin.js
Fixes a few linting errors that are found in the generated typescript files when using `ts-standard` (`standard` but for typescript)
> Fix linting issues from generated .ts stackable files

- packages/client/index.js
- packages/client/test/openapi.2.test.js
avoid the client throwing when `args.query` is `undefined`
> fix(client): Handle empty query arg

- docs/reference/sql-mapper/entities/api.md
- packages/sql-mapper/mapper.d.ts
- packages/sql-mapper/test/types/mapper.test-d.ts
For instance, without explicit support for null values in the WhereCondition interface, developers could inadvertently produce queries that do not behave as expected in scenarios involving null. Similarly, lacking clear documentation might lead to inconsistent query formulations or misunderstandings about how null comparisons are conducted in SQL, affecting data retrieval or manipulation tasks.
With these enhancements, the interface now directly accommodates null values, reducing potential for errors and increasing query precision. Improved documentation further aids developers, offering detailed insights into the operation of eq and neq with null, thereby standardizing practices and bolstering the robustness of applications built on our platform.
♻️ (mapper.d.ts): Update WhereCondition …
> fix(sql-mapper/types): enhance null value type support and documentation

- docs/reference/db/authorization/user-roles-metadata.md
- docs/reference/db/configuration.md
- packages/db-authorization/index.d.ts
- packages/db-authorization/index.js
- packages/db-authorization/lib/utils.d.ts
- packages/db-authorization/lib/utils.js
- packages/db-authorization/schema.js
- packages/db-authorization/test/role-path.test.js
- packages/db-authorization/test/utils.test.js
- packages/db/config.d.ts
- packages/db/lib/schema.js
- packages/db/schema.json
This to load roles from structured objects that can be loaded from JWT claims, e.g.:
```
"resource_access": {
"rest-api": {
"roles": [
"admin",
"user"
]
},
```
To support that, a `rolePath` can be used, specifying a dot-separated path. In this case we would need:
```
{ 
(...)
rolePath: "resource_access.rest-api.roles"
(...)
}
> Load roles from path from user context

- .github/workflows/ci.yml
@mcollina let's disable node js 18.9 for the runtime and create an issue to enable it when nodejs fix will arive. It fails everytime anyway. WDYT?
> ci: drop runtime node 18.9 ci

- docs/reference/composer/configuration.md
- packages/composer/config.d.ts
- packages/composer/lib/openapi-generator.js
- packages/composer/lib/schema.js
- packages/composer/package.json
- packages/composer/test/helper.js
- packages/composer/test/openapi/routes-composition.test.js
- pnpm-lock.yaml
Fix #2121
@mikaelkaron ptal. Unfortunaltelly it still will create a default description (it's another problem of how service schema is generated), but at least it will create a correct status codes with correct empty schemas.
> feat: compose responses with empty bodies

- packages/create-platformatic-auto/src/index.mjs
- packages/create-platformatic-auto/test/cli/helper.mjs
- packages/create-platformatic-auto/test/cli/runtime.test.mjs
> adds pnpm-workspace.yaml when creating app with pnpm

- docs/guides/use-env-with-platformatic.md
I added a head element for metadata, including the OG image and description, to the env guide; this will help improve SEO and create cards when we post guides on social media moving forward. 
We can also add media-specific cards to individual cards.
> Added SEO metadata to ENV guide

- packages/client/index.js
- packages/client/test/openapi.2.test.js
This fixes subtle bugs, since right now the client (when called), overrides the parameters passed.
As an example:
```
const params = {
path: { id: 'baz' },
query: { name: 'bar' }
})
}
const result = await client.getPath(params)
// 🫨 `params` is now { path: { id: undefined }, query: { name: undefined } } 🫣
```
> fix(client): Do not override client params

- packages/config/lib/manager.js
- packages/config/test/index.test.js
- packages/runtime/test/generator.test.js
The bug was introduced in https://github.com/platformatic/platformatic/pull/2456, I removed adding `process.env` to the runtime env.
Fix: #2568
> Avoid write all process.env entries in .env file

- docs/guides/generate-frontend-code-to-consume-platformatic-rest-api.md
We shouldn't suggest in the [docs](https://docs.platformatic.dev/docs/guides/generate-frontend-code-to-consume-platformatic-rest-api#configure-the-new-platformatic-app) a setting like `*` for  CORS, since it's highly unsafe. Better a more strict `"^http://localhost.*"`. Happy to update it also with another domain name...
> chore(docs): Suggest safer CORS RegExp

- packages/runtime/fixtures/configs/monorepo-with-dependencies.json
- packages/runtime/fixtures/monorepo-with-dependencies/main/clients/service-1/package.json
- packages/runtime/fixtures/monorepo-with-dependencies/main/clients/service-1/schema.json
- packages/runtime/fixtures/monorepo-with-dependencies/main/clients/service-2/package.json
- packages/runtime/fixtures/monorepo-with-dependencies/main/clients/service-2/schema.json
- packages/runtime/fixtures/monorepo-with-dependencies/main/external-service.schema.json
- packages/runtime/fixtures/monorepo-with-dependencies/main/platformatic.json
- packages/runtime/fixtures/monorepo-with-dependencies/service-1/clients/service-2/package.json
- packages/runtime/fixtures/monorepo-with-dependencies/service-1/clients/service-2/schema.json
- packages/runtime/fixtures/monorepo-with-dependencies/service-1/external-service.schema.json
- packages/runtime/fixtures/monorepo-with-dependencies/service-1/platformatic.json
- packages/runtime/fixtures/monorepo-with-dependencies/service-2/platformatic.json
- packages/runtime/lib/config.js
- packages/runtime/test/dependencies.test.js
@mcollina Can I drop the `dependents` property? It's bacisally the reversed `depencendies` that we never use. Just to not spend time on mainaning it.
> fix: parsing runtime service remote dependencies

- packages/db/index.d.ts
- packages/db/index.test-d.ts
- packages/db/lib/errors.js
fix typo within the library that handles errors in the DB package.
> fix: typo on db error lib

- packages/client-cli/lib/frontend-openapi-generator.mjs
- packages/client-cli/test/fixtures/array-query-parameters-openapi.json
- packages/client-cli/test/fixtures/array-query-params/.gitignore
- packages/client-cli/test/fixtures/array-query-params/openapi.json
- packages/client-cli/test/fixtures/array-query-params/platformatic.db.json
- packages/client-cli/test/fixtures/array-query-params/plugin.cjs
- packages/client-cli/test/frontend-openapi.test.mjs
When an OpenAPI spec defines a query parameter as `array` the previous generated code as follows
```js
queryParameters.forEach((qp) => {
if (request[qp]) {
if (Array.isArray(request[qp])) {
request[qp].forEach((p) => {
searchParams.append(`${qp}[]`, qp[p].toString() || '')  
})
} else {
searchParams.append(qp, request[qp]?.toString() || '')
}
delete request[qp]
}
})
```
would send a parameter like `ids=foo,bar,foobar` which would not be serialized back as an array
The new generated code show as follows
```js
queryParameters.forEach((qp) => {
if (request[qp]) {
if (Array.isArray(request[qp])) {
request[qp].forEach((p) => {
searchParams.append(qp + '[]', qp[p].toString() || '')
})
} else {
searchParams.append(qp, request[qp]?.toString() || '')
}
}
delete request[qp]
})
```
So basically we …
> Support array query parameters in frontend client requests

- packages/telemetry/lib/telemetry.js
- packages/telemetry/test/client.test.js
Also fixes the span `name` when port is not defined.
> Set `url.scheme` telemetry attribute in HTTP client calls

- docs/client/programmatic.md
- packages/client/index.d.ts
- packages/client/index.js
- packages/client/index.test-d.ts
- packages/client/test/openapi.2.test.js
With this new feature, 2 new optional options can be passed down to `undici` (as by [doc](https://github.com/nodejs/undici/blob/040d9da4a81f278270d0f73243815f89e4ce1b65/docs/docs/api/Client.md?plain=1#L22))
> feat(client): Allow passing timeout options

- packages/client/index.js
- packages/client/test/telemetry.test.js
- packages/composer/lib/openapi-generator.js
- packages/composer/lib/proxy.js
- packages/composer/test/telemetry/proxy.test.js
- packages/composer/test/telemetry/routes-composition-telemetry.test.js
- packages/runtime/lib/start.js
- packages/service/lib/plugins/metrics.js
This PR add a _client_ (sender) telemetry id as label to the server http metrics. In that way we can get the latency and requests amount between two different telemetry services. This is a draft, I would like to here what do you think first.
> feat: add telemetry id to the service http metrics

- packages/runtime/lib/generator/runtime-generator.js
- packages/runtime/test/generator.test.js
Close #2823
Needed to the ICC to use a user version of the @platformatic/runtime
> feat: add @platformatic/runtime to the app deps

- packages/composer/schema.json
- packages/control/test/config.test.mjs
- packages/db/schema.json
- packages/runtime/lib/api-client.js
- packages/runtime/lib/app.js
- packages/runtime/test/api/metrics.test.js
- packages/runtime/test/api/service-config.test.js
- packages/runtime/test/management-api/service-config.test.js
- packages/runtime/test/prom-metrics.test.js
- packages/service/lib/plugins/metrics.js
- packages/service/lib/schema.js
- packages/service/schema.json
- packages/service/test/metrics.test.js
We have prefixes in Prometheus metrics names, but doing that is a problem e.g. when aggregating the same metrics per labels. Also this multiplies the number of metrics in prometheus with no reason. 
In this Pr the prefix is removed from metrics name and added as label instead.
> Remove the prefix from metrics and use labels 

- packages/control/test/config.test.mjs
- packages/runtime/lib/api-client.js
- packages/runtime/lib/app.js
- packages/runtime/test/api/metrics.test.js
- packages/runtime/test/api/service-config.test.js
- packages/runtime/test/management-api/service-config.test.js
- packages/runtime/test/prom-metrics.test.js
- packages/service/lib/plugins/metrics.js
- packages/service/test/metrics.test.js
This is the same as https://github.com/platformatic/platformatic/pull/2875 but without removing the `prefix` from the config, so is not a breaking change
> Remove the prefix from metrics and use labels [v1.x]

- packages/runtime/fixtures/configs/monorepo-with-metrics.json
- packages/runtime/lib/app.js
- packages/runtime/test/api/service-config.test.js
The runtime metrics config is propagated to all services, but the `serviceId` must be added to all the services labels to correctly identify them in prometheus.
This is on v1.x, if OK, the commit will be ported to `main` too
> Set the `serviceId` on the runtime metrics services config

- packages/runtime/fixtures/configs/monorepo-with-metrics.json
- packages/runtime/lib/app.js
- packages/runtime/test/api/service-config.test.js
Same as: https://github.com/platformatic/platformatic/pull/2882
> Set the serviceId on the runtime metrics services'configs

- packages/client/index.js
- packages/client/test/telemetry.test.js
- packages/composer/lib/openapi-generator.js
- packages/composer/lib/proxy.js
- packages/db/package.json
- packages/db/test/helper.js
- packages/db/test/telemetry.test.js
- packages/service/index.js
- packages/sql-graphql/lib/telemetry.js
- packages/sql-graphql/test/telemetry.test.js
- packages/sql-mapper/lib/entity.js
- packages/sql-mapper/lib/telemetry.js
- packages/sql-mapper/mapper.js
- packages/sql-mapper/package.json
- packages/sql-mapper/test/helper.js
- packages/sql-mapper/test/telemetry.test.js
- packages/telemetry/lib/telemetry.js
- packages/telemetry/test/client.test.js
- packages/telemetry/test/internal.test.js
- pnpm-lock.yaml
Opentelemetry DB span. The `db.query` and `db.tx` functions has been wrapped to create the spans. 
Also, refactored some names, so that `startSpan` and `endSpan` are now generic and not only bound to HTTP.
> DB opentelemetry support

- packages/runtime/fixtures/monorepo/serviceAppWithLogger/plugin.js
- packages/runtime/lib/runtime.js
- packages/runtime/test/api/stop.4.test.js
Runtime should handle the service stop command error and kill the worker thread anyway.
> fix: catch runtime service stop error

- packages/db/test/helper.js
- packages/db/test/telemetry.test.js
- packages/sql-mapper/lib/connection-info.js
- packages/sql-mapper/lib/telemetry.js
- packages/sql-mapper/mapper.js
- packages/sql-mapper/test/helper.js
- packages/sql-mapper/test/telemetry.test.js
We need more span attirbutes when doing DB queries. 
The `pgIntrumentation` sets:
```
'db.system': 'postgresql',
'db.name': 'postgres',
'db.connection_string': 'postgresql://127.0.0.1:5432/postgres',
'net.peer.name': '127.0.0.1',
'net.peer.port': 5432,
'db.user': 'postgres',
'db.statement': 'SELECT "id", "title"\n FROM "public"."pages"\nLIMIT $1' 
```    
In this PR we set also all these attributes for the supported DBs , with the exception on `db.connection_string` (because it might contain password), and also is not useful for telemetry, given all the other attributes).
> More DB telemetry attributes

- packages/composer/index.js
- packages/composer/lib/stackable.js
- packages/composer/test/helper.js
- packages/composer/test/stackable/get-config.test.js
- packages/composer/test/stackable/get-graphql-schema.test.js
- packages/composer/test/stackable/get-info.test.js
- packages/composer/test/stackable/get-openapi-schema.test.js
- packages/composer/test/stackable/inject.test.js
- packages/config/index.d.ts
- packages/control/test/config.test.mjs
- packages/db/test/stackable/get-config.test.js
- packages/db/test/stackable/get-graphql-schema.test.js
- packages/db/test/stackable/get-info.test.js
- packages/db/test/stackable/get-openapi-schema.test.js
- packages/db/test/stackable/inject.test.js
- packages/runtime/lib/worker/app.js
- packages/runtime/lib/worker/main.js
- packages/runtime/test/app.test.js
- packages/runtime/test/cli/do-not-crash-on-syntax-error.test.mjs
- packages/runtime/test/cli/server.test.mjs
- packages/runtime/test/cli/start/start.4.test.mjs
- packages/runtime/test/start/logs-errors-during-migrations.test.js
- packages/service/index.d.ts
- packages/service/index.js
- packages/service/lib/stackable.js
- packages/service/test/stackable/get-config.test.js
- packages/service/test/stackable/get-graphql-schema.test.js
- packages/service/test/stackable/get-info.test.js
- packages/service/test/stackable/get-openapi-schema.test.js
- packages/service/test/stackable/inject.test.js
this PR does two things:
- moves all code that works with a service config from the runtime to the stackable interface
- reduces the buildStackable function signature. Now it accepts the path to the config and returns only the stackable interface.
> feat: move runtime service config parsing to the stackable interface

- packages/db/lib/adjust-config.js
- packages/db/lib/schema.js
- packages/db/schema.json
This does two things:
- allows config for `types.autogenerate` to be either `boolean` or `string`
- adds short description for `types.autogenerate`
> Add string support for `types.autogenerate`

- packages/generators/lib/base-generator.js
- packages/generators/test/base-generator.test.js
Always set `skipLibCheck: true` in generated `tsconfig.json` to avoid problems.
Source: https://x.com/mattpocockuk/status/1820454283457765645
> Always set skipLibCheck: true in generated tsconfig

- docs/guides/monitoring.md
I saw many links to the environment variables placeholder docs landing in 404, i only fixed it here in the monitoring section. I could open a PR fixing it in the other places if this PR makes sense
> fix link to environment variables placeholder

- packages/composer/lib/proxy.js
Request redirecting doesn't work because composer has no idea what was the original url that came to the application.
> feat: proxy root request instead of redirecting it

- packages/basic/index.js
- packages/wattpm/index.js
- packages/wattpm/lib/commands/execution.js
- packages/wattpm/lib/commands/external.js
- packages/wattpm/lib/commands/init.js
- packages/wattpm/lib/defaults.js
- packages/wattpm/lib/schema.js
- packages/wattpm/lib/utils.js
- packages/wattpm/package.json
- packages/wattpm/test/execution.test.js
- packages/wattpm/test/external.test.js
- packages/wattpm/test/fixtures/no-dependencies/package.json
- packages/wattpm/test/fixtures/no-dependencies/watt.json
- packages/wattpm/test/fixtures/no-dependencies/web-1/first/index.js
- packages/wattpm/test/fixtures/no-dependencies/web-1/second/index.js
- packages/wattpm/test/fixtures/no-dependencies/web-2/third/index.js
- packages/wattpm/test/helper.js
- packages/wattpm/test/init.test.js
- pnpm-lock.yaml
The `wattpm import` command now behaves like this:
1. When doing `wattpm import rootDir local/folder/somewhere`, the folder is added in the `services` of the root `watt.json`. If the target folder has no `watt.json`, it also makes sure one exists and that the proper package is installed in `package.json`.
2. When doing `wattpm import rootDir http://...`, the URL is added in `watt.json`.
3. When doing `wattpm import rootDir`, the command scans for all services (autoloaded or explicitly specified in the `watt.json`) and performs the same checks made in 1.
> Enhancement to the import command

- packages/utils/lib/streams/destination-writable.js
The reason for the crash in https://github.com/platformatic/platformatic/issues/3205, was obscured by this. Long term, we would have to rewrite the logging stream.
> Avoid losing log messages if another write is in progress

- packages/basic/lib/worker/child-process.js
- packages/basic/lib/worker/listeners.js
Fixes #3223.
FWIW, there is also an "error" (is not technically an error but it might be confusing) in the user code. In the `apps/express/app/index.ts` he was doing this:
```
app.listen(port, host).on("listening", () => {
logger.info(
`Express server is listening on port http://${host}:${port}`
);
});
```
But since Watt is changing the port, this would be more correct:
```
app.listen(port, host).on("listening", function () {
logger.info(
`Express server is listening on port http://${host}:${this.address().port}`
);
});
```
> fix: Do not set a port when dealing with UNIX sockets.

- packages/client-cli/lib/openapi-common.mjs
- packages/client-cli/test/cli-openapi.test.mjs
- packages/client-cli/test/frontend-openapi.test.mjs
Any scaffolded up using platformatic with default `Movies` table, then run 
```bash
npx platformatic client http://127.0.0.1:3042/api --frontend --language ts
```
Example: https://github.com/no-treasure/plt-watt-demo/tree/develop/services/frontend/src/api
If we call `getMovies()` but don't specify any arguments, we won't get any error from TS, but it will throw an error:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'limit')
```
because in `_getMovies()` and `getMovies()` expects that `request: Types.GetMoviesRequest` should be passed, but there will be undefined in this case
```ts
queryParameters.forEach((qp) => {
//      undefined[qp]
if (request[qp]) {
if (Array.isArray(request[qp])) {
;(request[qp] as string[]).forEach((p) => { …
```
> fix(client-cli): `req` type definition

- packages/client-cli/lib/openapi-common.mjs
- packages/client-cli/package.json
- packages/client-cli/test/cli-openapi-empty-req-res.test.mjs
- packages/client-cli/test/fixtures/empty-req-res/openapi.json
- packages/client-cli/test/fixtures/empty-req-res/package.json
- packages/client-cli/test/fixtures/empty-req-res/platformatic.service.json
- packages/client-cli/test/fixtures/empty-req-res/plugins/example.js
With an Open API schema like:
```json
{
"paths": {
"/hello": {
"get": {
"operationId": "getHello",
"responses": {
"200": {
"description": "Default Response"
}
}
}
}
}
}
```
We currently return an invalid TS syntax:
```ts
export type GetHelloRequest = {
unknown
}
```
With this fix, will return valid TypeScript code:
```ts
export type GetHelloRequest = {
}
```
> fix(client-cli): Handle empty req/res OpenAPI schema

- packages/client-cli/lib/openapi-common.mjs
- packages/client-cli/lib/openapi-generator.mjs
- packages/client-cli/test/cli-openapi.test.mjs
When we have a `multipart/form-data` content type, we should define it as a request body.
> fix(client-cli): Define form data type on the request

- packages/cli/package.json
- pnpm-lock.yaml
This was supposed to happen for the v2 release but it slipped. This is not actually needed at all.
> Actually remove Platformatic DB from the CLI

- packages/node/index.js
- packages/node/test/telemetry.test.js
We need this because we user the `serviceName` in telemetry
> Set telemetry config on nodejs services

- packages/client-cli/lib/frontend-openapi-generator.mjs
- packages/client-cli/test/expected-generated-code/multiple-responses-movies.ts
- packages/client-cli/test/frontend-openapi.test.mjs
Valid `content-type` headers can be either `application/json` or `application/json; charset=...` so it's safer to use `startsWith`
> Check json response with startsWith rather than ===

- packages/client/index.js
- packages/client/test/openapi.test.js
2.16.0 has broken platformatic client for users using `throwOnError: true` as now all errors have a status code of 500 rather than the status code that was in the original error response, so adding a small fix.
> fix: persist status code from response to UnexpectedCallFailureError

- docs/composer/configuration.md
Small PR - fixes the CLI guide reference in `docs/composer/configuration.md`.
> docs: update CLI guide reference

- docs/runtime/_shared-configuration.md
- packages/runtime/fixtures/env-config/platformatic.json
- packages/runtime/fixtures/env-config/services/hello/package.json
- packages/runtime/fixtures/env-config/services/hello/server.js
- packages/runtime/fixtures/env-config/services/hello/test.env
- packages/runtime/lib/runtime.js
- packages/runtime/lib/schema.js
- packages/runtime/lib/worker/main.js
- packages/runtime/package.json
- packages/runtime/schema.json
- packages/runtime/test/config.test.js
- pnpm-lock.yaml
Add support for setting `env` object and `envfile` path in services of top-level config file to load env vars into the worker thread for the service when starting up.
> feat: support configuring env and envfile in main config file

- .github/workflows/ci.yml
- packages/frontend-template/package.json
This allows workspace-level pnpm test to work, and simplifies the GitHub Actions workflow yaml.
> Add pretest to frontend-template

- packages/wattpm/lib/commands/build.js
- packages/wattpm/lib/commands/external.js
- packages/wattpm/lib/utils.js
- packages/wattpm/test/utils.test.js
Connected to [this issue](https://github.com/platformatic/platformatic/issues/3630), steps done:
* add `yarn` auto-detect for `resolve` command
* have the package manager logic detection in a single place
* add tests to check that logic
> fix(wattpm): enable yarn auto detect

- docs/runtime/_shared-configuration.md
- packages/runtime/fixtures/typescript/services/titles/routes/root.ts
- packages/runtime/lib/runtime.js
- packages/runtime/lib/schema.js
- packages/runtime/schema.json
- packages/runtime/test/config.test.js
- packages/wattpm/test/management.test.js
Add support for enabling source maps per-service or globally.
Fixes #3561
> Add sourceMaps config option

- packages/basic/lib/worker/listeners.js
- packages/node/index.js
- packages/node/test/fixtures/node-async-local-storage-inject/package.json
- packages/node/test/fixtures/node-async-local-storage-inject/platformatic.runtime.json
- packages/node/test/fixtures/node-async-local-storage-inject/services/api/index.js
- packages/node/test/fixtures/node-async-local-storage-inject/services/api/package.json
- packages/node/test/fixtures/node-async-local-storage-inject/services/api/platformatic.application.json
- packages/node/test/inject.test.js
This allows servers found via diagnostics_channel `net.server.listen` events to run injected requests while retaining the asynchronous context captured by the `server.listen(...)` and creating new asynchronous resources as normal http request handle objects would.
> Fix ALS when calling inject() on @platformatic/node stackable

- packages/cli/test/install.test.js
- packages/wattpm/lib/commands/build.js
- packages/wattpm/lib/utils.js
- packages/wattpm/test/build.test.js
- packages/wattpm/test/resolve.test.js
- packages/wattpm/test/utils.test.js
Fixes the current setup for main folder and subfolder services:
* add a `getPackageArgs` that will define the `args` to be passed when running `resolve`, and it will be called for the `root` and for the nested services
* fix how we auto-detect package manager for nested services => if available, we check first the service option, then the auto-detection for the service, and finally we default to the root package manager
> fix(wattpm): properly auto resolve nested package manager

- packages/db-authorization/index.d.ts
- packages/sql-mapper/mapper.d.ts
- packages/sql-mapper/test/types/mapper.test-d.ts
@mcollina this commit fix typescript where definition, which did not include the "or" operator.
If you prefer I can rename the existing WhereCondition in SingleWhereCondition and define a new type WhereCondition as `type WhereCondition = SingleWhereCondition | { or: SingleWhereCondition[] }`
Let me know how you prefer to proceed
> fix OR WhereCondition type definition

- packages/client-cli/cli.mjs
- packages/client-cli/help/help.txt
- packages/client-cli/lib/frontend-openapi-generator.mjs
- packages/client-cli/lib/openapi-common.mjs
- packages/client-cli/lib/openapi-generator.mjs
- packages/client-cli/test/cli-openapi-optional-body.test.mjs
- packages/client-cli/test/fixtures/optional-body/openapi.json
- packages/client-cli/test/fixtures/optional-body/package.json
- packages/client-cli/test/fixtures/optional-body/platformatic.service.json
- packages/client-cli/test/fixtures/optional-body/plugins/example.js
As of today, if `required` array is missing in the Open API schema, we mark the properties as required.
Even though the correct behavior should be different, I added a new property called `--props-optional` (defaulted to `false`) to update this logic avoiding breaking changes.
> feat(client cli): add props optional param

- packages/runtime/lib/worker/http-cache.js
- packages/runtime/test/http-cache.test.js
- packages/telemetry/lib/telemetry-config.js
- packages/telemetry/lib/thread-interceptor-hooks.js
This is needed to understand if the trace is done and not wait for a server span if client request was cached.
> feat: add an http.cache.hit attribute

- packages/control/index.d.ts
- packages/control/index.test-d.ts
Will address [this comment](https://github.com/platformatic/watt-admin/pull/5/files#diff-072c26ea8fdfa78fdf65b9c419df4a7bf068a950d5ef4fa8b65ca53de1ba4cbeR32)
> chore(control): add runtime and services types

- packages/control/index.d.ts
- packages/control/index.test-d.ts
- packages/control/lib/runtime-api-client.js
- packages/control/test/runtime-api.test.mjs
This will be useful for instance for [watt-admin](https://github.com/platformatic/watt-admin/pull/8/files#diff-73d0003e548bafddce265b62b5fa08bb66f5243eec635b2388479f4a65bc09a1R9)
> chore(control): add metrics types

- packages/client-cli/cli.mjs
- packages/client-cli/test/fixtures/client-with-config/openapi.json
- packages/client-cli/test/fixtures/client-with-config/watt.json
- packages/client-cli/test/frontend-openapi.test.mjs
**Why?**
As of today, when running `platformatic client http://127.0.0.1:3042/documentation/json --frontend --language ts --name client --full` the watt.json is updated with a `clients` section, which is not allowed since we're in a frontend project leveraging `@platformatic/vite`:
**How?**
We are now checking if it's a front-end project. In this case, we do not update the `config,` and we force the generation of a [client.ts](https://github.com/platformatic/watt-admin/pull/15/files#diff-6e8e03da88f2244788f0fc7d769338e93cb338acafec18857b43655ace35067f)
**QA?**
You can test it by running the `client` command of [this branch](https://github.com/platformatic/watt-admin/pull/15/files#diff-0816cd46d529b043bd6c753c560b74405e043bc40c7b3f9fc9083d16ef23ed46R11)
> fix(client cli): frontend generation

- packages/client-cli/lib/frontend-openapi-generator.mjs
- packages/client-cli/test/expected-generated-code/multiple-responses-movies.ts
- packages/client-cli/test/frontend-openapi.test.mjs
- Use a more strict `object` type rather than `Object` (which can wrongly include values such as `number`, `boolean`, `null`, etc.)
- Do not cast `json()` and `text()` return values (since they already have a proper type defined [here](https://github.com/microsoft/TypeScript/blob/main/src/lib/dom.generated.d.ts#L3465))
- Use optional chaining when defining header values
- Add comment on `ts-ignore`
> fix(client cli): use proper types

- Dockerfile
We should have done this bump when we marked Platformatic v2, however it seems now the best path forward to update to latest v22 in a minor.
> Update dockerfile to v22

- packages/client/index.js
- packages/client/test/openapi.test.js
platformatic client will use the global dispatcher unless one is supplied via the dispatcher option, however if throwOnError is set to true, it will create an internal Agent and use that instead. If you're using setGlobalDispatcher() in your code, the client will stop using it when you enable throwOnError.
Making a small change to ensure the client will always use the global dispatcher if a custom dispatcher is not supplied, whether throwOnError is on or off.
> Platformatic Client: use global dispatcher when throwOnError is true

- docs/cli.md
- packages/client-cli/cli.mjs
- packages/client-cli/help/help.txt
- packages/client-cli/package.json
- packages/client-cli/test/cli-openapi.test.mjs
When you have a repo with a `watt.json` file and you run the `client-cli`: it updates the `watt.json` by adding a `clients` section (which is invalid as not included in the [schema](https://schemas.platformatic.dev/@platformatic/node/2.35.1.json)).
This PR fixes this bug.
> fix(client cli): do not update watt.json

- packages/client-cli/lib/openapi-common.mjs
- packages/client-cli/lib/openapi-generator.mjs
- packages/client-cli/lib/responses-writer.mjs
- packages/client-cli/test/cli-openapi.test.mjs
- packages/client-cli/test/fixtures/client-with-config/openapi.json
- packages/client-cli/test/fixtures/tsdoc-openapi.json
- packages/client-cli/test/frontend-openapi.test.mjs
- packages/client-cli/test/responses-writer.test.mjs
Adds tsdoc comments to client-cli generated types, to give you info in your editor what the different APIs do, and what the different request parameters are.
Example
| Before  | After |
| ------------- | ------------- |
| ![image](https://github.com/user-attachments/assets/129ef4c2-466f-40bc-9503-1a71102063c2) | ![image](https://github.com/user-attachments/assets/9b9a10fd-78b3-4a9b-a66d-74b0635b7bce)  |
| ![image](https://github.com/user-attachments/assets/dcab8af5-d010-4e94-968f-dcb2c35e0ee7)  | ![image](https://github.com/user-attachments/assets/76a9dfc6-6cbb-4612-a7de-f0e0b98afe35)  |
| ![image](https://github.com/user-attachments/assets/ff2df3f5-e774-4fb1-8ae2-1a1ea34ee6c1) | ![image](https://github.com/user-attachments/assets/477a5603-e008-4682-8217-575cf0048846)  |
(Your mileage …
> feat: add api descriptions from schema to type definitions

- packages/client-cli/lib/responses-writer.mjs
- packages/client-cli/test/cli-openapi-additional-properties.test.mjs
- packages/client-cli/test/cli-openapi.test.mjs
- packages/client-cli/test/fixtures/additional-properties-openapi.json
- packages/client-cli/test/frontend-openapi.test.mjs
- packages/client-cli/test/responses-writer.test.mjs
When the OpenAPI specs are defined with:
```
"application/json": {
"schema": {
"type": "object",
"additionalProperties": {
"type": "object",
"properties": {
"description": {
"type": "string"
}
},
"required": ["description"],
"additionalProperties": false
}
}
}
```
the generated types will currently be:
```
export type GetAnotherResponseOK = {
'type': unknown;
'properties': unknown;
'required': unknown;
'additionalProperties': unknown;
}
```
Make sure that the generated types are `Record<string, { 'description': string }>` by using the `getType` function which is better handling the optional & addition properties than `writeObjectProperties`.
> fix: correctly interpret Record response

- packages/client-cli/lib/get-type.mjs
- packages/client-cli/test/cli-openapi-nullable-properties.test.mjs
- packages/client-cli/test/fixtures/nullable-properties-openapi.json
The property `nullable` is currently not used for `object`, `array` and `enum` when generating the types.
Add the check on the nullable property and a test for cases with and without this property
> fix: correctly handle nullable properties

- packages/client-cli/lib/openapi-common.mjs
- packages/client-cli/test/cli-openapi.test.mjs
- packages/client-cli/test/fixtures/tsdoc-openapi.json
Hi, generated a new client for an API today then after checking their swagger I realised I'd been using deprecated methods (they're greyed out in the UI).
Adding `@deprecated` jsdoc tags to the client types so I can avoid making the same mistake in the future :)
| Before    | After |
| -------- | ------- |
| ![image](https://github.com/user-attachments/assets/f5e3fe5e-5835-466c-8533-4dc50466fa7e) | ![image](https://github.com/user-attachments/assets/f0113bcc-a4e4-43fa-aada-ecccef147610)    |
| ![image](https://github.com/user-attachments/assets/3bcc6566-a45f-491f-828c-8f7883c0e886) |  ![image](https://github.com/user-attachments/assets/81746b1c-bc94-45c7-b2b2-dce853409e83)  |
(Crosses out deprecated methods, but again your mileage may vary for your editor of choice!)
> feat(client-cli): add @deprecated jsdoc tag to deprecated client methods

- packages/client-cli/lib/frontend-openapi-generator.mjs
- packages/client-cli/test/frontend-openapi.test.mjs
As by title, this PR allows to handle query params when they are optional, like in the following case:
```ts
export type GetDataRequest = {
path: {
'id': string;
}
query?: {
'someEnum'?: 'one' | 'two';
}
}
```
> fix(client cli): handle optional query params

- packages/client-cli/test/fixtures/allof-anyof-schema/openapi.json
- packages/client-cli/test/fixtures/allof-anyof-schema/platformatic.db.json
- packages/client-cli/test/fixtures/allof-anyof-schema/plugin.cjs
- packages/client-cli/test/fixtures/content-types/openapi.json
- packages/client-cli/test/fixtures/content-types/platformatic.db.json
- packages/client-cli/test/fixtures/content-types/plugin.cjs
- packages/client-cli/test/fixtures/fetch-params/openapi.json
- packages/client-cli/test/fixtures/fetch-params/platformatic.db.json
- packages/client-cli/test/fixtures/fetch-params/plugin.cjs
- packages/client-cli/test/fixtures/full-response-simple/openapi.json
- packages/client-cli/test/fixtures/full-response-simple/platformatic.db.json
- packages/client-cli/test/fixtures/full-response-simple/plugin.cjs
- packages/client-cli/test/fixtures/no-content-response/openapi.json
- packages/client-cli/test/fixtures/no-content-response/platformatic.db.json
- packages/client-cli/test/fixtures/no-content-response/plugin.cjs
- packages/client-cli/test/fixtures/optional-headers/openapi.json
- packages/client-cli/test/fixtures/optional-headers/platformatic.db.json
- packages/client-cli/test/fixtures/optional-headers/plugin.cjs
- packages/client-cli/test/fixtures/optional-query-params/openapi.json
- packages/client-cli/test/fixtures/optional-query-params/platformatic.db.json
- packages/client-cli/test/fixtures/optional-query-params/plugin.cjs
- packages/client-cli/test/frontend-openapi.test.mjs
As titled, add specific tests to check that recently added features works fine at runtime when calling the `client` generated by `@platformatic/client-cli`
> chore(client cli): add integration tests

- packages/control/index.d.ts
- packages/control/index.test-d.ts
Fix for https://github.com/platformatic/watt-admin/pull/24/files#diff-511e34c1ee368c527d7e811a3e07a4dec0bd755bfe568f11e498bfe6fc5ef67bR152
> fix(control): add missing metric type

- packages/metrics/package.json
- packages/metrics/test/index.test.js
While working on [this](https://github.com/platformatic/platformatic/pull/3973), I realized we do not have any tests for the `metrics` package. This PR adds just some basic tests
> chore(metrics): add tests

- packages/wattpm/index.js
- packages/wattpm/lib/commands/admin.js
This adds the `wattpm admin` command that defers to npx.
I didn't add tests because I don't want to add a module mocking system right now (and deal with the complexity of ESM loaders).
The code is simple enough.
> Added admin command

- packages/sql-mapper/lib/cursor.js
- packages/sql-mapper/lib/entity.js
- packages/sql-mapper/lib/errors.js
- packages/sql-mapper/mapper.d.ts
- packages/sql-mapper/test/cursor.test.js
I've decided to divide issue #230 into several PRs (if its ok). This one contains changes for the sql-mapper module. 
* Adds the multi-column cursor to sql-mapper. 
* Cursor respects the order of `orderBy` fields when generating conditions
*  `where` and `orderBy` clauses can be used with cursor
* Forward and backward pagination is supported using `nextPage` key
* Generates short SQL tuple comparison when all sort directions match and falls back to compound query when mixed directions used
[Support multi-column cursors](https://github.com/prisma/prisma/issues/19159)
> #230 (part 1) - Cursor pagination in sql-mapper

- packages/node/index.js
- packages/node/package.json
- packages/node/test/fixtures/node-with-build-no-main/package.json
- packages/node/test/fixtures/node-with-build-no-main/platformatic.runtime.json
- packages/node/test/fixtures/node-with-build-no-main/services/frontend/package.json
- packages/node/test/fixtures/node-with-build-no-main/services/frontend/platformatic.application.json
- packages/node/test/fixtures/node-with-build-no-main/services/frontend/src/server.ts
- packages/node/test/fixtures/node-with-build-no-main/services/frontend/tsconfig.json
- packages/node/test/production.test.js
This avoids errors such as:
```
[09:49:37.048] ERROR (47574): Failed to start service "noir".
err: {
"type": "Error",
"message": "Cannot find module '/Users/matteo/tmp/eeee/web/noir/dist/dist/server.js' imported from /Users/matteo/tmp/eeee/node_modules/@platformatic/basic/lib/utils.js",
"stack":
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/matteo/tmp/eeee/web/noir/dist/dist/server.js' imported from /Users/matteo/tmp/eeee/node_modules/@platformatic/basic/lib/utils.js
at finalizeResolution (node:internal/modules/esm/resolve:275:11)
at moduleResolve (node:internal/modules/esm/resolve:860:10)
at defaultResolve (node:internal/modules/esm/resolve:984:11)
at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:685:12)
at #cachedDefaultResolve …
```
> Avoid adding the typescript prefix in production mode

- packages/config/index.d.ts
- packages/config/lib/manager.js
- packages/config/test/index.test.js
This option avoids loading `.env` files from `@platformatic/config` when it is set as `true`
> feat(config): add disable env loaded option

- packages/runtime/lib/generator/runtime-generator.js
- packages/runtime/test/generator.test.js
- Fix bug where .env.sample was being generated using config.env instead of config.defaultEnv
- Add tests to verify correct behavior for environment variables in .env vs .env.sample files
- The .env.sample file should contain default values while .env should contain actual runtime values
> fix(runtime): correctly store default env as sample

- packages/client-cli/cli.mjs
Unneeded and it's causing the `Response Error` issue
> fix(client cli): do not add error interceptor

- packages/control/lib/errors.js
- packages/control/lib/runtime-api-client.js
- packages/control/test/pprof.test.mjs
- packages/runtime/lib/management-api.js
- packages/runtime/lib/runtime.js
- packages/runtime/test/management-api/pprof.test.js
- packages/runtime/test/pprof-commands.test.js
- packages/watt-pprof-capture/lib/errors.js
- packages/wattpm/index.js
- packages/wattpm/lib/commands/help.js
- packages/wattpm/lib/commands/pprof.js
- packages/wattpm/test/pprof.test.js
This adds pprof-calling support to:
- runtime instance
- management API
- control client
- wattpm commands
With that we should have the full flow to trigger profiles via the wattpm CLI.
> Add wattpm pprof commands

- packages/utils/lib/features.js
Fixes #4262
A bit more cautious approach would be to enable majors manually (in case something will be deprecated/removed), so let me know wdyt.
> fix: enable reusePort and getHeapStatistics post node 24 (#4262)

- docs/reference/node/overview.md
- packages/basic/test/helper.js
- packages/node/lib/capability.js
- packages/node/test/fixtures/node-no-server-lifecycle/package.json
- packages/node/test/fixtures/node-no-server-lifecycle/platformatic.runtime.json
- packages/node/test/fixtures/node-no-server-lifecycle/services/background-app/index.mjs
- packages/node/test/fixtures/node-no-server-lifecycle/services/background-app/package.json
- packages/node/test/fixtures/node-no-server-lifecycle/services/background-app/platformatic.application.json
- packages/node/test/misc.test.js
Solves: https://github.com/platformatic/platformatic/issues/4309
For now, I added it only for no server apps - let me know if it's worth to expand to "blackbox" apps as well.
> feat: allow closing no-server apps

- packages/runtime/lib/runtime.js
- packages/runtime/test/vertical-scaler.test.js
Setting the default params back to config so we can read them later. In the watt-extra for example.
> feat: set verticalScaler default values back to config
