- packages/db/lib/gen-types.mjs
- packages/db/lib/migrate.mjs
- packages/db/test/cli/gen-types.test.mjs
- packages/db/test/fixtures/auto-gen-types/platformatic.db.json
> feat(db): create plugin.js after types generation

- README.md
- packages/cli/README.md
Changed discord link in `README.md`
> Discord correct link

- packages/sql-mapper/mapper.d.ts
- packages/sql-mapper/mapper.js
- packages/sql-mapper/test/types/mapper.test-d.ts
> fix(sql-mapper): convert `isMySQL` to `isMySql`

- packages/db/test/cli/gen-types.test.mjs
> test(db): run types generation tests in parallel

- packages/db/index.js
- packages/db/package.json
- pnpm-lock.yaml
> fastify-isolate got renamed to fastify-sandbox

- packages/db/lib/init.mjs
- packages/db/test/cli/init.test.mjs
> Creates also undo migration in 'db init'

- packages/sql-graphql/index.js
- packages/sql-graphql/test/simple.test.js
> feat(sql-graphql): creates default query `hello` when no schema is defined

- docs/reference/sql-mapper/introduction.md
> docs: adds missing import line

- docs/reference/cli.md
- packages/db/help/help.txt
> docs(db): add missing commands to db help

- packages/sql-graphql/lib/utils.js
- packages/sql-graphql/package.json
- packages/sql-graphql/test/helper.js
- packages/sql-graphql/test/simple.test.js
- packages/sql-json-schema-mapper/index.js
- packages/sql-json-schema-mapper/test/helper.js
- packages/sql-json-schema-mapper/test/simple.test.js
- packages/sql-openapi/test/helper.js
- packages/sql-openapi/test/order_by.test.js
- packages/sql-openapi/test/simple.test.js
- packages/sql-openapi/test/where.test.js
- pnpm-lock.yaml
> feat(multi): Support for JSON columns

- docs/reference/migrations.md
- packages/db/fixtures/multiple-migrations.json
- packages/db/fixtures/multiple-migrations/001.do.sql
- packages/db/fixtures/multiple-migrations/001.undo.sql
- packages/db/fixtures/multiple-migrations/002.do.sql
- packages/db/fixtures/multiple-migrations/002.undo.sql
- packages/db/fixtures/multiple-migrations/003.do.sql
- packages/db/fixtures/multiple-migrations/003.undo.sql
- packages/db/lib/migrate.mjs
- packages/db/lib/migrator.mjs
- packages/db/test/migrate/migrate.test.mjs
One step migration / rollback with up/down:
```
npx platformatic db migrate -u
npx platformatic db migrate -d
```
> Migration rollback command

- packages/db-authorization/index.js
- packages/db-authorization/test/simple-rest.test.js
> fix: non working parameters on protected listing endpoint

- packages/db/index.js
- packages/db/lib/migrate.mjs
- packages/db/lib/migrator.mjs
- packages/db/package.json
- packages/db/test/migrate/migrate.test.mjs
- pnpm-lock.yaml
> Disabled migration on hot reloading

- packages/db/package.json
- packages/db/test/load-and-reload-files.test.js
- pnpm-lock.yaml
> Add test for botched file reloading

- .github/workflows/announce-releases.yml
> Announce releases on discord

- docs/getting-started/movie-quotes-app-tutorial.md
- docs/getting-started/quick-start-guide.md
- docs/reference/migrations.md
- packages/db/fixtures/sqlite/platformatic.db.json
- packages/db/index.js
- packages/db/test/cli/migrate.test.mjs
- packages/db/test/fixtures/auto-apply.json
- packages/db/test/fixtures/auto-gen-types/platformatic.db.json
- packages/db/test/fixtures/bad-typescript-plugin/platformatic.db.json
- packages/db/test/fixtures/gen-types-typescript/platformatic.db.json
- packages/db/test/fixtures/gen-types/platformatic.db.json
- packages/db/test/fixtures/invalid-migrations-directory.json
- packages/db/test/fixtures/no-auto-apply.json
- packages/db/test/fixtures/sqlite/platformatic.db.json
- packages/db/test/fixtures/validate-migrations-checksums.json
- packages/db/test/fixtures/watch/platformatic.db.json
Will fix #101
May need some touchups.
> feat: disable migrations by default #101

- docs/reference/configuration.md
> docs: Adds sample min configuration in docs

- packages/db/lib/root-endpoint/public/index.html
- packages/db/test/routes.test.js
> feat(db): adds links in home page to openapi/graphql docs

- packages/sql-openapi/test/simple.test.js
This is just an example of how you could write the test cases.
Could be a good idea ? What do you think?
> test: improve test readability using an url constant in the messages

- docs/guides/monitoring.md
This is a guide on howto set and test monitoring with Prometheus and Grafana.
> Monitoring guide with Prometheus

- packages/db/db.mjs
- packages/db/tap-snapshots/test/cli/schema.test.mjs.test.cjs
- packages/db/test/cli/schema.test.mjs
- packages/db/test/metrics.test.js
> Show schema help if missing schema type in schema generation

- docs/reference/configuration.md
- packages/db/lib/schema.js
- packages/sql-openapi/index.js
- packages/sql-openapi/test/simple.test.js
- packages/sql-openapi/test/tap-snapshots/simple-openapi-4.cjs
> OpenAPI prefix

- .github/workflows/ci.yml
- .github/workflows/update-docs.yml
- README.md
Also renamed the workflow to have a better name on badges (and all lowercase)
> Readme Badges

- packages/sql-graphql/lib/relationship.js
- packages/sql-graphql/test/helper.js
- packages/sql-graphql/test/relations.test.js
> Fixing #188: Allow multi reference

- CONTRIBUTING.md
> Issue 65 contributing start platformatic db section

- CONTRIBUTING.md
Could you add a linter for markdown?
> doc: fix ordered list in CONTRIBUTING.md

- .gitignore
- CONTRIBUTING.md
- docs/reference/db/dashboard.md
- packages/db-dashboard/.env.sample
> Updates docs for db-dashboard

- docs/guides/deployment/advanced-fly-io-deployment.md
- docs/guides/deployment/deploy-to-fly-io-with-sqlite.md
When you review this, please take a look at the "TODO" comments and let me know your thoughts.
Once this PR has been approved and merged, I'll create a PR to add the 'Add SQLite Backups on Fly.io' how-to guide.
> Add Deploy to Fly.io with SQLite how-to guide

- docs/reference/sql-mapper/entities/transactions.md
- packages/sql-mapper/lib/entity.js
- packages/sql-mapper/mapper.d.ts
- packages/sql-mapper/package-lock.json
- packages/sql-mapper/package.json
- packages/sql-mapper/test/entity_transaction.test.js
- pnpm-lock.yaml
> Entity transaction support

- docs/reference/db/authorization/introduction.md
- packages/db-authorization/index.js
- packages/db-authorization/lib/jwt.js
- packages/db-authorization/lib/webhook.js
- packages/db-authorization/test/jwt-webhook.test.js
Fixes https://github.com/platformatic/platformatic/issues/258
> Support authorization via JWT and Webhook at the same time

- packages/db-authorization/test/simple-subscription.test.js
> Fix db-authorization subscription flaky test

- packages/db/index.js
- packages/db/test/cli/helper.mjs
- packages/db/test/cli/load-and-reload-files.test.mjs
It's a very popular use case when uploading ts compiled modules.
> feat(db): add support for plugin import with export default property

- packages/sql-openapi/lib/entity-to-routes.js
- packages/sql-openapi/test/helper.js
- packages/sql-openapi/test/nested.test.js
- packages/sql-openapi/test/tap-snapshots/nested-routes-openapi-recursive.cjs
Fixes: https://github.com/platformatic/platformatic/issues/259
Also, fixed a bug about passing the wrong PK when getting the "parent" entity (the unit test was passing because the key value was the same, fixed also the test).
> Nested recursive relationship support

- packages/db-ra-data-rest/.npmignore
- packages/db-ra-data-rest/README.md
Hey there.
Solves issues #265 #270
> fix: add npmignore and readme to db-ra-data-rest

- packages/db/lib/gen-types.mjs
- packages/db/test/cli/gen-types.test.mjs
- packages/db/test/fixtures/auto-gen-types-no-plugin/index.d.ts
- packages/db/test/fixtures/auto-gen-types-no-plugin/index.test-d.ts
- packages/db/test/fixtures/auto-gen-types-no-plugin/migrations/001.do.sql
- packages/db/test/fixtures/auto-gen-types-no-plugin/package.json
- packages/db/test/fixtures/auto-gen-types-no-plugin/platformatic.db.json
- packages/db/test/fixtures/auto-gen-types/platformatic.db.json
Fixes https://github.com/platformatic/platformatic/issues/268
> fix gen-types when config.plugin is not defined

- packages/sql-mapper/lib/entity.js
- packages/sql-mapper/test/where.test.js
> Make sure eq and neq can check for NULL as well

- packages/db-authorization/lib/webhook.js
- packages/db-authorization/test/webhook.test.js
Fixes: https://github.com/platformatic/platformatic/issues/294
> Webhook authentication issue if the body is not present in request

- .github/workflows/ci.yml
> Ignore scripts while running pnpm fetch

- packages/service/.taprc
- packages/service/index.js
- packages/service/lib/start.mjs
- packages/service/test/cli/helper.mjs
- packages/service/test/cli/watch.test.mjs
Fixes https://github.com/platformatic/platformatic/issues/283
> Do not crash if config is reloaded

- packages/authenticate/package.json
- packages/db-core/package.json
- packages/db-dashboard/package.json
- packages/db-ra-data-rest/package.json
- packages/db/package.json
- packages/service/package.json
- packages/sql-events/package.json
- packages/sql-graphql/package.json
- packages/sql-json-schema-mapper/package.json
- packages/sql-openapi/package.json
This made the links from npm not work properly.
> fix typo in repo urls

- packages/sql-graphql/lib/entity-to-type.js
- packages/sql-graphql/test/datatypes.test.js
- packages/sql-graphql/test/helper.js
- packages/sql-json-schema-mapper/index.js
- packages/sql-json-schema-mapper/test/helper.js
- packages/sql-json-schema-mapper/test/simple.test.js
- packages/sql-mapper/lib/entity.js
- packages/sql-mapper/lib/queries/mysql-shared.js
- packages/sql-mapper/lib/queries/pg.js
- packages/sql-mapper/test/entity.test.js
- packages/sql-mapper/test/helper.js
- packages/sql-openapi/lib/entity-to-routes.js
> fix: add enum values support in schema

- packages/db-dashboard/src/App.jsx
- packages/db-dashboard/src/components/Layout.jsx
- packages/db-dashboard/src/components/Navbar.jsx
- packages/db-dashboard/src/components/Sidebar.jsx
- packages/db-dashboard/src/elements/Title.jsx
- packages/db-dashboard/src/pages/Home.jsx
Fixes https://github.com/platformatic/platformatic/issues/228
> fix: add missing import React in db-dashboard

- packages/db-authorization/index.js
- packages/db-authorization/package.json
- packages/db-authorization/test/validation.test.js
- packages/db/test/helper.js
- packages/db/test/start-and-stop.test.js
- pnpm-lock.yaml
- renovate.json
> Validate authorization config rules

- .github/workflows/ci.yml
- packages/sql-graphql/lib/relationship.js
> Fails the CI job if linting fails / fix linting

- docs/reference/sql-mapper/entities/api.md
- docs/reference/sql-rest/api.md
- packages/db-authorization/index.js
- packages/db-authorization/test/simple-rest.test.js
- packages/db-authorization/test/skip-authorization.test.js
- packages/db-ra-data-rest/src/index.js
- packages/db-ra-data-rest/src/index.spec.js
- packages/db/tap-snapshots/test/cli/schema.test.mjs.test.cjs
- packages/sql-mapper/lib/entity.js
- packages/sql-mapper/lib/queries/mysql-shared.js
- packages/sql-mapper/lib/queries/pg.js
- packages/sql-mapper/lib/queries/shared.js
- packages/sql-mapper/lib/queries/sqlite.js
- packages/sql-mapper/test/updateMany.test.js
- packages/sql-openapi/lib/entity-to-routes.js
- packages/sql-openapi/test/tap-snapshots/nested-routes-openapi-recursive.cjs
- packages/sql-openapi/test/tap-snapshots/nested-routes-openapi.cjs
- packages/sql-openapi/test/tap-snapshots/orderby-openapi-1.cjs
- packages/sql-openapi/test/tap-snapshots/simple-openapi-1.cjs
- packages/sql-openapi/test/tap-snapshots/simple-openapi-2.cjs
- packages/sql-openapi/test/tap-snapshots/simple-openapi-4.cjs
- packages/sql-openapi/test/tap-snapshots/updateMany-openapi-1.cjs
- packages/sql-openapi/test/tap-snapshots/where-openapi-1.cjs
- packages/sql-openapi/test/tap-snapshots/where-openapi-2.cjs
- packages/sql-openapi/test/updateMany.test.js
> feat(sql-mapper): implement updateMany function on entity

- packages/db/.taprc
- packages/db/test/cli/gen-types.test.mjs
- packages/db/test/fixtures/no-hotreload.json
- packages/service/lib/schema.js
> Plugin schema additionalProperties: false

- packages/db-dashboard/index.js
- packages/db-dashboard/src/components/metrics/Metrics.jsx
- packages/db-dashboard/src/components/metrics/TotalMetric.jsx
- packages/db-dashboard/src/pages/Home.jsx
- packages/db-dashboard/src/pages/Home.module.css
- pnpm-lock.yaml
It's a Darft because based on https://github.com/platformatic/platformatic/pull/330 which is a WIP. 
This add the (total) metrics on the Dashboard:
> Metrics in dashboard home page

- packages/db-dashboard/index.js
- packages/db-dashboard/src/App.jsx
- packages/db-dashboard/src/components/Navbar.jsx
Fixes https://github.com/platformatic/platformatic/issues/339
> Add catchall route for dashboard

- packages/sql-mapper/lib/queries/sqlite.js
- packages/sql-mapper/test/entity.test.js
> fix: entity insert with explicit PK value

- docs/reference/db/configuration.md
- docs/reference/service/configuration.md
- packages/service/lib/schema.js
- packages/service/test/cli/start.test.mjs
- packages/service/test/fixtures/not-load.js
- packages/service/test/fixtures/not-load.service.json
> Add pluginTimeout to schema, docs, and tests

- packages/db/lib/gen-types.mjs
- packages/db/lib/start.mjs
- packages/db/test/cli/gen-types.test.mjs
> Log messages if there are no tables

- packages/sql-graphql/lib/utils.js
- packages/sql-graphql/test/simple.test.js
> Add support for postgresql jsonb

- docs/reference/db/configuration.md
- docs/reference/db/schema-support.md
- packages/db/lib/schema.js
- packages/sql-mapper/lib/queries/pg.js
- packages/sql-mapper/mapper.js
- packages/sql-mapper/test/schema.test.js
Fixes https://github.com/platformatic/platformatic/issues/356
> Postgres schema support

- packages/db-dashboard/src/App.jsx
I need it to work with:
`pnpm run dashboard:start`
> fix: add import React in dashboard App

- packages/db-dashboard/src/pages/ConfigViewer.jsx
- packages/db-dashboard/src/pages/GQL.jsx
- packages/db-dashboard/src/pages/SwaggerViewer.jsx
Signed-off-by: Riccardo Fiorenza <ricfio.professional@gmail.com>
> fix: add missing import React in dashboard sources

- docs/reference/db/authorization/introduction.md
- packages/db-authorization/index.js
- packages/db-authorization/lib/utils.js
- packages/db-authorization/test/simple.test.js
- packages/db-authorization/test/skip-authorization.test.js
Fixes: https://github.com/platformatic/platformatic/issues/345
> Disable authorization checks if no `ctx` is passed

- packages/db-dashboard/package.json
- pnpm-lock.yaml
Fixes: https://github.com/platformatic/platformatic/issues/371
> Dashboard dependency fix

- docs/guides/add-custom-functionality/extend-rest.md
> docs: fix Extend REST API

- docs/reference/db/configuration.md
- docs/reference/sql-graphql/ignore.md
- docs/reference/sql-openapi/ignore.md
- packages/db/lib/schema.js
- packages/sql-graphql/index.js
- packages/sql-graphql/lib/entity-to-type.js
- packages/sql-graphql/test/ignore.test.js
- packages/sql-json-schema-mapper/index.js
- packages/sql-json-schema-mapper/test/simple.test.js
- packages/sql-openapi/index.js
- packages/sql-openapi/lib/entity-to-routes.js
- packages/sql-openapi/lib/many-to-many.js
- packages/sql-openapi/lib/shared.js
- packages/sql-openapi/test/ignore.test.js
> Ignore endpoints

- CONTRIBUTING.md
Running tests locally I encounter some troubles (like tests that were failing without a particular reason why).
I added some points to the docs that helped me solve this.
🙏🏼 Thank you @marcopiraccini for helping me with this!
> Add steps in case of issues running the tests

- packages/cli/cli.js
> Print ASCII art only if no command is specified

- packages/sql-graphql/lib/relationship.js
- packages/sql-graphql/test/nested.test.js
> Remove requirement for foreign keys to have _id suffix

- packages/sql-graphql/lib/entity-to-type.js
- packages/sql-graphql/lib/relationship.js
- packages/sql-graphql/test/fix-428.test.js
> Fetch all relation keys when fetching relations in GraphQL 

- packages/service/index.js
- packages/service/lib/compile.js
> Support npm 9

- docs/reference/db/authorization/introduction.md
- packages/db-authorization/index.js
- packages/db-authorization/test/jwt.test.js
> Setup user on demand

- .gitignore
Signed-off-by: Roberto Bianchi <roberto.bianchi@spendesk.com>
As by title, add a section to exclude IDE folders.
> feat(gitignore): Exclude VS Code folder

- packages/db/index.js
- packages/db/test/admin.test.js
- packages/db/test/config.test.js
- packages/db/test/start-and-stop.test.js
> Set up the _admin endpoints only when dashboard is enabled

- packages/db/index.js
We use the ConfigManager in other places for config validation
> feat: export ConfigManager in the db package

- docs/getting-started/quick-start-guide.md
Quickstart that uses the new platformatic-creator
> Quickstart changes for platformatic-creator

- docs/reference/sql-mapper/entities/timestamps.md
- packages/db/lib/schema.js
- packages/sql-graphql/test/created_updated_at.test.js
- packages/sql-graphql/test/inserted_updated_at.test.js
- packages/sql-mapper/lib/entity.js
- packages/sql-mapper/mapper.js
- packages/sql-mapper/test/helper.js
- packages/sql-mapper/test/updateMany.test.js
Signed-off-by: Marcelo Mollaj <marcelomollaj@gmail.com>
Fixes #422
TODO:
> Make inserted_at and updated_at customizable

- packages/db/lib/gen-migration.mjs
> Add logging for migration generation

- docs/guides/debug-platformatic-db.md
fixes: [Platformatic DB] Error message when server starts and database doesn't contain tables could be more helpful #452
> docs: add debug platformatic db

- docs/reference/sql-mapper/entities/api.md
- docs/reference/sql-mapper/examples/count.js
Fixes https://github.com/platformatic/platformatic/issues/503
> Added `count` api doc to sql-mapper reference

- packages/db/.taprc
> Increase test timeout in packages/db (for Windows)

- packages/sql-graphql/lib/entity-to-type.js
- packages/sql-graphql/test/nested.test.js
Signed-off-by: Riccardo Fiorenza <ricfio.professional@gmail.com>
> Test fails for 'nested resolver with many nested rows'

- docs/reference/db/api.md
- docs/reference/db/js-api.md
- packages/db/.npmignore
- packages/db/fixtures/programmatic.mjs
> Add docs for starting Platformatic DB programmaticaly

- packages/service/lib/metrics-plugin.js
> Reduce prometheus logs to trace level

- .gitignore
- packages/cli/cli.js
- packages/cli/fixtures/sqlite/migrations/001.do.sql
- packages/cli/fixtures/sqlite/migrations/001.undo.sql
- packages/cli/fixtures/sqlite/platformatic.db.json
- packages/cli/package.json
- packages/cli/test/platformatic.test.js
- packages/db/db.mjs
- packages/db/package.json
- pnpm-lock.yaml
https://github.com/platformatic/platformatic/pull/472 broke all start commands by making them exit with code 0. This PR changes that and adds a test.
> Fix the start command from the CLI

- docs/reference/db/configuration.md
- docs/reference/service/configuration.md
- packages/db/lib/start.mjs
- packages/db/test/cli/compile.test.mjs
- packages/db/test/fixtures/typescript-plugin-nocompile/platformatic.db.json
- packages/db/test/fixtures/typescript-plugin-nocompile/plugin.ts
- packages/db/test/fixtures/typescript-plugin-nocompile/tsconfig.json
- packages/service/lib/schema.js
- packages/service/lib/start.mjs
- packages/service/test/cli/compile.test.mjs
- packages/service/test/cli/gen-schema.test.mjs
- packages/service/test/fixtures/typescript-plugin-nocompile/platformatic.service.json
- packages/service/test/fixtures/typescript-plugin-nocompile/plugin.ts
- packages/service/test/fixtures/typescript-plugin-nocompile/tsconfig.json
Added a `build` config to Typescript (defaults to `true`)  which disables automatic builds:
```
"plugin": {
"path": "plugin.ts",
"typescript": {
"outDir": "dist",
"build": false
}
}
```
It's a draft because adding doc
> Configuration to disable automatic TS build

- packages/db/lib/schema.js
- packages/db/package.json
- packages/db/test/cli/schema.test.mjs
- packages/service/lib/schema.js
- packages/service/package.json
- packages/service/test/cli/gen-schema.test.mjs
- pnpm-lock.yaml
> Fix plugin ref in VSCode

- packages/config/index.js
- packages/config/test/placeholders.test.js
> Escape slashes in env variables

- packages/create-platformatic/src/create-gitignore.mjs
> Ignore .sqlite files for create-platformatic

- packages/db/lib/start.mjs
> Update no entities cli error to have link to docs

- packages/create-platformatic/src/utils.mjs
- packages/create-platformatic/test/utils.test.mjs
Fixes: https://github.com/platformatic/platformatic/issues/557 
Loom: https://www.loom.com/share/58c07e2aa7e2417c924000efc15c1cc3
> Manage error if git or whoami fails in create-platformatic

- packages/create-platformatic/package.json
- packages/create-platformatic/src/index.mjs
- packages/create-platformatic/src/utils.mjs
- packages/create-platformatic/test/utils.test.mjs
- pnpm-lock.yaml
> Feature: show warning on unsupported node.js version

- packages/create-platformatic/src/index.mjs
relates to #551 
[reference conversation](https://github.com/platformatic/platformatic/pull/577#discussion_r1065166623)
Signed-off-by: dan.castillo <dancastillo99@gmail.com>
> Updated warning message for platformatic unsupported node version

- docs/reference/db/configuration.md
- docs/reference/service/configuration.md
- packages/service/index.js
- packages/service/lib/schema.js
- packages/service/test/cors.test.js
> Support multiple CORS origins and regexps

- packages/sql-graphql/test/schema.test.js
- packages/sql-mapper/lib/entity.js
- packages/sql-mapper/mapper.js
Fix for issue https://github.com/platformatic/platformatic/issues/458
> fix(sql-graphql): issue 458

- packages/db/package.json
- packages/service/package.json
- packages/utils/lib/file-watcher.js
- packages/utils/package.json
- pnpm-lock.yaml
> Bump minimatch to v6.0.0

- packages/create-platformatic/src/create-gitignore.mjs
> create-platformatic: add ctags and clinic to gitignore

- packages/db/lib/migrator.mjs
- packages/db/lib/seed.mjs
- packages/db/test/cli/seed.test.mjs
> feat: throw an error on seed command if there are migrations to apply

- .gitignore
- docs/reference/db/introduction.md
- docs/reference/db/programmatic.md
- docs/reference/service/introduction.md
- docs/reference/service/programmatic.md
- packages/db/index.js
- packages/db/lib/config.js
- packages/db/test/fixtures/sqlite/no-logger.json
- packages/db/test/start-and-stop.test.js
- packages/service/index.js
- packages/service/test/config.test.js
> Start Platformatic Service & DB programmatically

- packages/sql-mapper/lib/queries/sqlite.js
- packages/sql-mapper/test/entity.test.js
> fix: fix fields retrieving during sqlite insertOne query

- docs/reference/db/configuration.md
- packages/config/index.js
- packages/db/lib/config.js
- packages/db/lib/schema.js
- packages/db/test/fixtures/name-resolver.db.json
- packages/db/test/fixtures/name-resolver.js
- packages/db/test/fixtures/names.graphql
- packages/db/test/graphql.test.js
> Allow custom schema to be configured

- .gitignore
- CONTRIBUTING.md
> Add ctags instructions

- packages/db-authorization/package.json
- packages/db-core/package.json
- packages/service/package.json
- packages/sql-graphql/index.js
- packages/sql-graphql/package.json
- packages/sql-graphql/test/federation.test.js
- pnpm-lock.yaml
> Update mercurius to v12

- packages/sql-graphql/test/datatypes.test.js
- packages/sql-mapper/test/entity.test.js
- packages/sql-openapi/test/nested.test.js
These appear to be happy little accidents.
> remove 'only' specifier on tests

- docs/guides/securing-platformatic-db.md
> Add guide for using adminSecret

- docs/getting-started/movie-quotes-app-tutorial.md
- docs/reference/service/configuration.md
More info on [Discord](https://discord.com/channels/1011258196905689118/1075782109588885605/1075804885028716596)
> docs(schema): Add tip box

- packages/sql-graphql/lib/relationship.js
- packages/sql-graphql/test/helper.js
- packages/sql-graphql/test/relations.test.js
Ths PR fixes a problem in complex codebases where a loader could wrongly configured due to ordering of the introspection queries.
This was discovered to fix https://github.com/platformatic/unscalable-queue-system/blob/9060fba459ec8b5fade623e5cd52922e643af703/test/cron.js#L125-L137
> Remove wrong loader setup due to introspection order

- docs/reference/sql-mapper/fastify-plugin.md
- packages/sql-mapper/mapper.js
- packages/sql-mapper/test/mapper.test.js
> Add req.platformaticContext

- docs/getting-started/movie-quotes-app-tutorial.md
As suggested by @simonplend on [Discord](https://discord.com/channels/1011258196905689118/1075782109588885605/1077149767882252348), added a code snippet regarding the usage of `typebox` combined with `fastify-type-provider-typebox`.
> docs(schema-type): Movie quotes tutorial update

- packages/sql-mapper/lib/queries/sqlite.js
- packages/sql-mapper/test/entity.test.js
> Fix nested transaction support in insertOne

- packages/create-platformatic/src/db/create-db-cli.mjs
> Use platformatic bin in create-platformatic to support pnpm and yarn

- packages/create-platformatic/src/db/create-db-cli.mjs
- packages/create-platformatic/test/db/create-db.test.mjs
> fix(create-platformatic): create default migrations only when requested (#690)

- docs/getting-started/movie-quotes-app-tutorial.md
Fixes #573.
Related fix: https://github.com/platformatic/tutorial-movie-quotes-app/commit/219d86d992a4135ac4bde204461f0b128495dde3
> Fix createdAt date formatting in Movie Quotes App tutorial

- packages/create-platformatic/src/db/create-db-cli.mjs
- packages/create-platformatic/src/service/create-service-cli.mjs
Fixes: https://github.com/platformatic/platformatic/issues/716
Tested manually, because we don't have tests for the user interactions
> Creates the GH action in the project folder

- packages/db/lib/start.mjs
- packages/service/index.js
- packages/service/lib/compile.js
- packages/service/lib/config.js
- packages/service/lib/start.mjs
- packages/service/lib/utils.js
- packages/service/test/cli/compile.test.mjs
- packages/service/test/utils.test.js
> Start platformatic from another folder with typescript enabled

- packages/db/test/healthcheck.test.js
- packages/service/index.js
> fix:719 - health check full object exposed to fastify/under-pressure

- docs/guides/prisma.md
> docs: add guide on Prisma and Platformatic

- CONTRIBUTING.md
Add command in case of `volta`
> Update CONTRIBUTING instructions

- docs/reference/cli.md
- packages/service/help/schema.txt
This PR close https://github.com/platformatic/platformatic/issues/766
> fix(docs): Issue #766

- packages/db/lib/gen-types.mjs
- packages/db/lib/schema.js
- packages/db/test/cli/gen-types.test.mjs
- packages/db/test/fixtures/auto-gen-types-dir/index.d.ts
- packages/db/test/fixtures/auto-gen-types-dir/index.test-d.ts
- packages/db/test/fixtures/auto-gen-types-dir/migrations/001.do.sql
- packages/db/test/fixtures/auto-gen-types-dir/package.json
- packages/db/test/fixtures/auto-gen-types-dir/platformatic.db.json
- packages/db/test/fixtures/gen-types-dir/index.d.ts
- packages/db/test/fixtures/gen-types-dir/index.test-d.ts
- packages/db/test/fixtures/gen-types-dir/migrations/001.do.sql
- packages/db/test/fixtures/gen-types-dir/package.json
- packages/db/test/fixtures/gen-types-dir/platformatic.db.json
Add a configuration option to specify the directory for the generated types.
fixes #685
> feat: add config option for type generation target directory

- docs/reference/db/configuration.md
- packages/service/lib/schema.js
> Add more Fastify options to the `server` schema

- packages/db/lib/config.js
- packages/db/lib/gen-types.mjs
- packages/service/lib/compile.js
- packages/service/lib/utils.js
- packages/service/test/cli/compile.test.mjs
- packages/service/test/fixtures/typescript-autoload/platformatic.service.json
- packages/service/test/fixtures/typescript-autoload/routes/plugin.ts
- packages/service/test/fixtures/typescript-autoload/tsconfig.json
> Support directories in paths when using plugins

- docs/reference/db/configuration.md
Address this comment discussion [on Discord](https://discord.com/channels/1011258196905689118/1027566961254744084/1085164323468492810)
> Explain how to document authentication on Swagger

- CONTRIBUTING.md
To help others with [similar issues](https://github.com/platformatic/platformatic/issues/754), I created a troubleshooting guideline
> docs(contributing): Add troubleshooting guideline

- docs/reference/db/configuration.md
Fix the configuration accordingly with the latest change (v. 1.18.0)
> Update configuration doc

- docs/reference/service/introduction.md
- packages/service/package.json
Address https://github.com/platformatic/platformatic/issues/793
> feat(issue#793): Standalone PLT service module

- packages/create-platformatic/src/db/create-db-cli.mjs
- packages/create-platformatic/src/service/create-service-cli.mjs
- packages/create-platformatic/src/service/create-service.mjs
- packages/create-platformatic/test/db/create-db.test.mjs
- packages/create-platformatic/test/service/create-service.test.mjs
> Ask the user to overwrite the readme in create-platformatic

- packages/create-platformatic/test/db/create-db.test.mjs
I have no idea why CI is not failing. It's another problem.
> test: fix create-platformatic db test

- packages/create-platformatic/src/service/create-service.mjs
- packages/create-platformatic/test/service/create-service.test.mjs
Added generation of `tsconfig.json` file and `plugins: { typescript: true }` to the config.
Closes #823
> service: added missing information in typescript generator

- .github/workflows/update-platformatic-runtime.yml
Auto-update our cloud on deploy platform
> Auto update cloud runtime on release

- .github/workflows/update-platformatic-runtime.yml
This should fix the automation
> Fix property in GitHub event

- packages/sql-json-schema-mapper/index.js
- packages/sql-json-schema-mapper/test/types.test.js
Fixes https://github.com/platformatic/platformatic/issues/868
> Add back support for enums in typings

- packages/config/test/load.test.js
- packages/metaconfig/test/0.19.0.test.js
- packages/metaconfig/test/fixtures/v0.19.0/db.json
- packages/metaconfig/test/fixtures/v0.19.0/service.json
- packages/metaconfig/versions/0.19.x.js
- packages/metaconfig/versions/0.20.x.js
Unfortunately I broke the auto-update logic.
> Add auto-update to v0.20.x

- .github/workflows/update-platformatic-runtime.yml
> Use GITHUB_ENV rather than GITHUB_OUTPUT

- packages/service/test/autoload.test.js
https://github.com/platformatic/platformatic/actions/runs/4733455163/jobs/8401650917
https://github.com/platformatic/platformatic/actions/runs/4724093504/jobs/8393706080
> test: fix windows CI failing test

- packages/create-platformatic/src/db/create-db.mjs
- packages/create-platformatic/src/service/create-service.mjs
> fix(#891): append .env file if already exists

- packages/config/index.js
- packages/config/test/path-keyword.test.js
- packages/create-platformatic/src/db/create-db.mjs
- packages/create-platformatic/test/db/create-db.test.mjs
> fix(#890): add migrations in config only when wanted

- packages/service/lib/load-config.js
- packages/service/test/cli/start.test.mjs
- packages/service/test/fixtures/custom-port-placeholder.json
This should be the upstream fix for https://github.com/platformatic/machinist/pull/97
> Pass args.allowEnv to configManager

- docs/getting-started/quick-start-guide.md
> fixes for documentation

- pnpm-lock.yaml
> fix for deps

- packages/db/lib/migrator.mjs
> Always set the migrations table to versions if not specified

- packages/sql-mapper/lib/entity.js
- packages/sql-mapper/test/entity.test.js
- packages/sql-mapper/test/no-primary-key.test.js
fixes #545 
cc @mcollina, giving this anotherTRY.👍
the test failures caused unexpected problems earlier, my friend. I will try to resolve them here..
> SQLITE PK allows varchar

- docs/guides/prisma.md
Tiny spelling fix to code snippets in the Prisma Guide documentation.
> Update Prisma Guide docs

- packages/cli/lib/deploy.js
- packages/cli/test/deploy.test.js
Fixes https://github.com/platformatic/platformatic/issues/911
> Automatically apply the cli: prefix if not specified

- packages/service/lib/schema.js
> Adds two properties to https schema config

- CONTRIBUTING.md
- docs/getting-started/quick-start-guide.md
I thought I'd organize [CONTRIBUTING.md](https://github.com/platformatic/platformatic/blob/main/CONTRIBUTING.md) a little bit, but I haven't reviewed it thoroughly.
> Organize and update contributing guides

- packages/db-dashboard/src/components/Header.jsx
- packages/db-dashboard/src/index.css
Hi @marcopiraccini @mcollina 
here PR for the fix on fonts related to fonts (screenshots attached)
> Fixing fonts

- packages/db-authorization/package.json
- pnpm-lock.yaml
> Update fastify-user to 0.1.2

- packages/client-cli/cli.mjs
- packages/client-cli/test/cli-graphql.test.mjs
> Client names must be valid JS identifiers

- packages/db-authorization/index.js
- packages/db-authorization/test/skip-authorization.test.js
> skipAuth: false requires a ctx

- packages/service/lib/root-endpoint/public/index.html
Signed-off-by: Aryan Srivastava <srivastavaaryanalc76@gmail.com>
> Update index.html 

- docs/guides/migrating-fastify-app-to-platformatic-service.md
When this PR is merged, this one should be merged too: https://github.com/platformatic/oss/pull/69
> Add guide: Migrating a Fastify app to Platformatic Service

- packages/db/test/authorization-setup.test.js
- packages/db/test/fixtures/auto-gen-types-dir/plugin.js
- packages/db/test/fixtures/auto-gen-types/plugin.js
- packages/db/test/fixtures/name-resolver.js
- packages/service/lib/gen-schema.js
- packages/service/test/fixtures/nested-directories/modules/inventory/routes/product.js
idk where it came from and why ci is not failing
> chore: fix linting problems

- packages/client-cli/cli.mjs
- packages/client-cli/help/help.txt
- packages/client-cli/test/cli-graphql.test.mjs
- packages/client-cli/test/cli-openapi.test.mjs
Fixes https://github.com/platformatic/platformatic/issues/1092
> Add support for generating a client from a file

- packages/config/test/load.test.js
- packages/create-platformatic/src/db/create-db.mjs
- packages/db/lib/adjust-config.js
- packages/metaconfig/test/from-eighteen-to-will-see.test.js
- packages/metaconfig/versions/from-zero-eighteen-to-will-see.js
> Only add sqlite watch ignores in the config file

- docs/reference/composer/api-modification.md
- packages/composer/lib/composer-hook.js
- packages/composer/test/openapi/fixtures/plugins/hook.js
- packages/composer/test/openapi/fixtures/plugins/multiple-hooks.js
- packages/composer/test/openapi/hooks.test.js
> feat: move composer hook under platformatic namespace

- packages/create-platformatic/src/runtime/create-runtime-cli.mjs
Closes https://github.com/platformatic/platformatic/issues/1118
> The generated service name in runtime must not include spaces

- packages/create-platformatic/src/runtime/create-runtime-cli.mjs
Fixes https://github.com/platformatic/platformatic/issues/1117
> Create-platformatic runtime allows to cusotmize the services folder

- packages/client-cli/cli.mjs
- packages/client-cli/lib/gen-graphql.mjs
- packages/client-cli/lib/gen-openapi.mjs
- packages/client-cli/package.json
- packages/client-cli/test/cli-graphql.test.mjs
- packages/client-cli/test/cli-openapi.test.mjs
- pnpm-lock.yaml
Fixes https://github.com/platformatic/platformatic/issues/1119
> Capitalize the name of the client being generated

- docs/reference/composer/configuration.md
- packages/composer/lib/openapi-composer.js
- packages/composer/lib/openapi-generator.js
- packages/composer/lib/schema.js
- packages/composer/test/openapi/config.test.js
- packages/composer/test/openapi/ignore-routes.test.js
Fixes https://github.com/platformatic/platformatic/issues/1116
> feat: add composer openapi config file support

- packages/client-cli/lib/gen-graphql.mjs
- packages/client-cli/lib/gen-openapi.mjs
- packages/client-cli/lib/utils.mjs
- packages/client-cli/test/cli-graphql.test.mjs
- packages/client-cli/test/cli-openapi.test.mjs
Fixes https://github.com/platformatic/platformatic/issues/1134
> maintain only allowed characters when generating a JS client

- packages/runtime/lib/app.js
- packages/runtime/lib/config.js
- packages/runtime/lib/worker.js
- packages/runtime/package.json
- packages/runtime/test/app.test.js
Fixes https://github.com/platformatic/platformatic/issues/1135
> Do not recreate the ConfigManager at every restart of the runtime

- packages/runtime/test/cli/compile.test.mjs
- packages/runtime/test/cli/watch.test.mjs
In dbd19c851d87db32548b3a8bfa057af93cc99e14, I made a mistake and I didn't have the tmp folders removed. Here is the fix
> Delete tmp folders after the test completes

- packages/sql-mapper/mapper.d.ts
- packages/sql-mapper/test/types/mapper.test-d.ts
> Better types for `EntityHooks`

- packages/db-core/test/basic.test.js
- packages/db/lib/gen-types.mjs
- packages/db/test/cli/gen-types.test.mjs
- packages/db/test/fixtures/gen-types/index.test-d.ts
- packages/sql-mapper/mapper.d.ts
- packages/sql-mapper/test/types/mapper.test-d.ts
Fixes https://github.com/platformatic/platformatic/issues/1268 #1267
> db: make entity hooks typed

- packages/client-cli/cli.mjs
- packages/client-cli/test/cli-openapi-no-implementation.test.mjs
- packages/client-cli/test/runtime.test.mjs
> Always log something when the client is generated + generate it only once

- packages/client-cli/lib/gen-openapi.mjs
- packages/client-cli/test/cli-openapi.test.mjs
- packages/runtime/lib/app.js
> client-cli: set req as optional for OpenAPI routes

- packages/cli/package.json
Fixes [this](https://github.com/platformatic/platformatic/actions/runs/5713011531/job/15477707753?pr=1312)
> adds cc-by-4.0 license to checker

- packages/service/lib/plugins/sandbox-wrapper.js
- packages/service/test/autoload.test.js
> fix: don't overwrite the 'skip-override' plugin option

- packages/create-platformatic/src/db/create-db.mjs
- packages/create-platformatic/src/ghaction.mjs
- packages/create-platformatic/src/service/create-service.mjs
- packages/create-platformatic/test/db/create-db.test.mjs
- packages/create-platformatic/test/ghaction-dynamic.test.mjs
- packages/create-platformatic/test/ghaction-static.test.mjs
- packages/create-platformatic/test/service/create-service.test.mjs
Changes are
- ensure `PLT_TYPESCRIPT` is added to `.env` and in the `env` section of GH action files
- ensure `env` section of GH Action files are shared by all steps
FIxes: #1339
> Better support for typescript

- packages/config/test/load.test.js
- packages/metaconfig/package.json
- packages/metaconfig/test/from-eighteen-to-will-see.test.js
- packages/metaconfig/versions/from-zero-eighteen-to-will-see.js
- pnpm-lock.yaml
> Upgrade to the latest patch version

- packages/client/index.d.ts
- packages/client/index.test-d.ts
- packages/client/package.json
- pnpm-lock.yaml
Add type definition and tests for `client-cli`
> feat(client-cli): Main type definition

- docs/reference/cli.md
- packages/cli/help/compile.txt
- packages/cli/help/deploy.txt
- packages/cli/help/gh.txt
- packages/cli/help/help.txt
- packages/cli/help/start.txt
- packages/cli/help/upgrade.txt
- packages/client-cli/help/help.txt
- packages/composer/help/start.txt
- packages/db/help/compile.txt
- packages/db/help/migrations apply.txt
- packages/db/help/migrations create.txt
- packages/db/help/schema.txt
- packages/db/help/seed.txt
- packages/db/help/start.txt
- packages/db/help/types.txt
- packages/frontend-template/help/help.txt
- packages/frontend-template/help/open-api-server-error.txt
- packages/frontend-template/help/open-api-server-no-200.txt
- packages/service/help/compile.txt
- scripts/gen-cli-doc.mjs
Markdown cleanup and reading comprehension improvements.
> fixes #1358: Platformatic CLI document readability improvements

- packages/client-cli/lib/gen-openapi.mjs
> feat(client-cli): Set unknown instead of any

- packages/deploy-client/index.js
- packages/deploy-client/package.json
- packages/deploy-client/test/deploy-db.test.js
- pnpm-lock.yaml
Fixes https://github.com/platformatic/platformatic/issues/1388
> deploy: do not crash if typescript is missing

- packages/client/index.d.ts
- packages/client/index.js
- packages/client/index.test-d.ts
- packages/client/test/plugin.test.js
Resolve issue https://github.com/platformatic/platformatic/issues/1403#issuecomment-1683585043
> feat(#1403): Add params to getHeaders

- packages/db/lib/gen-types.mjs
A standard linting check will fail otherwise
> Fix syntax of generated types

- docs/reference/db/configuration.md
> update docs to avoid command not found error

- packages/client-cli/lib/gen-openapi.mjs
- packages/client-cli/test/cli-openapi-no-implementation.test.mjs
> feat(client-cli): Export `fullResponse` interface

- docs/reference/composer/configuration.md
- docs/reference/db/configuration.md
- docs/reference/runtime/configuration.md
- docs/reference/service/configuration.md
- packages/telemetry/lib/schema.js
- packages/telemetry/lib/telemetry.js
- packages/telemetry/test/client.test.js
- packages/telemetry/test/telemetry.test.js
Fixes: https://github.com/platformatic/platformatic/issues/1429
> Better skip configuration for telemetry

- packages/telemetry/lib/schema.js
(method is not supposed to be an array)
> Telemetry skip schema fix 

- packages/client-cli/cli.mjs
- packages/client-cli/lib/gen-openapi.mjs
- packages/client-cli/test/cli-openapi.test.mjs
- packages/client-cli/test/fixtures/optional-params-openapi.json
- packages/client-cli/test/get-type.test.mjs
> Correctly set optional parameters in object definition

- docs/reference/db/plugin.md
Same as https://github.com/platformatic/docs/pull/80
> Update typescript config docs

- packages/create-platformatic/src/ghaction.mjs
- packages/create-platformatic/test/ghaction-dynamic.test.mjs
Updated the message in the CLI to reflect the PR Preview naming
> Updated enable PR Previews message

- packages/service/lib/start.js
- packages/service/test/fixtures/request-id.js
- packages/service/test/routes.test.js
> Ensure request id is an UUID

- packages/client-cli/cli.mjs
- packages/client-cli/test/cli-openapi.test.mjs
- packages/composer/test/helper.js
This PR includes also a minor fix in linting.
> Maybe fix composer test on Node v20

- docs/guides/add-custom-functionality/raw-sql.md
adding how to run raw SQL quereis directly from plugins to the platformatic db docs,
I'm unsure about the documentation and whether it's clear enough!
Any suggestions would be great and if we need to mention the `@databases/sql` for extra information.
> docs: add how to run raw sql queries from plugins to the docs

- docs/getting-started/movie-quotes-app-tutorial.md
- docs/getting-started/quick-start-guide.md
- docs/guides/prisma.md
- docs/platformatic-cloud/quick-start-guide.md
- packages/create-platformatic/src/composer/README.md
- packages/create-platformatic/src/create-package-json.mjs
- packages/create-platformatic/src/db/README.md
- packages/create-platformatic/src/runtime/README.md
- packages/create-platformatic/src/service/README.md
- packages/create-platformatic/src/utils.mjs
- packages/create-platformatic/test/utils.test.mjs
- packages/frontend-template/test/e2e/fixtures/package.json
~~GitHub wasn't picking up pushes in https://github.com/platformatic/platformatic/pull/1062 or https://github.com/platformatic/platformatic/pull/1064, so opening a new PR.~~
> drop node 19. add node 20 support

- packages/config/lib/store.js
> Improves error message when version mismatch

- packages/runtime/fixtures/monorepo-watch/service1/platformatic.service.json
- packages/runtime/lib/app.js
- packages/runtime/test/api.test.js
Second part of #1500. Please don't merge the PR if CI completelly fails.
> fix: runtime watch option check

- packages/client-cli/lib/gen-graphql.mjs
- packages/client-cli/lib/gen-openapi.mjs
- packages/client-cli/test/cli-openapi-no-implementation.test.mjs
- packages/client-cli/test/cli-openapi.test.mjs
This generates the following:
```ts
import { type FastifyReply, type FastifyPluginAsync } from 'fastify'
declare namespace movies {
export interface Movies {
getMovies(req?: GetMoviesRequest): Promise<Array<GetMoviesResponseOK>>;
createMovie(req?: CreateMovieRequest): Promise<CreateMovieResponseOK>;
updateMovies(req?: UpdateMoviesRequest): Promise<Array<UpdateMoviesResponseOK>>;
getMovieById(req?: GetMovieByIdRequest): Promise<GetMovieByIdResponseOK>;
updateMovie(req?: UpdateMovieRequest): Promise<UpdateMovieResponseOK>;
deleteMovies(req?: DeleteMoviesRequest): Promise<DeleteMoviesResponseOK>;
}
export interface MoviesOptions {
url: string
}
export const movies: MoviesPlugin;
export { movies as default };
export interface FullResponse<T> {
'statusCode': number;
'headers': object;
'body': …
```
> Avoid TS 2309 error in generated client

- packages/client/test/fixtures/validate-response/openapi.json
- packages/frontend-template/index.js
- packages/frontend-template/lib/gen-openapi.mjs
- packages/frontend-template/lib/utils.mjs
- packages/frontend-template/test/fixtures/openapi.json
- packages/frontend-template/test/openapi.test.js
> Generate frontend client from path

- packages/frontend-template/index.js
- packages/frontend-template/test/fixtures/sample/plugin.cjs
- packages/frontend-template/test/openapi.test.js
> Generate frontend client from custom url

- packages/client-cli/lib/openapi-common.mjs
- packages/client-cli/test/cli-openapi.test.mjs
> enable optionalheaders in fullresponse mode

- packages/db/index.js
- packages/db/lib/utils.js
- packages/db/test/cli/migrate.test.mjs
- packages/db/test/fixtures/update-schema-lock/migrations/001.do.sql
- packages/db/test/fixtures/update-schema-lock/platformatic.db.json
> fix: update schema.lock file on app start

- packages/db/lib/schema.js
- packages/db/test/config.test.js
> feat: set db pluginTimeout to 60s by default

- packages/client-cli/test/cli-graphql-no-implementation.test.mjs
- packages/client-cli/test/cli-graphql-variants.test.mjs
- packages/client-cli/test/cli-graphql.test.mjs
- packages/client-cli/test/cli-openapi-no-implementation.test.mjs
- packages/client-cli/test/cli-openapi.test.mjs
- packages/client-cli/test/runtime.test.mjs
- packages/client/index.js
- packages/client/test/plugin-graphql.test.js
- packages/client/test/plugin.test.js
- packages/service/fixtures/hello-client-ts-without-deps/plugin.ts
- packages/service/fixtures/hello-client-ts/plugin.ts
- packages/service/fixtures/hello-client-without-deps/plugin.js
- packages/service/fixtures/hello-client/plugin.js
> Decorate only request with client instance

- packages/create-platformatic/src/composer/create-composer-cli.mjs
- packages/create-platformatic/src/composer/create-composer.mjs
- packages/create-platformatic/src/runtime/create-runtime-cli.mjs
- packages/create-platformatic/test/composer/create-composer.test.mjs
> feat: generate composed services configs

- docs/reference/composer/introduction.md
- docs/reference/db/introduction.md
- docs/reference/runtime/introduction.md
- docs/reference/service/introduction.md
This fixes: https://github.com/platformatic/platformatic/issues/1556
> Remove public beta from doc

- packages/create-platformatic/src/runtime/create-runtime.mjs
One of the latest commit fixed the tests, but broke the actual result.
> Check services dir is absolute

- packages/create-platformatic/src/composer/create-composer-cli.mjs
- packages/create-platformatic/src/composer/create-composer.mjs
- packages/create-platformatic/src/db/create-db-cli.mjs
- packages/create-platformatic/src/db/create-db.mjs
- packages/create-platformatic/src/runtime/create-runtime-cli.mjs
- packages/create-platformatic/src/runtime/create-runtime.mjs
- packages/create-platformatic/src/service/create-service-cli.mjs
- packages/create-platformatic/src/service/create-service.mjs
- packages/create-platformatic/src/utils.mjs
- packages/create-platformatic/test/composer/create-composer.test.mjs
- packages/create-platformatic/test/db/create-db.test.mjs
- packages/create-platformatic/test/runtime/create-runtime.test.mjs
- packages/create-platformatic/test/service/create-service.test.mjs
> feat: ask once for runtime port

- packages/create-platformatic/src/composer/create-composer-cli.mjs
- packages/create-platformatic/src/composer/create-composer.mjs
- packages/create-platformatic/src/create-package-json.mjs
- packages/create-platformatic/test/composer/create-composer.test.mjs
> Add plugins and routes when creating composer

- packages/cli/lib/upgrade.js
- packages/cli/package.json
- packages/db/lib/migrate.mjs
- packages/utils/index.js
- packages/utils/lib/packages.js
- packages/utils/package.json
- packages/utils/test/packages.test.js
- pnpm-lock.yaml
> Fix suggestions for additional packages on migration run

- docs/guides/applications-with-stackables.md
- docs/reference/service/programmatic.md
- packages/config/lib/store.js
- packages/config/test/fixtures/app/platformatic.json
- packages/config/test/store.test.js
This fixes: https://github.com/platformatic/platformatic/issues/1577
> Extends in stackables

- docs/reference/db/logging.md
> adds query logging paragraph to db logging reference

- .github/workflows/ci.yml
- packages/create-platformatic/test/cli/README.md
- packages/create-platformatic/test/cli/composer.test.mjs
- packages/create-platformatic/test/cli/db.test.mjs
- packages/create-platformatic/test/cli/helper.mjs
- packages/create-platformatic/test/cli/runtime.test.cli.mjs
- packages/create-platformatic/test/cli/service.test.mjs
This is a prerequisite for: https://github.com/platformatic/platformatic/issues/1571
> create-platformatic CLI service/composer/runtime tests

- docs/getting-started/architecture.md
This fixes https://github.com/platformatic/platformatic/issues/1559
> Mention cloud on getting started / architecture

- packages/create-platformatic/create-platformatic.mjs
- packages/create-platformatic/src/cli-options.mjs
- packages/create-platformatic/src/composer/create-composer-cli.mjs
- packages/create-platformatic/src/create-git-repository.mjs
- packages/create-platformatic/src/db/create-db-cli.mjs
- packages/create-platformatic/src/db/create-db.mjs
- packages/create-platformatic/src/index.mjs
- packages/create-platformatic/src/runtime/create-runtime-cli.mjs
- packages/create-platformatic/src/service/create-service-cli.mjs
- packages/create-platformatic/test/create-git-repository.test.mjs
Solving https://github.com/platformatic/platformatic/issues/1210
WIP
TODO
> feat: create-platformatic should ask if the user wants to create a git repository

- .github/workflows/ci.yml
- packages/create-platformatic/create-platformatic.mjs
- packages/create-platformatic/package.json
- packages/create-platformatic/src/cli-options.mjs
- packages/create-platformatic/src/composer/create-composer-cli.mjs
- packages/create-platformatic/src/composer/create-composer.mjs
- packages/create-platformatic/src/create-git-repository.mjs
- packages/create-platformatic/src/db/create-db-cli.mjs
- packages/create-platformatic/src/db/create-db.mjs
- packages/create-platformatic/src/index.mjs
- packages/create-platformatic/src/runtime/create-runtime-cli.mjs
- packages/create-platformatic/src/runtime/create-runtime.mjs
- packages/create-platformatic/src/service/create-service-cli.mjs
- packages/create-platformatic/src/service/create-service.mjs
- packages/create-platformatic/test/cli/composer.test.mjs
- packages/create-platformatic/test/cli/db.test.mjs
- packages/create-platformatic/test/cli/runtime.test.mjs
- packages/create-platformatic/test/cli/service.test.mjs
- packages/create-platformatic/test/create-git-repository.test.mjs
> Add CI integration test for git repository on create platformatic

- packages/db/lib/seed.mjs
- packages/db/package.json
- packages/service/index.d.ts
Draft to check CI first
Fixes: #1350
> support typescript when seeding a database

- packages/client/test/telemetry.test.js
- packages/service/index.js
- packages/sql-graphql/index.js
- packages/sql-graphql/lib/telemetry.js
- packages/sql-graphql/package.json
- packages/sql-graphql/test/telemetry.test.js
- packages/telemetry/lib/telemetry.js
- packages/telemetry/test/helper.js
- packages/telemetry/test/internal.test.js
- pnpm-lock.yaml
Fixes: https://github.com/platformatic/platformatic/issues/1507
> Support for GraphQL resolver in opentracing 

- packages/create-platformatic/src/ghaction.mjs
> Add support for workflow dispatch in the generated actions

- packages/composer/lib/fetch-schemas.mjs
- packages/composer/lib/openapi-generator.js
- packages/composer/lib/utils.js
- packages/composer/test/utils.test.js
> Ensure prefix and url are prefixed with slash

- docs/reference/cli.md
- packages/client-cli/help/help.txt
- packages/client-cli/lib/openapi-generator.mjs
> Update type declaration and docs

- packages/client-cli/cli.mjs
- packages/client-cli/test/cli-openapi.test.mjs
> Skip generate .cjs file if in platformatic app

- packages/service/lib/plugins/plugins.js
Remove `console.log` statement
> fix: remove log statement

- docs/reference/runtime/configuration.md
- docs/reference/service/configuration.md
- packages/composer/lib/schema.js
- packages/db/lib/schema.js
- packages/metaconfig/test/1.x.x.test.js
- packages/metaconfig/versions/1.x.x.js
- packages/runtime/lib/build-server.js
- packages/runtime/lib/config.js
- packages/runtime/lib/schema.js
Fixes https://github.com/platformatic/platformatic/issues/1702
> Fix watch docs and force additionalProperties: false to runtime schema

- packages/client-cli/lib/openapi-common.mjs
- packages/client-cli/test/cli-openapi.test.mjs
- packages/client-cli/test/fixtures/openapi.yaml
Thanks @rozzilla for the hint!
> Force camel case name for operations in client generation

- docs/reference/db/authorization/strategies.md
> docs: add docs for addAuthStrategy method

- packages/client/index.js
- packages/client/package.json
- packages/client/test/fixtures/common-parameters-openapi.json
- packages/client/test/fixtures/movies-quotes/openapi.json
- packages/client/test/generateOperationId.test.js
- packages/client/test/openapi.test.js
- pnpm-lock.yaml
Found while working on #1722 
The test on common parameters was to fix a little the coverage.
> Uses camelCase operation id

- packages/runtime/fixtures/dbApp/package.json
- packages/runtime/fixtures/dbAppWithMigrationError/package.json
- packages/runtime/lib/config.js
- packages/runtime/test/config.test.js
...if not present, defaults to `main`
> When runtime wraps a service, get the name from package.json

- packages/authenticate/authenticate.js
- packages/authenticate/lib/login.js
- packages/authenticate/test/login.test.js
- packages/authenticate/test/read-user-api-key.js
- packages/cli/lib/deploy.js
- packages/cli/lib/errors.js
- packages/deploy-client/index.js
- packages/deploy-client/test/deploy-db.test.js
> feat: add deploy with user api key

- packages/client-cli/index.d.ts
- packages/client-cli/lib/errors.mjs
- packages/client-cli/lib/graphql-generator.mjs
> fix(typo): Change error name

- packages/cli/lib/deploy.js
> fix: don't throw if there is no plt config file

- packages/db/snapshots/test/cli/schema2.test.mjs
- packages/sql-openapi/lib/entity-to-routes.js
- packages/sql-openapi/lib/many-to-many.js
- packages/sql-openapi/lib/shared.js
- packages/sql-openapi/test/tap-snapshots/array-openapi-1.cjs
- packages/sql-openapi/test/tap-snapshots/nested-routes-openapi-recursive.cjs
- packages/sql-openapi/test/tap-snapshots/nested-routes-openapi.cjs
- packages/sql-openapi/test/tap-snapshots/orderby-openapi-1.cjs
- packages/sql-openapi/test/tap-snapshots/simple-openapi-1.cjs
- packages/sql-openapi/test/tap-snapshots/simple-openapi-2.cjs
- packages/sql-openapi/test/tap-snapshots/simple-openapi-3.cjs
- packages/sql-openapi/test/tap-snapshots/simple-openapi-4.cjs
- packages/sql-openapi/test/tap-snapshots/updateMany-openapi-1.cjs
- packages/sql-openapi/test/tap-snapshots/where-openapi-1.cjs
- packages/sql-openapi/test/tap-snapshots/where-openapi-2.cjs
- packages/sql-openapi/test/tap-snapshots/where-openapi-3.cjs
> db: Add automatic tags to OpenAPI definitions

- packages/client-cli/test/fixtures/runtime/platformatic.runtime.json
- packages/client-cli/test/runtime.test.mjs
- packages/client/index.js
- packages/client/test/telemetry.test.js
> adds /graphql to client url when calling a graphql client

- docs/getting-started/architecture.md
👋 Just a little dead link fix.
> docs(architecture): dead link to fastify plugin documentation

- docs/guides/seed-a-database.md
- packages/db/lib/seed.mjs
> Update seed function import and docs

- docs/reference/cli.md
- packages/db/help/migrations create.txt
> Removes --name argument from migration create command doc

- packages/create-platformatic/src/cli-options.mjs
- packages/create-platformatic/src/composer/create-composer-cli.mjs
- packages/create-platformatic/src/db/create-db-cli.mjs
- packages/create-platformatic/src/runtime/create-runtime-cli.mjs
- packages/create-platformatic/src/service/create-service-cli.mjs
- packages/create-platformatic/test/cli-options.test.mjs
- packages/create-platformatic/test/cli/composer.test.mjs
- packages/create-platformatic/test/cli/db.test.mjs
- packages/create-platformatic/test/cli/helper.mjs
- packages/create-platformatic/test/cli/runtime.test.mjs
- packages/create-platformatic/test/cli/service.test.mjs
> fix: convert npm install question to a cli flag

- docs/reference/runtime/configuration.md
- docs/reference/service/configuration.md
- packages/config/lib/manager.js
- packages/config/test/fixtures/placeholder-namespace.json
- packages/config/test/load-config.test.js
> feat: allow to use wildcard to set own environment variable placeholders

- docs/guides/environment-variables.md
Fixes https://github.com/platformatic/platformatic/issues/1659
Fixes https://github.com/platformatic/platformatic/issues/1808
> Add Guide on how to use Env variables

- packages/config/lib/load-config.js
- packages/config/lib/manager.js
- packages/config/test/load.test.js
- packages/runtime/fixtures/typescript-no-env/platformatic.runtime.json
- packages/runtime/fixtures/typescript-no-env/services/composer/platformatic.composer.json
- packages/runtime/fixtures/typescript-no-env/services/movies/global.d.ts
- packages/runtime/fixtures/typescript-no-env/services/movies/migrations/001.do.sql
- packages/runtime/fixtures/typescript-no-env/services/movies/migrations/001.undo.sql
- packages/runtime/fixtures/typescript-no-env/services/movies/platformatic.db.json
- packages/runtime/fixtures/typescript-no-env/services/movies/plugin.ts
- packages/runtime/fixtures/typescript-no-env/services/movies/tsconfig.json
- packages/runtime/fixtures/typescript-no-env/services/movies/types/Movie.d.ts
- packages/runtime/fixtures/typescript-no-env/services/movies/types/index.d.ts
- packages/runtime/fixtures/typescript-no-env/services/titles/client/client.d.ts
- packages/runtime/fixtures/typescript-no-env/services/titles/client/client.openapi.json
- packages/runtime/fixtures/typescript-no-env/services/titles/client/package.json
- packages/runtime/fixtures/typescript-no-env/services/titles/platformatic.service.json
- packages/runtime/fixtures/typescript-no-env/services/titles/plugins/example.ts
- packages/runtime/fixtures/typescript-no-env/services/titles/routes/root.ts
- packages/runtime/fixtures/typescript-no-env/services/titles/tsconfig.json
- packages/runtime/lib/compile.js
- packages/runtime/lib/load-config.js
- packages/runtime/test/cli/compile.test.mjs
fixes: https://github.com/platformatic/platformatic/issues/1822
> fix: compile works even with no env variables 

- packages/service/index.js
- packages/service/lib/plugins/plugins.js
- packages/service/test/load-plugin.test.js
Fixes https://github.com/platformatic/platformatic/issues/1835
> Do not compile plugins if there are no paths

- packages/db/lib/generator/db-generator.js
- packages/db/test/generator.test.js
- packages/generators/lib/base-generator.d.ts
- packages/generators/lib/base-generator.js
- packages/runtime/lib/generator/runtime-generator.js
- packages/service/lib/generator/service-generator.js
- packages/service/test/generator.test.js
Let's try with the service first, then will add a similar PR for db and composer
Refs: #1839
> Support config fields (getter/setter)

- packages/composer/lib/generator/composer-generator.d.ts
- packages/composer/lib/generator/composer-generator.js
- packages/composer/package.json
- packages/composer/test/generator.test.js
- packages/generators/index.d.ts
- packages/generators/lib/base-generator.js
- packages/generators/lib/create-gitignore.js
- packages/generators/test/base-generator.test.js
- packages/runtime/lib/generator/runtime-generator.js
- packages/runtime/package.json
- packages/runtime/test/generator.test.js
- pnpm-lock.yaml
> adds composer generator

- packages/generators/lib/base-generator.d.ts
- packages/generators/lib/base-generator.js
- packages/generators/lib/errors.js
- packages/generators/lib/utils.d.ts
- packages/generators/lib/utils.js
- packages/generators/test/base-generator.test.js
- packages/generators/test/utils.test.js
- packages/service/lib/generator/service-generator.js
- packages/service/test/generator.test.js
> support fastify plugins in service generator

- packages/runtime/lib/generator/runtime-generator.js
- packages/runtime/test/generator.test.js
> Sets typescript value in services

- packages/runtime/lib/generator/runtime-generator.d.ts
- packages/runtime/lib/generator/runtime-generator.js
- packages/runtime/test/generator.test.js
> Adds logLevel as part of the runtime config

- packages/runtime/index.d.ts
- packages/runtime/lib/generator/runtime-generator.d.ts
> Adds simple types for runtime

- .github/workflows/ci.yml
- packages/composer/index.js
- packages/composer/test/generator.test.js
- packages/composer/test/runner.js
- packages/generators/test/runner.js
- packages/service/test/runner.js
Fixes https://github.com/platformatic/platformatic/issues/1884
> Always fail on failed tests

- packages/composer/lib/generator/composer-generator.d.ts
- packages/composer/lib/generator/composer-generator.js
- packages/composer/test/generator.test.js
- packages/db/lib/generator/db-generator.js
- packages/db/test/generator.test.js
- packages/generators/lib/base-generator.js
- packages/generators/lib/utils.d.ts
- packages/generators/lib/utils.js
- packages/generators/test/utils.test.js
- packages/runtime/lib/generator/runtime-generator.js
- packages/runtime/test/generator.test.js
- packages/service/lib/generator/service-generator.d.ts
- packages/service/lib/generator/service-generator.js
- packages/service/test/generator.test.js
- service dependencies added with `addPackage` are added to runtime's `package.json`
- plugins options can be saved both as raw value and as env varaibles
> Adds support for packages with env variable name

- packages/service/lib/compile.js
- packages/service/lib/plugins/openapi.js
- packages/service/test/openapi.test.js
> Actually support openapi prefix option

- packages/composer/lib/generator/composer-generator.js
- packages/db/lib/generator/db-generator.js
- packages/db/test/generator.test.js
- packages/generators/lib/base-generator.js
- packages/generators/test/base-generator.test.js
- packages/service/lib/generator/service-generator.js
> Move addPackages implementation in base generator

- docs/reference/composer/configuration.md
- docs/reference/db/configuration.md
- docs/reference/runtime/configuration.md
- docs/reference/service/configuration.md
- packages/config/lib/manager.js
- packages/config/test/plugin.test.js
This is necessary for https://github.com/platformatic/platformatic/issues/1895
> PLT_SERVICE_ROOT support in service config

- packages/db/config.d.ts
- packages/db/lib/schema.js
This PR doesn't have tests bc it already fixes some failing tests.
Fixed #1925
> fix: add db openapi prefix option

- packages/client-cli/index.d.ts
- packages/client-cli/lib/errors.mjs
- packages/client-cli/lib/openapi-common.mjs
- packages/client-cli/test/cli-openapi-no-implementation.test.mjs
- packages/client-cli/test/cli-openapi.test.mjs
- packages/client-cli/test/frontend-openapi.test.mjs
- packages/client-cli/test/get-type.test.mjs
- packages/client-cli/test/write-content.test.mjs
@rozzilla can you take a look at tests and see if there are some other edge cases you may spot?
Fixes: #1775
> improves parsing of openapi responses

- packages/db/index.js
- packages/db/test/authorization-setup.test.js
- packages/db/test/fixtures/auth-in-code.js
> db: load authorization before user plugins

- packages/client-cli/lib/frontend-openapi-generator.mjs
- packages/client-cli/test/frontend-openapi.test.mjs
Addresses #1981 - updated unit tests.
> feat(client-cli): Add return types to generated frontend typescript client

- packages/composer/test/generator.test.js
- packages/db/test/generator.test.js
- packages/generators/lib/base-generator.d.ts
- packages/generators/lib/base-generator.js
- packages/generators/lib/utils.js
- packages/generators/package.json
- packages/generators/test/base-generator.test.js
- packages/runtime/test/generator.test.js
- packages/service/test/generator.test.js
- pnpm-lock.yaml
fixes: https://github.com/platformatic/platformatic/issues/1996
> generator get the plugins version from npm 

- docs/reference/db/configuration.md
- packages/db/config.d.ts
- packages/db/lib/migrator.mjs
- packages/db/lib/schema.js
> Fix postgrator options

- packages/service/lib/root-endpoint/public/index.html
> fix: service openapi page url

- packages/db/index.js
- packages/db/lib/gen-types.mjs
- packages/db/lib/migrate.mjs
- packages/db/test/cli/gen-types.test.mjs
> fix: db types generation

- docs/reference/db/configuration.md
> fix broken links

- packages/client-cli/lib/get-type.mjs
- packages/client-cli/lib/openapi-common.mjs
- packages/client-cli/lib/responses-writer.mjs
- packages/client-cli/test/get-type.test.mjs
- packages/client-cli/test/responses-writer.test.mjs
> support discrimnator object in responses

- docs/reference/service/configuration.md
> Remove dupe documentation

- docs/reference/service/configuration.md
> Remove extra bullet point from documentation

- packages/client-cli/lib/frontend-openapi-generator.mjs
- packages/client-cli/test/frontend-openapi.test.mjs
> fix: frontend client headers generation

- packages/client-cli/cli.mjs
- packages/client-cli/test/runtime.test.mjs
> fix: runtime client name generation

- packages/generators/lib/create-stackable-cli.js
- packages/generators/lib/create-stackable-files.js
- packages/generators/lib/stackable-generator.js
> feat: update stackable generator cli

- packages/generators/lib/create-stackable-files.js
> fix: use function for the transformConfig param

- packages/composer/lib/generator/composer-generator.js
- packages/composer/test/generator.test.js
- packages/db/lib/generator/db-generator.js
- packages/db/test/generator.test.js
- packages/runtime/test/generator.test.js
- packages/service/lib/generator/service-generator.js
- packages/service/package.json
- packages/service/test/generator.test.js
> feat: add PLT_TYPESCRIPT env var

- packages/client-cli/lib/openapi-common.mjs
- packages/client-cli/test/cli-openapi.test.mjs
- packages/client-cli/test/fixtures/requestbody-as-array-openapi.json
> Support request body as array

- packages/client-cli/lib/frontend-openapi-generator.mjs
- packages/client-cli/test/fixtures/wildcard-in-path-openapi.json
- packages/client-cli/test/frontend-openapi.test.mjs
> Support special characters in path params

- packages/config/lib/manager.js
- packages/runtime/fixtures/configs/monorepo-hotreload.json
- packages/runtime/lib/app.js
- packages/runtime/package.json
- packages/runtime/test/cli/do-not-crash-on-bad-config.test.mjs
- packages/runtime/test/cli/do-not-crash-on-syntax-error.test.mjs
- packages/runtime/test/cli/helper.mjs
- pnpm-lock.yaml
> Do not crash on syntax error and bad config reloads

- packages/client-cli/lib/frontend-openapi-generator.mjs
- packages/client-cli/test/fixtures/empty-responses-openapi.json
- packages/client-cli/test/frontend-openapi.test.mjs
> Do not add headers in frontend get request

- docs/getting-started/quick-start-guide.md
> fix a quick typo. sqlite3 is not the only db this supports

- packages/control/lib/runtime-api-client.js
- packages/runtime/lib/management-api.js
- packages/runtime/test/management-api/config.test.js
- packages/runtime/test/management-api/env.test.js
- packages/runtime/test/management-api/inject.test.js
- packages/runtime/test/management-api/logs.test.js
- packages/runtime/test/management-api/metadata.test.js
- packages/runtime/test/management-api/metrics.test.js
- packages/runtime/test/management-api/reload.test.js
- packages/runtime/test/management-api/service-config.test.js
- packages/runtime/test/management-api/service-details.test.js
- packages/runtime/test/management-api/start-service.test.js
- packages/runtime/test/management-api/stop-service.test.js
- packages/runtime/test/management-api/stop.test.js
- packages/runtime/test/management-api/topology.test.js
> feat: add v1 prefix to the management api

- packages/client-cli/lib/frontend-openapi-generator.mjs
- packages/client-cli/lib/utils.mjs
- packages/client-cli/test/frontend-openapi.test.mjs
- packages/client-cli/test/utils.test.mjs
> Frontend client generator understands json 200 responses

- docs/reference/runtime/configuration.md
> Fix environment variable placeholder links.

- docs/getting-started/new-api-project-instructions.md
- docs/getting-started/quick-start-guide.md
> Updating the quick-start docs

- packages/client-cli/lib/responses-writer.mjs
> Pass full spec on response writer

- docs/reference/composer/configuration.md
> Fix a broken URL#fragment.

- docs/getting-started/architecture.md
> Fix a small typo

- packages/control/lib/ps.js
> Modify table alignment

- packages/runtime/lib/generator/runtime-generator.js
- packages/runtime/test/generator.test.js
Changes in the Runtime Generator..minor fixes
fixes #2244
> Add support for runtime name in the Runtime Generator

- packages/generators/lib/base-generator.js
- packages/generators/test/base-generator.test.js
> Add service name to package.json

- packages/client-cli/help/help.txt
Closes https://github.com/platformatic/platformatic/issues/2250
> Add client help for `--types-only`

- packages/generators/lib/base-generator.js
- packages/runtime/lib/generator/runtime-generator.js
Fixes https://github.com/platformatic/platformatic/issues/2262
> Use borp for running tests

- packages/runtime/lib/worker.js
> feat: change runtime log file mode

- docs/getting-started/architecture.md
From https://github.com/platformatic/docs/pull/105
> fix: broken link to mercurius

- packages/runtime/lib/api.js
- packages/runtime/lib/errors.js
- packages/runtime/test/api/fail.2.test.js
- packages/runtime/test/api/stop.2.test.js
> List all services on error (service not found)

- packages/composer/lib/openapi.js
- packages/composer/lib/proxy.js
- packages/composer/test/proxy.test.js
> fix: composer proxy routes hiding

- packages/generators/lib/base-generator.js
- packages/runtime/lib/generator/runtime-generator.js
- packages/runtime/lib/utils.js
- packages/runtime/package.json
- packages/runtime/test/helpers.js
- packages/runtime/test/update.test.js
- packages/runtime/test/utils.test.js
- pnpm-lock.yaml
Refs: https://github.com/platformatic/meraki/pull/382
> Handle plugin differences when updating a runtime

- packages/runtime/test/update.test.js
Refs: https://github.com/platformatic/meraki/pull/382
> Adds test to ensure correct plugin management in runtime update

- docs/reference/service/configuration.md
- packages/control/test/config.test.mjs
- packages/control/test/fixtures/runtime-1/services/service-1/platformatic.json
- packages/control/test/fixtures/runtime-1/services/service-2/platformatic.json
- packages/control/test/fixtures/runtime-2/services/service-1/platformatic.json
- packages/runtime/fixtures/management-api/services/service-1/platformatic.json
- packages/runtime/fixtures/management-api/services/service-2/platformatic.json
- packages/runtime/lib/app.js
- packages/runtime/test/api/service-config.test.js
- packages/runtime/test/management-api/metrics.test.js
- packages/runtime/test/management-api/service-config.test.js
- packages/service/lib/plugins/metrics.js
- packages/service/lib/schema.js
- packages/service/test/metrics.test.js
> feat: add metrics server hide option

- packages/runtime/lib/app.js
- packages/runtime/test/api/metrics.test.js
- packages/service/lib/plugins/metrics.js
> fix: stream runtime metrics after hot reload

- packages/runtime/lib/generator/runtime-generator.js
- packages/runtime/test/update.test.js
Refs: https://github.com/platformatic/meraki/issues/443
> Fix clieaning env vars on runtime update

- packages/client-cli/lib/openapi-common.mjs
- packages/client-cli/test/cli-openapi.test.mjs
- packages/client-cli/test/fixtures/requestbody-and-parameters-openapi.json
- packages/client-cli/test/runtime.test.mjs
- packages/generators/test/base-generator.test.js
Handles correctly arrays and some other edge cases
Fixes: #2324
> Better handling of body parser

- .github/workflows/ci.yml
See: https://github.com/actions/runner-images/issues/9557
> ci: update docker compose from v1 to v2

- packages/runtime/lib/api.js
- packages/runtime/lib/app.js
- packages/runtime/test/app.test.js
- pnpm-lock.yaml
> fix: start runtime race condition

- packages/cli/fixtures/runtime-upgrade/platformatic.json
- packages/cli/fixtures/runtime-upgrade/services/piquant-combat/.gitignore
- packages/cli/fixtures/runtime-upgrade/services/piquant-combat/global.d.ts
- packages/cli/fixtures/runtime-upgrade/services/piquant-combat/migrations/001.do.sql
- packages/cli/fixtures/runtime-upgrade/services/piquant-combat/migrations/001.undo.sql
- packages/cli/fixtures/runtime-upgrade/services/piquant-combat/platformatic.json
- packages/cli/fixtures/runtime-upgrade/services/piquant-combat/plugins/example.ts
- packages/cli/fixtures/runtime-upgrade/services/piquant-combat/routes/root.ts
- packages/cli/fixtures/runtime-upgrade/services/piquant-combat/schema.lock
- packages/cli/fixtures/runtime-upgrade/services/piquant-combat/test/helper.ts
- packages/cli/fixtures/runtime-upgrade/services/piquant-combat/test/plugins/example.test.ts
- packages/cli/fixtures/runtime-upgrade/services/piquant-combat/test/routes/movies.test.ts
- packages/cli/fixtures/runtime-upgrade/services/piquant-combat/test/routes/root.test.ts
- packages/cli/fixtures/runtime-upgrade/services/piquant-combat/tsconfig.json
- packages/cli/fixtures/runtime-upgrade/services/piquant-combat/types/Movie.d.ts
- packages/cli/fixtures/runtime-upgrade/services/piquant-combat/types/index.d.ts
- packages/cli/lib/upgrade.js
- packages/cli/package.json
- packages/cli/test/upgrade.test.js
- packages/config/lib/manager.js
- packages/config/test/load.test.js
- packages/runtime/lib/config.js
- packages/runtime/lib/schema.js
- packages/runtime/test/config.test.js
- packages/service/lib/openapi-schema-defs.js
- pnpm-lock.yaml
Fixes https://github.com/platformatic/platformatic/issues/2341
> Fix updating a runtime

- docs/reference/sql-mapper/entities/api.md
Fixed the table error and cleared it all up
> fixed the table

- docs/reference/cli.md
- packages/cli/cli.js
- packages/cli/help/inject.txt
- packages/control/control.js
- packages/control/help/inject.txt
- packages/control/lib/inject.js
- packages/control/test/inject.test.mjs
- packages/runtime/lib/management-api.js
> feat: add plt inject verbose option

- packages/client-cli/lib/frontend-openapi-generator.mjs
- packages/client-cli/lib/openapi-common.mjs
- packages/client-cli/test/cli-openapi.test.mjs
- packages/client-cli/test/expected-generated-code/multiple-responses-movies.ts
- packages/client-cli/test/frontend-openapi.test.mjs
- packages/frontend-template/src/App.tsx
> Force full response if empty response object is found in OpenAPI spec

- docs/FAQs.md
- docs/guides/movie-quotes-app-tutorial.md
- packages/frontend-template/README.md
- packages/frontend-template/src/App.tsx
updated the new link for the Platformatic CLI
> updated the new link for the plt cli

- docs/service/overview.md
Fixed a linking issue on the Service docs to include intro
> Updated the Service docs to include intro

- packages/runtime/lib/api-client.js
- packages/runtime/lib/errors.js
- packages/runtime/lib/start.js
- packages/runtime/test/api/fail.4.test.js
- packages/runtime/test/cli/restart.test.mjs
Fixes #2422 
Fixes https://github.com/platformatic/platformatic/issues/2417
> runtime: do not restart on failed startup

- README.md
- docs/guides/migrating-fastify-app-to-platformatic-service.md
- docs/runtime/configuration.md
- docs/service/overview.md
> updated the links to solve for issue 2405

- docs/guides/use-env-with-platformatic.md
- docs/sidebars.js
I added a guide in the guides section of the docs for how to use env in a Platformatic application.
> added a guide for using env in plt apps

- packages/scalar-theme/static/theme.css
> fix: remove broken rule from scalar theme

- packages/runtime/lib/management-api.js
Small refactoring I need to reuse the code in zio.
> refactor: create management api plugin

- packages/sql-mapper/lib/entity.js
- packages/sql-mapper/lib/errors.js
- packages/sql-mapper/test/updateMany.test.js
> (sql-mapper): throw an error if updateMany misses the where clause

- docs/db/configuration.md
- docs/getting-started/new-api-project-instructions.md
- docs/getting-started/quick-start-guide.md
Restructured and rewrote certain sections of the get started guide
> Docs rewrite get started

- docs/composer/configuration.md
- docs/db/configuration.md
- docs/guides/applications-with-stackables.md
- docs/guides/environment-variables.md
- docs/runtime/configuration.md
- docs/service/configuration.md
- docs/service/programmatic.md
- packages/composer/index.js
- packages/config/index.d.ts
- packages/config/lib/load-config.js
- packages/config/lib/manager.js
- packages/config/lib/store.js
- packages/config/test/fixtures/stackable-upgrade/foo.js
- packages/config/test/index.test.js
- packages/config/test/load-config.test.js
- packages/config/test/load.test.js
- packages/config/test/store.test.js
- packages/db/index.js
- packages/db/test/cli/env.test.mjs
- packages/generators/lib/create-stackable-files.js
- packages/runtime/lib/config.js
- packages/runtime/test/generator.test.js
- packages/service/fixtures/acme-base-ts/src/lib/index.ts
- packages/service/fixtures/acme-base/index.js
- packages/service/index.js
- packages/service/test/cli/start.1.test.mjs
> feat: drop allowed env vars

- packages/generators/index.d.ts
- packages/generators/index.test-d.ts
> Expose generatePlugins in generators types

- docs/db/configuration.md
- docs/db/logging.md
- docs/db/migrations.md
- docs/db/overview.md
- docs/db/plugin.md
- docs/db/programmatic.md
- docs/db/schema-support.md
- docs/getting-started/issues.md
Restructuring the `@platformatic-db` docs intro page. I also created an issues component to be used on all the pages as a placeholder until a feedback button is added.
> updated the intro page for PLT db

- docs/db/authorization/overview.md
I updated the Platformatic db Authorization overview page
> updated the @db auth docs

- docs/db/authorization/strategies.md
Updated the strategies section of the DB docs. Talking to HOD on new designs for the images in this page.
> updated the strategies section of the platforrmatic DB docs

- docs/db/authorization/rules.md
- docs/db/authorization/user-roles-metadata.md
- docs/db/logging.md
- docs/db/plugin.md
- docs/db/programmatic.md
- docs/db/schema-support.md
- docs/guides/use-env-with-platformatic.md
Updated the roles section of the DB authorization docs.
> updated user roles and metdata docs

- docs/runtime/overview.md
Updated the runtime overview page to improve readability.
> updated the runtime overview page

- docs/Overview.md
- docs/runtime/configuration.md
- docs/runtime/overview.md
- docs/runtime/programmatic.md
Updated the Runtime docs section
> Runtime docs update

- CONTRIBUTING.md
- README.md
- docs/FAQs.md
- packages/cli/README.md
- packages/client-cli/README.md
- packages/client/README.md
- packages/db/README.md
- packages/runtime/README.md
Updated readmes with new URLs for the docs, added new support messages, and added new FAQs based on questions from Support
> updated urls, added new support message for readmes and updated the faq

- packages/generators/lib/base-generator.js
- packages/generators/test/base-generator.test.js
- packages/generators/test/fixtures/sample-runtime/services/no-plugin/platformatic.json
Fixes: https://github.com/platformatic/platformatic/issues/2574
> fix: update of application with services with no plugins

- CONTRIBUTING.md
Updated the contributing guide to be better streamlined.
> updated the contributing guide

- docs/learn/glossary.md
- docs/runtime/configuration.md
- docs/runtime/programmatic.md
> updated the runtime docs

- docs/packages/sql-openapi/ignore.md
- packages/db/index.js
- packages/db/lib/schema.js
- packages/sql-openapi/index.js
- packages/sql-openapi/lib/entity-to-routes.js
- packages/sql-openapi/lib/many-to-many.js
- packages/sql-openapi/lib/shared.js
- packages/sql-openapi/test/ignore-routes.test.js
> feat: add sql-openapi path ignore

- packages/composer/index.js
- packages/composer/test/config.test.js
Remove duplicated export that is missing a version property.
> fix: composer exports

- packages/composer/lib/root-endpoint/index.js
- packages/composer/package.json
- packages/db/lib/root-endpoint/index.js
- packages/db/package.json
- packages/service/lib/root-endpoint/index.js
- packages/service/package.json
- pnpm-lock.yaml
> Moved from ua-parser-js to my-ua-parser

- packages/sql-mapper/lib/queries/shared.js
- packages/sql-mapper/test/entity.test.js
> fix: sql-mapper insert query

- docs/packages/sql-openapi/overview.md
> update sqltoopenapi docs

- docs/packages/sql-openapi/api.md
- docs/packages/sql-openapi/explicit-include.md
- docs/packages/sql-openapi/ignore.md
- docs/packages/sql-openapi/overview.md
> Sqlopenapi docs update

- packages/service/lib/plugins/graphql.js
- packages/service/test/graphql.test.js
Fixes https://github.com/platformatic/platformatic/issues/2604
> fix: hide /graphql schema from OpenAPI spec

- docs/service/configuration.md
- packages/service/lib/schema.js
- packages/service/test/http2.test.js
Fixes https://github.com/platformatic/platformatic/issues/2689
> Add HTTP/2 config to the service schema

- docs/service/configuration.md
- packages/runtime/test/api/metrics.test.js
- packages/runtime/test/prom-metrics.test.js
- packages/service/lib/plugins/metrics.js
- packages/service/lib/schema.js
- packages/service/package.json
- packages/service/test/metrics.test.js
- pnpm-lock.yaml
It's a draft because doc update is missing.
> Custom labels for service metrics 

- packages/client-cli/test/cli-graphql-no-implementation.test.mjs
- packages/client-cli/test/cli-graphql-variants.test.mjs
- packages/client-cli/test/cli-graphql.test.mjs
- packages/client-cli/test/cli-openapi-full-request-body.test.mjs
- packages/client-cli/test/cli-openapi-no-implementation.test.mjs
- packages/client-cli/test/cli-openapi-url-auth-headers.test.mjs
- packages/db/lib/generator/code-templates.js
- packages/db/test/cli/gen-types.test.mjs
- packages/db/test/cli/seed.test.mjs
- packages/db/test/generator.test.js
- packages/runtime/test/cli/watch/watch.4.test.mjs
- packages/runtime/test/cli/watch/watch.7.test.mjs
- packages/runtime/test/cli/watch/watch.8.test.mjs
- packages/sql-events/test/hooks.test.js
- packages/sql-graphql/test/federation.test.js
- packages/sql-graphql/test/subscription.test.js
Signed-off-by: Leonardo Rossi <leonardo.rossi@gmail.com>
> Removes `t.diagnostic` calls from tests

- packages/runtime/lib/generator/runtime-generator.js
- packages/runtime/test/update.test.js
Needed by https://github.com/platformatic/meraki/issues/808
> fixes bug when updating entrypoint in a runtime

- .npmignore
Fixes https://github.com/platformatic/platformatic/issues/2854
> Fix #2854: added .snapshots to npmignore

- packages/runtime/lib/generator/runtime-generator.js
- packages/runtime/test/generator.test.js
- packages/runtime/test/update.test.js
> Check runtime generator entrypoint on update

- packages/runtime/test/management-api/logs-all.test.js
> test: fix flacky runtime logs test

- docs/learn/beginner/crud-application.md
Fixed issue withe the new API instructions for beginner learn tutorial
Fixes https://github.com/platformatic/docs/issues/147
> updated the learn tutorials to reflect new api instructions

- packages/basic/lib/base.js
- packages/composer/test/stackable/get-graphql-schema.test.js
- packages/composer/test/stackable/get-openapi-schema.test.js
- packages/config/index.d.ts
- packages/db/test/stackable/get-graphql-schema.test.js
- packages/db/test/stackable/get-openapi-schema.test.js
- packages/runtime/lib/worker/app.js
- packages/runtime/lib/worker/default-stackable.js
- packages/runtime/lib/worker/itc.js
- packages/runtime/test/app.test.js
- packages/runtime/test/start/support-logging-using-a-transport.test.js
- packages/service/lib/stackable.js
- packages/service/test/stackable/get-graphql-schema.test.js
- packages/service/test/stackable/get-openapi-schema.test.js
This is a replacement for the `_configOverrides` feature.
> feat: add an updateContext method to the stackable interface

- packages/config/index.d.ts
- packages/db/index.js
- packages/db/lib/stackable.js
- packages/runtime/lib/worker/app.js
- packages/runtime/lib/worker/main.js
- packages/runtime/test/start/support-logging-using-a-transport.test.js
- packages/service/lib/stackable.js
The `isProduction` property will be set when application is run in zio.
> feat: add isProduction property to the stackable context

- .github/workflows/publish-releases.yml
Signed-off-by: Paolo Insogna <paolo@cowtech.it>
> fix: Improve release workflow parameter.

- packages/db/lib/stackable.js
- packages/db/test/stackable/get-meta.test.js
- packages/runtime/lib/errors.js
- packages/runtime/lib/management-api.js
- packages/runtime/lib/runtime.js
- packages/runtime/lib/worker/default-stackable.js
- packages/runtime/lib/worker/itc.js
- packages/runtime/test/api/meta.test.js
- packages/runtime/test/management-api/service-connection-strings.test.js
- packages/sql-mapper/lib/connection-info.js
- packages/sql-mapper/lib/telemetry.js
- packages/sql-mapper/mapper.js
- packages/sql-mapper/test/connection-info.test.js
Management API to get connection strings. 
As @ShogunPanda suggested, the information is on the `db` part of the meta returned by `getMeta` for `DbStackable`
> Connection strings management API

- packages/sql-mapper/mapper.d.ts
- packages/sql-mapper/test/types/mapper.test-d.ts
Fix eq/neq type declaration in sql-mapper WhereCondition interface
Fixes #2989
> Fix sql-mapper eq/neq type declaration

- .github/workflows/backport.yml
You can now use the `backport v1.x` label to trigger a backport. Works same as in Fastify.
> Added backport action

- .github/workflows/ci.yml
- packages/cli/cli.js
- scripts/check-node-version.js
> fix: shows error on using incompatible node version

- packages/runtime/lib/generator/runtime-generator.js
- packages/runtime/test/generator.test.js
make `create-platformatic` work on `wattpm` projects.
> support create-platformatic with a different autoload folder

- packages/service/lib/start.js
- packages/service/test/fixtures/ready-directory/ready-plugin.js
- packages/service/test/routes.test.js
> Do not use `.decorate()` to define start()

- docs/packages/astro/configuration.md
- docs/packages/astro/overview.md
- docs/packages/next/configuration.md
- docs/packages/next/overview.md
- docs/packages/node/configuration.md
- docs/packages/node/overview.md
- docs/packages/remix/configuration.md
- docs/packages/remix/overview.md
- docs/packages/vite/configuration.md
- docs/packages/vite/overview.md
- docs/service/configuration.md
- docs/sidebars.js
- packages/astro/index.js
- packages/vite/index.js
Added documentations for all new Stackables.
> chore: Added packages documentation.

- .github/workflows/ci.yml
- packages/basic/lib/base.js
- packages/basic/lib/errors.js
- packages/basic/lib/utils.js
- packages/basic/lib/worker/child-manager.js
- packages/basic/lib/worker/child-process.js
- packages/basic/lib/worker/child-transport.js
- packages/basic/lib/worker/listeners.js
- packages/basic/test/base.test.js
- packages/basic/test/fixtures/delayed-error.js
- packages/basic/test/fixtures/fetch.js
- packages/basic/test/fixtures/import-non-existing.js
- packages/basic/test/fixtures/imported.js
- packages/basic/test/fixtures/loader.js
- packages/basic/test/fixtures/non-zero-exit.js
- packages/basic/test/fixtures/print-cwd.js
- packages/basic/test/fixtures/server.js
- packages/basic/test/fixtures/unix-socket-server.js
- packages/basic/test/fixtures/wait-for-close.js
- packages/basic/test/helper.js
- packages/basic/test/utils.test.js
- packages/basic/test/worker/child-manager.test.js
- packages/basic/test/worker/child-process.test.js
- packages/basic/test/worker/listeners.test.js
- packages/itc/lib/itc.js
- packages/runtime/lib/runtime.js
> chore: Added tests for @platformatic/basic.

- docs/db/authorization/rules.md
- docs/db/plugin.md
Fixes https://github.com/platformatic/platformatic/issues/3245
> docs: rename references from createPlatformatiContext to platformaticContext

- packages/composer/test/proxy.test.js
- packages/composer/test/proxy/fixtures/service/routes.js
- packages/runtime/package.json
- pnpm-lock.yaml
Fixes https://github.com/platformatic/platformatic/issues/3219
> Fix sending POST through when using proxies

- .gitignore
- packages/astro/index.js
- packages/composer/lib/proxy.js
- packages/composer/test/proxy.test.js
- packages/composer/test/proxy/fixtures/astro/platformatic.json
- packages/composer/test/proxy/fixtures/astro/src/env.d.ts
- packages/composer/test/proxy/fixtures/astro/src/pages/index.astro
> fix: Only redirect by referer if asked to.

- packages/runtime/fixtures/configs/no-services-no-entrypoint.config.json
- packages/runtime/lib/config.js
- packages/runtime/lib/runtime.js
- packages/runtime/test/cli/start/start.5.test.mjs
- packages/runtime/test/entrypoint.test.js
Fixes https://github.com/platformatic/platformatic/issues/3267
> Allow create-platformatic to add a service to an empty watt app

- packages/sql-mapper/mapper.d.ts
- packages/sql-mapper/test/types/mapper.test-d.ts
> add platformatic context option in sql-mapper types definition

- packages/client-cli/lib/get-type.mjs
- packages/client-cli/package.json
- packages/client-cli/test/cli-openapi-additional-properties.test.mjs
- packages/client-cli/test/fixtures/additional-properties-openapi.json
Address https://github.com/platformatic/platformatic/issues/3397
> fix(client-cli): Support Open API records dictionaries

- docs/packages/node/overview.md
> chore: Allow Typescript documentation.

- docs/runtime/_shared-configuration.md
- packages/generators/test/helpers.js
- packages/runtime/config.d.ts
- packages/runtime/fixtures/network-timeout/platformatic.json
- packages/runtime/fixtures/network-timeout/service-1/platformatic.json
- packages/runtime/fixtures/network-timeout/service-1/plugin.js
- packages/runtime/fixtures/network-timeout/service-2/platformatic.json
- packages/runtime/fixtures/network-timeout/service-2/plugin.js
- packages/runtime/lib/runtime.js
- packages/runtime/lib/schema.js
- packages/runtime/lib/worker/main.js
- packages/runtime/schema.json
- packages/runtime/test/api/requests.test.js
- packages/runtime/test/helpers.js
- packages/runtime/test/multiple-workers/networking.test.js
- packages/runtime/test/update.test.js
- packages/wattpm/config.d.ts
- packages/wattpm/schema.json
- packages/wattpm/test/management.test.js
> feat: Make network mesh service timeout configurable.

- docs/client/programmatic.md
- packages/client/index.d.ts
- packages/client/index.js
- packages/client/index.test-d.ts
- packages/client/package.json
- packages/client/test/openapi.test.js
Fixes https://github.com/platformatic/platformatic/issues/2050
> feat(client): Pass custom undici `Dispatcher`

- packages/client-cli/test/cli-openapi-empty-req-res.test.mjs
Add an example on a test for an [edge case](https://github.com/platformatic/platformatic/issues/2397) that's already handled by the current `client` version
> feat(client): Address test case for issue #2397

- packages/client-cli/lib/openapi-generator.mjs
- packages/client-cli/lib/responses-writer.mjs
- packages/client-cli/test/cli-openapi-status-codes-range.test.mjs
- packages/client-cli/test/fixtures/status-codes-range/openapi.json
- packages/client-cli/test/fixtures/status-codes-range/package.json
- packages/client-cli/test/fixtures/status-codes-range/platformatic.service.json
- packages/client-cli/test/fixtures/status-codes-range/plugins/example.js
Address https://github.com/platformatic/platformatic/issues/2213
> feat(client-cli): Support status codes ranges

- docs/cli.md
- packages/client-cli/cli.mjs
- packages/client-cli/lib/frontend-openapi-generator.mjs
- packages/client-cli/test/frontend-openapi.test.mjs
Fixes https://github.com/platformatic/platformatic/issues/2599
> feat(client): warning when forcing fullResponse on frontend

- packages/wattpm/lib/commands/external.js
- packages/wattpm/lib/commands/init.js
- packages/wattpm/lib/utils.js
- packages/wattpm/test/init.test.js
> feat: Do not fail init when directory only contains hidden files.

- packages/runtime/lib/management-api.js
Fixes https://github.com/platformatic/platformatic/issues/3479
> The management API is now stable

- packages/client-cli/lib/get-type.mjs
- packages/client-cli/test/cli-openapi-additional-properties.test.mjs
- packages/client-cli/test/fixtures/additional-properties-openapi.json
Address https://github.com/platformatic/platformatic/issues/2553
> feat(client-cli): Handle additional properties true

- docs/client/overview.md
- packages/client/errors.js
- packages/client/index.d.ts
- packages/client/index.js
- packages/client/index.test-d.ts
- packages/client/test/openapi.2.test.js
- packages/client/test/openapi.test.js
- packages/client/test/plugin.test.js
Address https://github.com/platformatic/platformatic/issues/2628
> feat(client): Standardize error handling

- packages/runtime/lib/runtime.js
- packages/runtime/test/start/custom-environment.test.js
- packages/wattpm/test/execution.test.js
- packages/wattpm/test/fixtures/main/web/main/index.js
> adds env variable for dev mode in worker

- packages/basic/lib/worker/child-manager.js
- packages/runtime/lib/runtime.js
- packages/telemetry/lib/node-telemetry.js
- packages/telemetry/package.json
- pnpm-lock.yaml
no tests added, because it's just a module rename + configure a new instrumentation on otel for node services
> PG instrumentation for nodejs services

- docs/packages/node/overview.md
- packages/basic/lib/base.js
- packages/basic/lib/worker/child-process.js
- packages/basic/test/worker/child-process.test.js
- packages/node/index.js
- packages/node/test/fixtures/node-set-connection-string/package.json
- packages/node/test/fixtures/node-set-connection-string/platformatic.runtime.json
- packages/node/test/fixtures/node-set-connection-string/services/api/index.js
- packages/node/test/fixtures/node-set-connection-string/services/api/package.json
- packages/node/test/fixtures/node-set-connection-string/services/api/platformatic.application.json
- packages/node/test/meta.test.js
This covers also the nodejs services starting with scripts
> Set openapi/graphql schemas and connection string on nodejs services

- packages/wattpm/lib/commands/external.js
Make usage of `single-branch` and `depth` options to make the `git clone` command faster (reference https://git-scm.com/docs/git-clone)
> fix(wattpm): update git command

- docs/runtime/_shared-configuration.md
- jsconfig.json
- packages/runtime/lib/schema.js
- packages/runtime/schema.json
- packages/wattpm/lib/commands/build.js
- packages/wattpm/lib/commands/external.js
- packages/wattpm/schema.json
- packages/wattpm/test/build.test.js
- packages/wattpm/test/resolve.test.js
> feat: Allow custom package manager per service.

- docs/guides/monitoring.md
- packages/astro/index.js
- packages/basic/lib/base.js
- packages/basic/lib/worker/child-manager.js
- packages/basic/lib/worker/child-process.js
- packages/basic/test/base.test.js
- packages/basic/test/fixtures/server.js
- packages/basic/test/fixtures/wait-for-close.js
- packages/basic/test/worker/child-process.test.js
- packages/metrics/index.js
- packages/next/index.js
- packages/next/test/metrics.test.js
- packages/node/index.js
- packages/remix/index.js
- packages/runtime/fixtures/custom-metrics/external/index.mjs
- packages/runtime/fixtures/custom-metrics/external/package.json
- packages/runtime/fixtures/custom-metrics/external/platformatic.json
- packages/runtime/fixtures/custom-metrics/internal/index.mjs
- packages/runtime/fixtures/custom-metrics/internal/package.json
- packages/runtime/fixtures/custom-metrics/internal/platformatic.json
- packages/runtime/fixtures/custom-metrics/platformatic.json
- packages/runtime/fixtures/custom-metrics/service/platformatic.json
- packages/runtime/fixtures/custom-metrics/service/plugin.js
- packages/runtime/lib/worker/app.js
- packages/runtime/lib/worker/default-stackable.js
- packages/runtime/test/multiple-workers/basic.test.js
- packages/runtime/test/multiple-workers/reuse-port.test.js
- packages/runtime/test/prom-metrics.test.js
- packages/service/lib/stackable.js
- packages/vite/index.js
> feat: Support custom metrics.

- package.json
- packages/astro/index.js
- packages/composer/test/proxy.test.js
- packages/remix/index.js
- packages/runtime/lib/config.js
- packages/vite/index.js
- pnpm-lock.yaml
> Fix sigsev

- renovate.json
With this config: `Branch creation - "* 0-6 * * 6,0" in timezone Europe/Rome, Automerge - At any time (no schedule defined)`.
> Renovate schedule to create branch on WE nights

- packages/basic/index.js
- packages/basic/test/helper.js
- packages/runtime/lib/config.js
- packages/vite/test/fixtures/standalone/package.json
Unfortunately https://github.com/platformatic/platformatic/pull/3691 was incomplete and it did not fix Vite. This fixes it.
> Fix vite SIGSEV

- packages/telemetry/NOTICE
- packages/telemetry/lib/node-telemetry.js
- packages/telemetry/lib/telemetry-config.js
- packages/telemetry/package.json
- packages/telemetry/test/helper.js
- packages/telemetry/test/otelserver/README.md
- packages/telemetry/test/otelserver/index.js
- packages/telemetry/test/otelserver/messages.js
- packages/telemetry/test/otelserver/opentelemetry/proto/collector/README.md
- packages/telemetry/test/otelserver/opentelemetry/proto/collector/metrics/v1/metrics_service.proto
- packages/telemetry/test/otelserver/opentelemetry/proto/collector/metrics/v1/metrics_service_http.yaml
- packages/telemetry/test/otelserver/opentelemetry/proto/collector/trace/v1/trace_service.proto
- packages/telemetry/test/otelserver/opentelemetry/proto/collector/trace/v1/trace_service_http.yaml
- packages/telemetry/test/otelserver/opentelemetry/proto/common/v1/common.proto
- packages/telemetry/test/otelserver/opentelemetry/proto/metrics/v1/metrics.proto
- packages/telemetry/test/otelserver/opentelemetry/proto/resource/v1/resource.proto
- packages/telemetry/test/otelserver/opentelemetry/proto/trace/v1/trace.proto
- packages/telemetry/test/runtime-helper.js
- packages/telemetry/test/runtimes.integration.test.js
- packages/telemetry/test/runtimes.test.js
- pnpm-lock.yaml
Integrations tests of application with plt (composer) + node/next services: an OTEL server is started and the fixture configuration is changed to use it. 
Also refactored the tests to not use test helper from `basic`.
Fixes: https://github.com/platformatic/platformatic/issues/3739
> Telemetry integration tests

- packages/basic/lib/worker/child-process.js
- packages/runtime/fixtures/configs/monorepo-with-node.json
- packages/runtime/fixtures/monorepo-with-node/node/server.mjs
- packages/runtime/lib/worker/main.js
- packages/runtime/test/api/logging.test.js
- packages/utils/lib/streams/pino-writable.js
> feat: Added caller information to standard streams.

- .github/workflows/ci.yml
- docs/packages/node/overview.md
- packages/globals/.npmignore
- packages/globals/README.md
- packages/globals/eslint.config.js
- packages/globals/lib/index.d.ts
- packages/globals/lib/index.js
- packages/globals/package.json
- packages/globals/test/index.test.js
- pnpm-lock.yaml
> feat: Added @platformatic/globals package.

- packages/client-cli/test/cli-openapi-no-implementation.test.mjs
- packages/service/lib/compile.js
- packages/service/lib/stackable.js
- packages/service/test/cli/compile-1.test.mjs
- packages/service/test/cli/compile-3.test.mjs
- packages/ts-compiler/compile.js
- packages/ts-compiler/test/compile.test.js
> feat: Throw on failed compilation.

- packages/basic/lib/worker/child-manager.js
- packages/basic/lib/worker/child-process.js
- packages/basic/test/fixtures/fetch.js
- packages/basic/test/fixtures/tcp-wirer.js
- packages/basic/test/helper.js
- packages/basic/test/worker/child-manager.test.js
- packages/basic/test/worker/child-process.test.js
- packages/runtime/fixtures/interceptors-3/platformatic.json
- packages/runtime/fixtures/interceptors-3/services/a/platformatic.json
- packages/runtime/fixtures/interceptors-3/services/a/plugin.js
- packages/runtime/fixtures/interceptors-3/services/b/platformatic.json
- packages/runtime/fixtures/interceptors-3/services/b/plugin.js
- packages/runtime/fixtures/interceptors-3/services/composer/platformatic.json
- packages/runtime/fixtures/interceptors-3/services/node/index.js
- packages/runtime/fixtures/interceptors-3/services/node/package.json
- packages/runtime/fixtures/interceptors-3/services/node/platformatic.json
- packages/runtime/test/interceptors.test.js
> feat: Fetch from child processes via UNIX socket.

- docs/runtime/_shared-configuration.md
- packages/runtime/config.d.ts
- packages/runtime/fixtures/custom-argv/platformatic.json
- packages/runtime/fixtures/custom-argv/services/main/platformatic.json
- packages/runtime/fixtures/custom-argv/services/main/plugin.js
- packages/runtime/lib/runtime.js
- packages/runtime/lib/schema.js
- packages/runtime/schema.json
- packages/runtime/test/config.test.js
- packages/wattpm/config.d.ts
- packages/wattpm/schema.json
> feat: Support arguments for services.

- packages/wattpm/lib/utils.js
- packages/wattpm/test/build.test.js
- packages/wattpm/test/fixtures/update/web/main/watt.json
> fix: Only consider runtime file as project root.

- packages/client-cli/lib/responses-writer.mjs
- packages/client-cli/test/responses-writer.test.mjs
This fixes how we currently handle `204` status codes with the `fullResponse` option. Added specific tests for this behavior.
> fix(client cli): handle 204 with full response

- packages/client-cli/lib/frontend-openapi-generator.mjs
- packages/client-cli/test/expected-generated-code/multiple-responses-movies.ts
- packages/client-cli/test/frontend-openapi.test.mjs
Avoid unnecessary `if` condition on the generated client.
> feat(client cli): simplify response handler logic

- docs/composer/programmatic.md
> fix: doc composer programmatic

- docs/packages/node/_shared-overview.md
- docs/runtime/_shared-configuration.md
- docs/service/configuration.md
- packages/basic/lib/base.js
- packages/config/index.d.ts
- packages/globals/lib/index.d.ts
- packages/runtime/config.d.ts
- packages/runtime/fixtures/prom-server/liveness-custom.json
- packages/runtime/fixtures/prom-server/liveness-disabled.json
- packages/runtime/fixtures/prom-server/platformatic.json
- packages/runtime/fixtures/prom-server/services/main/platformatic.json
- packages/runtime/fixtures/prom-server/services/service-node/index.js
- packages/runtime/fixtures/prom-server/services/service-node/package.json
- packages/runtime/fixtures/prom-server/services/service-node/platformatic.json
- packages/runtime/lib/errors.js
- packages/runtime/lib/prom-server.js
- packages/runtime/lib/runtime.js
- packages/runtime/lib/schema.js
- packages/runtime/lib/worker/default-stackable.js
- packages/runtime/lib/worker/itc.js
- packages/runtime/schema.json
- packages/runtime/test/prom-metrics.test.js
- packages/service/lib/stackable.js
- packages/wattpm/config.d.ts
- packages/wattpm/schema.json
> feat: introduce watt liveness

- docs/client/frontend.md
- packages/client-cli/lib/frontend-openapi-generator.mjs
- packages/client-cli/test/expected-generated-code/multiple-responses-movies.ts
- packages/client-cli/test/frontend-openapi.test.mjs
> fix(client cli): allow to define additional fetch params

- packages/client-cli/lib/frontend-openapi-generator.mjs
- packages/client-cli/test/fixtures/form-data/openapi.json
- packages/client-cli/test/fixtures/form-data/platformatic.db.json
- packages/client-cli/test/fixtures/form-data/plugin.cjs
- packages/client-cli/test/frontend-openapi.test.mjs
> feat(client-cli): handle `FormData`

- docs/guides/k8s-readiness-liveness.md
- docs/packages/node/_shared-overview.md
As titled
I'd like to add a full example, where is the right place?
> doc: readiness and liveness guide

- docs/guides/k8s-readiness-liveness.md
> doc: k8s readiness liveness link to repo example

- packages/client-cli/lib/frontend-openapi-generator.mjs
- packages/client-cli/test/expected-generated-code/multiple-responses-movies.ts
- packages/client-cli/test/frontend-openapi.test.mjs
Reduce the amount of boilerplate code generated for the frontend to enhance its readability during debugging.
> chore(client cli): refactor and cleanup

- packages/basic/lib/worker/child-manager.js
- packages/next/lib/caching/valkey.js
- packages/next/lib/loader.js
- packages/next/test/fixtures/basepath-production/package.json
- packages/next/test/fixtures/basepath-production/platformatic.runtime.json
- packages/next/test/fixtures/basepath-production/services/frontend/next.config.js
- packages/next/test/fixtures/basepath-production/services/frontend/package.json
- packages/next/test/fixtures/basepath-production/services/frontend/platformatic.json
- packages/next/test/fixtures/basepath-production/services/frontend/src/app/layout.js
- packages/next/test/fixtures/basepath-production/services/frontend/src/app/page.js
- packages/next/test/fixtures/basepath-production/services/service/package.json
- packages/next/test/fixtures/basepath-production/services/service/platformatic.json
- packages/next/test/fixtures/basepath-production/services/service/plugin.js
- packages/next/test/miscellaneous.test.js
- pnpm-lock.yaml
> fix: Next.js related minor fixes.

- packages/control/index.d.ts
- packages/control/index.test-d.ts
> chore(control): update metric value type

- .github/workflows/ci.yml
- packages/metrics/index.js
- packages/metrics/test/index.test.js
> fix(metrics): collect metrics for workerid 0

- packages/sql-mapper/lib/entity.js
- packages/sql-mapper/mapper.d.ts
- packages/sql-mapper/test/where.test.js
- Allow pagination to be optionally disabled. This option is available only within the code and is not exposed through the API
Fixes: #2551
> feat(pagination): add option to disable pagination

- packages/wattpm/lib/commands/build.js
- packages/wattpm/test/build.test.js
Fixes https://github.com/platformatic/platformatic/issues/3970
> Fix wattpm update

- packages/basic/lib/base.js
- packages/basic/package.json
- packages/basic/test/base.test.js
Needed for https://github.com/platformatic/watt-admin/issues/65
> feat(basic): allow passing chained commands

- packages/remix/index.js
- packages/remix/test/app.test.js
Closes https://github.com/platformatic/platformatic/issues/3985
> fix: remove remix http custom headers

- docs/watt/reference.md
- packages/wattpm/lib/commands/execution.js
- packages/wattpm/lib/utils.js
- packages/wattpm/test/utils.test.js
> feat(wattpm): add config option

- packages/control/index.d.ts
- packages/control/index.test-d.ts
Add missing types to `@platformatic/control` package
> chore(control): update types

- packages/metrics/index.js
- packages/metrics/package.json
- packages/runtime/package.json
- pnpm-lock.yaml
Unfortunately compiling things on windows might be harder than expected.
> Make thread cpu usuage optional

- packages/astro/index.js
- packages/astro/package.json
- packages/astro/test/compatibility.test.js
- packages/astro/test/fixtures/compatibility/package.json
- packages/astro/test/fixtures/compatibility/platformatic.runtime.json
- packages/astro/test/fixtures/compatibility/services/frontend/package.json
- packages/astro/test/fixtures/compatibility/services/frontend/src/pages/index.astro
- packages/astro/test/fixtures/compatibility/tsconfig.json
- pnpm-lock.yaml
I tried it and didn't find any issues with version 5.
Also read all the breaking changes and didn't find any issues.
Fix issue #3669
> chore(astro): update supportedVersion to 5

- packages/db-authorization/test/admin.test.js
- packages/db/lib/schema.js
- packages/db/schema.json
> UpdateMany db auth rule

- packages/telemetry/lib/node-telemetry.js
- packages/telemetry/lib/pluggable-instrumentations.js
- packages/telemetry/package.json
- packages/telemetry/test/fixtures/express-api-pg/package.json
- packages/telemetry/test/fixtures/express-api-pg/platformatic.json
- pnpm-lock.yaml
...to dev deps in `telemetry` package
> Remove opentelemetry-pg instrumentation from deps

- packages/sql-openapi/lib/shared.js
- packages/sql-openapi/test/updateMany.test.js
- packages/sql-openapi/test/where.test.js
> #3909 - fix null/not null OpenAPI filter

- packages/wattpm/schema.json
Related to https://github.com/rozzilla/watt-poc/pull/3#discussion_r2073545055
> fix(wattpm): add missing https schema values

- packages/client-cli/lib/frontend-openapi-generator.mjs
- packages/client-cli/test/fixtures/delete-no-body/openapi.json
- packages/client-cli/test/fixtures/delete-no-body/platformatic.db.json
- packages/client-cli/test/fixtures/delete-no-body/plugin.cjs
- packages/client-cli/test/frontend-openapi.test.mjs
> fix(client cli): do not pass json type header when body is undefined

- packages/cli/package.json
As titled, see https://github.com/platformatic/platformatic/actions/runs/15412067448/job/43366220960
> fix: licenses list

- packages/composer/lib/proxy.js
- packages/composer/package.json
- pnpm-lock.yaml
Follow up and conclusion of #4098. Tests are in the other PR.
> feat: Use preRewrite callback.

- packages/runtime/lib/start.js
This should resolve some of the latest flakyness
> Try a new port if the error code is EACCESS

- packages/composer/lib/metrics.js
- packages/composer/lib/proxy.js
- packages/composer/package.json
- packages/composer/test/metrics.test.js
- packages/composer/test/proxy.test.js
- pnpm-lock.yaml
> feat(composer): add active ws connections metric

- packages/client-cli/cli.mjs
- packages/client-cli/help/help.txt
- packages/client-cli/test/watt-integration.test.mjs
> feat(client cli): flip props

- docs/guides/profiling-with-watt.md
- docs/reference/watt/cli-commands.md
- docs/sidebars.js
- packages/wattpm/lib/commands/pprof.js
- packages/wattpm/test/pprof.test.js
I've also updated the CLI commands to handle runtime id correctly to better align with other commands.
> Add docs and guides

- packages/runtime/fixtures/delayed-shutdown/index.js
- packages/runtime/fixtures/delayed-shutdown/platformatic.runtime.json
- packages/runtime/fixtures/delayed-shutdown/platformatic.service.json
- packages/runtime/fixtures/delayed-shutdown/start-and-stop.js
- packages/runtime/lib/runtime.js
- packages/runtime/lib/start.js
- packages/runtime/test/api/stop.4.test.js
- packages/runtime/test/unified-api.test.js
> fix: Correctly handle graceful shutdowns.

- packages/next/lib/capability.js
> fix: Disable handled error mode in Next.

- packages/basic/lib/capability.js
- packages/basic/lib/worker/child-process.js
- packages/basic/test/fixtures/server.js
- packages/control/test/runtime-api.test.js
- packages/gateway/lib/capability.js
- packages/globals/lib/index.d.ts
- packages/nest/lib/capability.js
- packages/node/lib/capability.js
- packages/node/test/fixtures/fastify-with-build-standalone/services/frontend/index.js
- packages/node/test/misc.test.js
- packages/runtime/fixtures/delayed-shutdown/start-and-stop.js
- packages/runtime/fixtures/unhandled-mode/node/index.js
- packages/runtime/fixtures/unhandled-mode/service/index.js
- packages/runtime/index.js
- packages/runtime/lib/runtime.js
- packages/runtime/lib/worker/main.js
- packages/runtime/package.json
- packages/runtime/test/graceful-close.test.js
- pnpm-lock.yaml
Fixes https://github.com/platformatic/platformatic/issues/4301
> Run onClose hook for Fastify Node apps
